In [1]:
import torch
import os 
import json
import torch_geometric
import re
import gc
import wandb
import optuna
import warnings
import time

from torch.utils.data import TensorDataset, DataLoader, WeightedRandomSampler
from torch_geometric.data import Data, HeteroData, Batch
from torch_geometric.loader import DataLoader
from torch_geometric.utils import to_dense_adj
from torch_geometric.nn import to_hetero
from collections import defaultdict, Counter
from tqdm import tqdm
from sklearn.metrics import ndcg_score
from itertools import groupby, permutations
from transformers import AutoTokenizer, AutoModel
from optuna.integration.wandb import WeightsAndBiasesCallback

import torch.nn.functional as F
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import networkx as nx
import numpy as np
import pandas as pd
import torch.nn as nn
import torch_geometric.nn as geom_nn
import torch_geometric.data as geom_data

C:\Users\roans\anaconda3.0\envs\transformers\lib\site-packages\torch\cuda\__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [2]:
# different metric (also ndcg@20)+
# add more randomo 0s

In [3]:
torch_geometric.__version__, torch.__version__

('2.7.0', '2.6.0+cu124')

In [4]:
device = ("cuda:0" if torch.cuda.is_available() else "cpu")
device, torch.cuda.get_device_name(0)

('cuda:0', 'NVIDIA GeForce RTX 4070 Ti')

In [5]:
import copy
import warnings
from typing import Any, Dict, List, Optional, Union

import torch
from torch import Tensor
from torch.nn import Module, Parameter

from torch_geometric.nn.conv import MessagePassing
from torch_geometric.nn.dense import Linear
from torch_geometric.nn.fx import Transformer
from torch_geometric.typing import EdgeType, Metadata, NodeType, SparseTensor
from torch_geometric.utils.hetero import get_unused_node_types

try:
    from torch.fx import Graph, GraphModule, Node
except (ImportError, ModuleNotFoundError, AttributeError):
    GraphModule, Graph, Node = 'GraphModule', 'Graph', 'Node'


def to_hetero_with_bases(module: Module, metadata: Metadata, num_bases: int,
                         in_channels: Optional[Dict[str, int]] = None,
                         input_map: Optional[Dict[str, str]] = None,
                         debug: bool = False) -> GraphModule:

    transformer = ToHeteroWithBasesTransformer(module, metadata, num_bases,
                                               in_channels, input_map, debug)
    return transformer.transform()



class ToHeteroWithBasesTransformer(Transformer):
    def __init__(
        self,
        module: Module,
        metadata: Metadata,
        num_bases: int,
        in_channels: Optional[Dict[str, int]] = None,
        input_map: Optional[Dict[str, str]] = None,
        debug: bool = False,
    ):
        super().__init__(module, input_map, debug)

        self.metadata = metadata
        self.num_bases = num_bases
        self.in_channels = in_channels or {}
        assert len(metadata) == 2
        assert len(metadata[0]) > 0 and len(metadata[1]) > 0

        self.validate()

        # Compute IDs for each node and edge type:
        self.node_type2id = {k: i for i, k in enumerate(metadata[0])}
        self.edge_type2id = {k: i for i, k in enumerate(metadata[1])}

    def validate(self):
        unused_node_types = get_unused_node_types(*self.metadata)
        if len(unused_node_types) > 0:
            warnings.warn(
                f"There exist node types ({unused_node_types}) whose "
                f"representations do not get updated during message passing "
                f"as they do not occur as destination type in any edge type. "
                f"This may lead to unexpected behavior.")

        names = self.metadata[0] + [rel for _, rel, _ in self.metadata[1]]
        for name in names:
            if not name.isidentifier():
                warnings.warn(
                    f"The type '{name}' contains invalid characters which "
                    f"may lead to unexpected behavior. To avoid any issues, "
                    f"ensure that your types only contain letters, numbers "
                    f"and underscores.")

    def transform(self) -> GraphModule:
        self._node_offset_dict_initialized = False
        self._edge_offset_dict_initialized = False
        self._edge_type_initialized = False
        out = super().transform()
        del self._node_offset_dict_initialized
        del self._edge_offset_dict_initialized
        del self._edge_type_initialized
        return out

    def placeholder(self, node: Node, target: Any, name: str):
        if node.type is not None:
            Type = EdgeType if self.is_edge_level(node) else NodeType
            node.type = Dict[Type, node.type]

        out = node

        # Create `node_offset_dict` and `edge_offset_dict` dictionaries in case
        # they are not yet initialized. These dictionaries hold the cumulated
        # sizes used to create a unified graph representation and to split the
        # output data.
        if self.is_edge_level(node) and not self._edge_offset_dict_initialized:
            self.graph.inserting_after(out)
            out = self.graph.create_node('call_function',
                                         target=get_edge_offset_dict,
                                         args=(node, self.edge_type2id),
                                         name='edge_offset_dict')
            self._edge_offset_dict_initialized = True

        elif not self._node_offset_dict_initialized:
            self.graph.inserting_after(out)
            out = self.graph.create_node('call_function',
                                         target=get_node_offset_dict,
                                         args=(node, self.node_type2id),
                                         name='node_offset_dict')
            self._node_offset_dict_initialized = True

        # Create a `edge_type` tensor used as input to `HeteroBasisConv`:
        if self.is_edge_level(node) and not self._edge_type_initialized:
            self.graph.inserting_after(out)
            out = self.graph.create_node('call_function', target=get_edge_type,
                                         args=(node, self.edge_type2id),
                                         name='edge_type')
            self._edge_type_initialized = True

        # Add `Linear` operation to align features to the same dimensionality:
        if name in self.in_channels:
            self.graph.inserting_after(out)
            out = self.graph.create_node('call_module',
                                         target=f'align_lin__{name}',
                                         args=(node, ),
                                         name=f'{name}__aligned')
            self._state[out.name] = self._state[name]

            lin = LinearAlign(self.metadata[int(self.is_edge_level(node))],
                              self.in_channels[name])
            setattr(self.module, f'align_lin__{name}', lin)

        # Perform grouping of type-wise values into a single tensor:
        if self.is_edge_level(node):
            self.graph.inserting_after(out)
            out = self.graph.create_node(
                'call_function', target=group_edge_placeholder,
                args=(out if name in self.in_channels else node,
                      self.edge_type2id,
                      self.find_by_name('node_offset_dict')),
                name=f'{name}__grouped')
            self._state[out.name] = 'edge'

        else:
            self.graph.inserting_after(out)
            out = self.graph.create_node(
                'call_function', target=group_node_placeholder,
                args=(out if name in self.in_channels else node,
                      self.node_type2id), name=f'{name}__grouped')
            self._state[out.name] = 'node'

        self.replace_all_uses_with(node, out)

    def call_message_passing_module(self, node: Node, target: Any, name: str):
        # Call the `HeteroBasisConv` wrapper instead instead of a single
        # message passing layer. We need to inject the `edge_type` as first
        # argument in order to do so.
        node.args = (self.find_by_name('edge_type'), ) + node.args

    def output(self, node: Node, target: Any, name: str):
        # Split the output to dictionaries, holding either node type-wise or
        # edge type-wise data.
        def _recurse(value: Any) -> Any:
            if isinstance(value, Node) and self.is_edge_level(value):
                self.graph.inserting_before(node)
                return self.graph.create_node(
                    'call_function', target=split_output,
                    args=(value, self.find_by_name('edge_offset_dict')),
                    name=f'{value.name}__split')

                pass
            elif isinstance(value, Node):
                self.graph.inserting_before(node)
                return self.graph.create_node(
                    'call_function', target=split_output,
                    args=(value, self.find_by_name('node_offset_dict')),
                    name=f'{value.name}__split')

            elif isinstance(value, dict):
                return {k: _recurse(v) for k, v in value.items()}
            elif isinstance(value, list):
                return [_recurse(v) for v in value]
            elif isinstance(value, tuple):
                return tuple(_recurse(v) for v in value)
            else:
                return value

        if node.type is not None and isinstance(node.args[0], Node):
            output = node.args[0]
            Type = EdgeType if self.is_edge_level(output) else NodeType
            node.type = Dict[Type, node.type]
        else:
            node.type = None

        node.args = (_recurse(node.args[0]), )

    def init_submodule(self, module: Module, target: str) -> Module:
        if not isinstance(module, MessagePassing):
            return module

        # Replace each `MessagePassing` module by a `HeteroBasisConv` wrapper:
        return HeteroBasisConv(module, len(self.metadata[1]), self.num_bases)


###############################################################################


class HeteroBasisConv(torch.nn.Module):
    # A wrapper layer that applies the basis-decomposition technique to a
    # heterogeneous graph.
    def __init__(self, module: MessagePassing, num_relations: int,
                 num_bases: int):
        super().__init__()

        self.num_relations = num_relations
        self.num_bases = num_bases

        # We make use of a post-message computation hook to inject the
        # basis re-weighting for each individual edge type.
        # This currently requires us to set `conv.fuse = False`, which leads
        # to a materialization of messages.
        def hook(module, inputs, output):
            assert isinstance(module._edge_type, Tensor)
            if module._edge_type.size(0) != output.size(0):
                raise ValueError(
                    f"Number of messages ({output.size(0)}) does not match "
                    f"with the number of original edges "
                    f"({module._edge_type.size(0)}). Does your message "
                    f"passing layer create additional self-loops? Try to "
                    f"remove them via 'add_self_loops=False'")
            weight = module.edge_type_weight.view(-1)[module._edge_type]
            weight = weight.view([-1] + [1] * (output.dim() - 1))
            return weight * output

        params = list(module.parameters())
        device = params[0].device if len(params) > 0 else 'cpu'

        self.convs = torch.nn.ModuleList()
        for _ in range(num_bases):
            conv = copy.deepcopy(module)
            conv.fuse = False  # Disable `message_and_aggregate` functionality.
            # We learn a single scalar weight for each individual edge type,
            # which is used to weight the output message based on edge type:
            conv.edge_type_weight = Parameter(
                torch.empty(1, num_relations, device=device))
            conv.register_message_forward_hook(hook)
            self.convs.append(conv)

        if self.num_bases > 1:
            self.reset_parameters()

    def reset_parameters(self):
        for conv in self.convs:
            if hasattr(conv, 'reset_parameters'):
                conv.reset_parameters()
            elif sum([p.numel() for p in conv.parameters()]) > 0:
                warnings.warn(
                    f"'{conv}' will be duplicated, but its parameters cannot "
                    f"be reset. To suppress this warning, add a "
                    f"'reset_parameters()' method to '{conv}'")
            torch.nn.init.xavier_uniform_(conv.edge_type_weight)

    def forward(self, edge_type: Tensor, *args, **kwargs) -> Tensor:
        out = None
        
        attention = []
        
        # Call message passing modules and perform aggregation:
        for conv in self.convs:
            conv._edge_type = edge_type
                        
            # res, (edge_ind_exp, att_weight_exp) = conv(*args, **kwargs)
            res = conv(*args, **kwargs)
            del conv._edge_type
            
            # attention.append(att_weight_exp)
            
            out = res if out is None else out.add_(res)
            
            # jump
        
        return out #, (edge_type, edge_ind_exp, torch.mean(torch.stack(attention, dim=0), dim=0))

    def __repr__(self) -> str:
        return (f'{self.__class__.__name__}(num_relations='
                f'{self.num_relations}, num_bases={self.num_bases})')


class LinearAlign(torch.nn.Module):
    # Aligns representions to the same dimensionality. Note that this will
    # create lazy modules, and as such requires a forward pass in order to
    # initialize parameters.
    def __init__(self, keys: List[Union[NodeType, EdgeType]],
                 out_channels: int):
        super().__init__()
        self.out_channels = out_channels
        self.lins = torch.nn.ModuleDict()
        for key in keys:
            self.lins[key2str(key)] = Linear(-1, out_channels, bias=False)

    def forward(
        self, x_dict: Dict[Union[NodeType, EdgeType], Tensor]
    ) -> Dict[Union[NodeType, EdgeType], Tensor]:
        
        return {key: self.lins[key2str(key)](x) for key, x in x_dict.items()}

    def __repr__(self) -> str:
        return (f'{self.__class__.__name__}(num_relations={len(self.lins)}, '
                f'out_channels={self.out_channels})')


###############################################################################

# These methods are used in order to receive the cumulated sizes of input
# dictionaries. We make use of them for creating a unified homogeneous graph
# representation, as well as to split the final output data once again.


def get_node_offset_dict(
    input_dict: Dict[NodeType, Union[Tensor, SparseTensor]],
    type2id: Dict[NodeType, int],
) -> Dict[NodeType, int]:
    cumsum = 0
    out: Dict[NodeType, int] = {}
    
    for key in type2id.keys():
        out[key] = cumsum
        cumsum += input_dict[key].size(0)

    return out


def get_edge_offset_dict(
    input_dict: Dict[EdgeType, Union[Tensor, SparseTensor]],
    type2id: Dict[EdgeType, int],
) -> Dict[EdgeType, int]:
    cumsum = 0
    out: Dict[EdgeType, int] = {}
    for key in type2id.keys():
        out[key] = cumsum
        value = input_dict[key]
        if isinstance(value, SparseTensor):
            cumsum += value.nnz()
        elif value.dtype == torch.long and value.size(0) == 2:
            cumsum += value.size(-1)
        else:
            cumsum += value.size(0)

    return out


###############################################################################

# This method computes the edge type of the final homogeneous graph
# representation. It will be used in the `HeteroBasisConv` wrapper.


def get_edge_type(
    input_dict: Dict[EdgeType, Union[Tensor, SparseTensor]],
    type2id: Dict[EdgeType, int],
) -> Tensor:

    inputs = [input_dict[key] for key in type2id.keys()]
    outs = []

    for i, value in enumerate(inputs):
        if value.size(0) == 2 and value.dtype == torch.long:  # edge_index
            out = value.new_full((value.size(-1), ), i, dtype=torch.long)
        elif isinstance(value, SparseTensor):
            out = torch.full((value.nnz(), ), i, dtype=torch.long,
                             device=value.device())
        else:
            out = value.new_full((value.size(0), ), i, dtype=torch.long)
        outs.append(out)
    
    return outs[0] if len(outs) == 1 else torch.cat(outs, dim=0)


###############################################################################

# These methods are used to group the individual type-wise components into a
# unfied single representation.


def group_node_placeholder(input_dict: Dict[NodeType, Tensor],
                           type2id: Dict[NodeType, int]) -> Tensor:

    inputs = [input_dict[key] for key in type2id.keys()]
    return inputs[0] if len(inputs) == 1 else torch.cat(inputs, dim=0)


def group_edge_placeholder(
    input_dict: Dict[EdgeType, Union[Tensor, SparseTensor]],
    type2id: Dict[EdgeType, int],
    offset_dict: Dict[NodeType, int] = None,
) -> Union[Tensor, SparseTensor]:

    inputs = [input_dict[key] for key in type2id.keys()]

    if len(inputs) == 1:
        return inputs[0]

    # In case of grouping a graph connectivity tensor `edge_index` or `adj_t`,
    # we need to increment its indices:
    elif inputs[0].size(0) == 2 and inputs[0].dtype == torch.long:
        if offset_dict is None:
            raise AttributeError(
                "Can not infer node-level offsets. Please ensure that there "
                "exists a node-level argument before the 'edge_index' "
                "argument in your forward header.")

        outputs = []
        for value, (src_type, _, dst_type) in zip(inputs, type2id):
            value = value.clone()
            value[0, :] += offset_dict[src_type]
            value[1, :] += offset_dict[dst_type]
            outputs.append(value)

        return torch.cat(outputs, dim=-1)

    elif isinstance(inputs[0], SparseTensor):
        if offset_dict is None:
            raise AttributeError(
                "Can not infer node-level offsets. Please ensure that there "
                "exists a node-level argument before the 'SparseTensor' "
                "argument in your forward header.")

        # For grouping a list of SparseTensors, we convert them into a
        # unified `edge_index` representation in order to avoid conflicts
        # induced by re-shuffling the data.
        rows, cols = [], []
        for value, (src_type, _, dst_type) in zip(inputs, type2id):
            col, row, value = value.coo()
            assert value is None
            rows.append(row + offset_dict[src_type])
            cols.append(col + offset_dict[dst_type])

        row = torch.cat(rows, dim=0)
        col = torch.cat(cols, dim=0)
        return torch.stack([row, col], dim=0)

    else:
        return torch.cat(inputs, dim=0)


###############################################################################

# This method is used to split the output tensors into individual type-wise
# components:


def split_output(
    output: Tensor,
    offset_dict: Union[Dict[NodeType, int], Dict[EdgeType, int]],
) -> Union[Dict[NodeType, Tensor], Dict[EdgeType, Tensor]]:
    
    # Sometimes an edge index ends up here. Not sure why. TODO: fix --> we should be able to determine which edge belongs
    # to which edge type
    if type(output) == tuple:
        return output
    elif output.size(0) == 2:
        output = output.T
        
    cumsums = list(offset_dict.values()) + [output.size(0)]    
    sizes = [cumsums[i + 1] - cumsums[i] for i in range(len(offset_dict))]
    outputs = output.split(sizes)
    
    return {key: output for key, output in zip(offset_dict, outputs)}


###############################################################################


def key2str(key: Union[NodeType, EdgeType]) -> str:
    key = '__'.join(key) if isinstance(key, tuple) else key
    return key.replace(' ', '_').replace('-', '_').replace(':', '_')

In [6]:
def listwise_loss(scores, labels):
    if labels.size(0) < 2:
        return torch.zeros((labels.size(0), 1), device=scores.device)

    # 1. Expand scores and labels into [N, N] matrices
    # S_i[i, j] is score of doc i, S_j[i, j] is score of doc j
    s_i = scores.view(-1, 1)
    s_j = scores.view(1, -1)
    l_i = labels.view(-1, 1)
    l_j = labels.view(1, -1)

    # 2. Only compute loss for pairs where label_i > label_j
    # This removes the "Intra-label Noise"
    pair_mask = (l_i > l_j).float()
    
    # 3. Calculate RankNet Gradient: sigmoid(s_j - s_i)
    # Using the property: 1 / (1 + exp(s_i - s_j)) = sigmoid(s_j - s_i)
    sigma = 1.0
    lambda_ij = torch.sigmoid(sigma * (s_j - s_i))

    # 4. Calculate Delta-NDCG
    # We sort to get the ranks
    sorted_idx = torch.argsort(scores.view(-1), descending=True)
    ranks = torch.zeros_like(sorted_idx)
    ranks[sorted_idx] = torch.arange(len(scores), device=scores.device)
    
    # Ranks for i and j
    r_i = ranks.view(-1, 1)
    r_j = ranks.view(1, -1)
    
    # Ideal DCG for normalization
    ideal_labels, _ = torch.sort(labels, descending=True)
    k = torch.arange(1, len(labels) + 1, device=scores.device)
    idcg = torch.sum((2**ideal_labels - 1) / torch.log2(k + 1))
    
    if idcg == 0: return torch.zeros_like(scores)

    # Calculate how much NDCG would change if we swapped i and j
    # (2^li - 2^lj) * (1/log(ri+1) - 1/log(rj+1))
    gain_diff = (2**l_i - 2**l_j)
    decay_diff = (1.0 / torch.log2(r_i + 2.0) - 1.0 / torch.log2(r_j + 2.0)).abs()
    delta_ndcg = (gain_diff * decay_diff) / idcg

    # 5. Aggregate Lambdas
    # Total force on doc i is the sum of all pairs where i is better than j
    # and all pairs where j is better than i (with flipped sign)
    # Force on i = sum_j (lambda_ij * delta_ndcg) where l_i > l_j
    # minus sum_j (lambda_ji * delta_ndcg) where l_j > l_i
    
    # This simplifies to:
    force_matrix = lambda_ij * delta_ndcg * pair_mask
    lambda_i = -torch.sum(force_matrix, dim=1) + torch.sum(force_matrix, dim=0)
    
    return lambda_i.view(-1, 1)

In [7]:
class InitialTransformLayer(torch.nn.Module):
    def __init__(self, embedding_size=32):
        super().__init__()        
        self.lin = nn.LazyLinear(embedding_size) 
        self.relu = nn.ReLU()

    # Add 'edge_index' here so it matches the call signature
    def forward(self, x, edge_index=None): 
        # We ignore edge_index to ensure it never returns 'None'
        return self.relu(self.lin(x))

class GNN(torch.nn.Module):
    def __init__(self, embedding_size=64, heads=4):
        super().__init__()
        self.pre_conv = geom_nn.TransformerConv(embedding_size, embedding_size)
        
        self.can_pos = geom_nn.GATv2Conv((-1, -1), out_channels=embedding_size, heads=heads, concat=False, add_self_loops=False)
        self.can_neg = geom_nn.GATv2Conv((-1, -1), out_channels=embedding_size, heads=heads, concat=False, add_self_loops=False)
        self.com_pos = geom_nn.GATv2Conv((-1, -1), out_channels=embedding_size, heads=heads, concat=False, add_self_loops=False)
        self.com_neg = geom_nn.GATv2Conv((-1, -1), out_channels=embedding_size, heads=heads, concat=False, add_self_loops=False)
        
        self.batch_norm = torch.nn.ModuleList([torch.nn.BatchNorm1d(embedding_size) for _ in range(4)])
        self.elu = nn.ELU()
        
    def forward(self, x, edge_index):            
        # Initial Message Passing (Basis-friendly)
        x = self.pre_conv(x, edge_index)
        
        # Multi-View logic
        x_can = self.can_neg(self.can_pos(x, edge_index.long()), edge_index.long())
        x_com = self.com_neg(self.com_pos(x * -1, edge_index[[1,0]].long()), edge_index[[1,0]].long())
        
        x_can = self.batch_norm[1](self.batch_norm[0](x_can))
        x_com = self.batch_norm[3](self.batch_norm[2](x_com))
         
        x_can, x_com = self.elu(x_can), self.elu(x_com)
        return torch.cat([x_can, x_com], dim=-1)

# Final Heterogeneous Wrapper
class OKRA(torch.nn.Module):
    def __init__(self, metadata, embedding_size=64, pooling_method="mean", heads=4):
        super().__init__()
        
        self.metadata = metadata
        self.num_heads = heads
        self.embedding_size = embedding_size
        
        self.pooling = {
            "mean": lambda x, dim: torch.mean(x, dim=dim),
            "sum": lambda x, dim: torch.sum(x, dim=dim),
            "max": lambda x, dim: torch.max(x, dim=dim)[0]
        }[pooling_method]
        
        # Initial transformation
        self.embedder = InitialTransformLayer(embedding_size=embedding_size)
        self.embedder = to_hetero(self.embedder, metadata, aggr='sum')

        self.gnn = GNN(embedding_size=embedding_size, heads=heads)
        self.gnn = to_hetero_with_bases(self.gnn, metadata, num_bases=3)
        
        # Adjust MLP size: (2 core nodes + 1 pooled context) * embedding_size
        self.mlp_candidate = nn.Linear(embedding_size * 3, 1)
        self.mlp_company = nn.Linear(embedding_size * 3, 1)

        self.sigmoid = nn.Sigmoid()
        
    def forward(self, data):
        # Device and Dtype setup
        ref_key = next(iter(data.x_dict))
        device = data.x_dict[ref_key].device
        dtype = torch.float32

        # Heal input gaps
        initial_x = {}
        for ntype in self.metadata[0]:
            if ntype in data.x_dict and data.x_dict[ntype] is not None:
                initial_x[ntype] = data.x_dict[ntype].to(dtype)
            else:
                initial_x[ntype] = torch.zeros((1, 32), device=device, dtype=dtype)

        # Heal edge gaps
        safe_edge_dict = {}
        for triplet in self.metadata[1]:
            if triplet in data.edge_index_dict:
                safe_edge_dict[triplet] = data.edge_index_dict[triplet]
            else:
                # Provide empty indices so the GNN doesn't KeyError
                safe_edge_dict[triplet] = torch.empty((2, 0), device=device, dtype=torch.long)

        # Embed
        embedded_dict = self.embedder(initial_x, safe_edge_dict)       
        gnn_out = self.gnn(embedded_dict, safe_edge_dict)       

        # Split and pool 
        x_can_dict, x_com_dict = {}, {}
        for ntype, val in gnn_out.items():
            if val is not None:
                x_can_dict[ntype], x_com_dict[ntype] = torch.chunk(val, 2, dim=-1)
            else:
                # Safety fallback for types that weren't updated by GNN
                num_nodes = initial_x[ntype].size(0)
                zeros = torch.zeros((num_nodes, self.embedding_size), device=device)
                x_can_dict[ntype], x_com_dict[ntype] = zeros, zeros

        sub_graphs_can, sub_graphs_com = defaultdict(list), defaultdict(list)
        main_nodes_can, main_nodes_com = defaultdict(list), defaultdict(list)
        
        main_candidate_embs = defaultdict(list)
        main_vacancy_embs = defaultdict(list)
        context_embs_can = defaultdict(list)
        context_embs_com = defaultdict(list)
        
        # Reference device for zero-padding
        ref_key = next(iter(data.x_dict))
        device = data.x_dict[ref_key].device

        for ntype in data.node_types:
            if ntype in x_can_dict:
                for i, emb in enumerate(x_can_dict[ntype]):
                    u_id = data[ntype].unique_node_id[i].item()
                    if u_id == 0: continue # Skip dummy
                    
                    sg = int(data[ntype].sub_graph[i].item())
                    
                    # Check if this specific node is a 'Main' node
                    is_head = u_id in data.head_nodes
                    is_tail = u_id in data.tail_nodes

                    if is_head:
                        main_candidate_embs[sg].append(emb)
                    if is_tail:
                        main_vacancy_embs[sg].append(emb)
                    
                    # All nodes (including head/tail) contribute to sub-graph context
                    context_embs_can[sg].append(emb.unsqueeze(0))
                    context_embs_com[sg].append(x_com_dict[ntype][i].unsqueeze(0))

        # Final Vector Construction
        final_can_list, final_com_list = [], []
        
        # We iterate through all sub-graphs present in this batch
        all_sgs = sorted(context_embs_can.keys())
        for sg in all_sgs:
            # Pool the general graph context (size: embedding_size)
            pooled_can_ctx = self.pooling(torch.stack(context_embs_can[sg]).squeeze(1), dim=0)
            pooled_com_ctx = self.pooling(torch.stack(context_embs_com[sg]).squeeze(1), dim=0)

            # Get ONE Candidate embedding (Mean pool if multiple found, zero if none)
            if main_candidate_embs[sg]:
                can_main = torch.mean(torch.stack(main_candidate_embs[sg]), dim=0)
            else:
                can_main = torch.zeros(self.embedding_size, device=device)

            # Get ONE Vacancy embedding (Mean pool if multiple found, zero if none)
            if main_vacancy_embs[sg]:
                vac_main = torch.mean(torch.stack(main_vacancy_embs[sg]), dim=0)
            else:
                vac_main = torch.zeros(self.embedding_size, device=device)

            # Construct fixed-size vectors (Always size 3 * embedding_size)
            # Order: [Candidate_Node, Vacancy_Node, Subgraph_Context]
            can_vec = torch.cat([can_main, vac_main, pooled_can_ctx])
            com_vec = torch.cat([can_main, vac_main, pooled_com_ctx]) # Using main nodes from com side if desired

            final_can_list.append(can_vec)
            final_com_list.append(com_vec)

        # Stack and Predict
        can_matrix = torch.stack(final_can_list, dim=0)
        com_matrix = torch.stack(final_com_list, dim=0)
                
        # Make predictions based on the sub-graph embeddings
        y_candidate = torch.clamp(self.mlp_candidate(can_matrix), min=-100, max=100)
        y_company = torch.clamp(self.mlp_company(com_matrix), min=-100, max=100)
        
        # Predicted score (Harmonic Mean)
        y_pred = torch.nan_to_num(2 * ((y_candidate * y_company) / (y_candidate + y_company + 1e-8))).squeeze()
        
        return y_pred, y_candidate, y_company, None

In [8]:
def train_loop(model, optimizer, trainloader, valloader, epochs=10, patience=4, kind="val"):
    ndcg_scores = []
    random_scores = []
    
    best_ndcg = -float('inf')
    patience_counter = 0
    
    # 1. Ensure optimizer is looking at the LATEST model parameters
    # (Especially important if you used to_hetero recently)
    optimizer.param_groups[0]['params'] = list(model.parameters())

    for epoch in range(epochs):
        model.train()
        for i, data in enumerate(trainloader):
            data = data.to(device)
            optimizer.zero_grad() 

            # Forward Pass
            y_pred, _, _, _ = model(data)

            data = data.to(device)
            optimizer.zero_grad() # Clear old gradients

            # Forward Pass
            y_pred, _, _, _ = model(data)

            # Calculate Gradient (lambda_i)
            lambda_i = listwise_loss(y_pred, data.y)
            torch.autograd.backward(y_pred.view(-1), lambda_i.view(-1))

            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            # Logging
            y_true = data.y.view(1, -1).cpu() 
            y_score = y_pred.detach().view(1, -1).cpu()
            
            # Use k=min(10, len(y_true)) to avoid errors on small batches
            batch_ndcg = ndcg_score(y_true, y_score, k=min(10, y_true.shape[1]))
            ndcg_scores.append(batch_ndcg)
            
            random_y = torch.rand_like(data.y).view(1, -1).cpu()
            random_scores.append(ndcg_score(y_true, random_y, k=min(10, y_true.shape[1])))

            print(" " * 100, end="\r")
            print(f"Epoch: {epoch + 1}, Batch: {i}/{len(trainloader)}, Pred Mean: {y_pred.mean().item():.4f}, NDCG: {batch_ndcg:.4f}", end="\r")

        print(f"\n\nTraining nDCG: {np.mean(ndcg_scores):.4f}")
        print(f"Training random nDCG: {np.mean(random_scores):.4f}\n")

        ndcg_scores = []
        random_scores = []
        
        # Evaluate model
        ndcg_val, random_scores_val = eval_loop(model, valloader, kind=kind)
        ndcg_outcome = np.mean(ndcg_val)
        
        print(f"\n{'Validation' if kind=='val' else 'Test'} nDCG: {np.mean(ndcg_val):.4f}")
        print(f"{'Validation' if kind=='val' else 'Test'}  random nDCG: {np.mean(random_scores_val):.4f}\n")

        # Check for improvement
        if ndcg_outcome > best_ndcg * 1:
            best_ndcg = ndcg_outcome
            best_epoch = epoch + 1
            patience_counter = 0
            # Save the best model state
            print(f"--> Improvement! Best nDCG: {best_ndcg:.4f}")
        else:
            patience_counter += 1
            print(f"--> No improvement. Patience: {patience_counter}/{patience}")

        # Stop if we haven't improved for 'patience' epochs
        if patience_counter >= patience:
            print(f"\nEarly stopping triggered at epoch {epoch + 1}")
            break
        
    return best_ndcg, best_epoch

def eval_loop(model, valloader, kind="val"):
    model.eval()
    ndcg_scores = []
    random_scores = []

    with torch.no_grad():
        for i, data_val in enumerate(valloader):
            data_val = data_val.to(device)
            print(f"Batch ({kind}): {i + 1}/{len(valloader)}", end="\r")
            
            y_pred_val, _, _, _ = model(data_val)
             
            y_true = data_val.y.unsqueeze(0).cpu()
            y_score = y_pred_val.unsqueeze(0).cpu()

            ndcg_scores.append(ndcg_score(y_true, y_score, k=10))
            random_scores.append(ndcg_score(y_true, torch.rand_like(data_val.y).unsqueeze(0).cpu(), k=10))
            
    return ndcg_scores, random_scores

In [9]:
def optimize_model(trial, trainloader, valloader, epochs=10, patience=4):
    # Grab an example batch to get the metadata for the HeteroGNN structure
    example_batch = next(iter(trainloader))

    # Cleaned up search space (No textual params)
    learning_rate = trial.suggest_float('learning_rate', 1e-4, 1e-2, log=True)
    embedding_size = trial.suggest_categorical('embedding_size', [8, 16, 32, 64, 128])
    pooling_method = trial.suggest_categorical('pooling_method', ["mean", "max", "sum"])
    heads = trial.suggest_categorical('heads', [2, 4, 8])
                                        
    print(f"""
    Config:
    - learning_rate = {learning_rate}
    - embedding_size = {embedding_size}
    - pooling_method = {pooling_method}
    - heads = {heads}
    """)

    model = OKRA(
        metadata=example_batch.metadata(),
        embedding_size=embedding_size,
        pooling_method=pooling_method,
        heads=heads
    ).to(device)

    # Configure Optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    
    start_time = time.time() 
    
    # Train and evaluate model
    ndcg_scores_val, best_epoch = train_loop(model, optimizer, trainloader, valloader, epochs=epochs, patience=patience)
    
    trial.set_user_attr("epochs", best_epoch)
    
    end_time = time.time()
    
    print(f"Training for {epochs} epochs took {end_time - start_time:.2f} seconds")
    
    return np.mean(ndcg_scores_val)

In [10]:
def objective_wrapper(trainloader, valloader):
    def objective(trial):
        return optimize_model(trial, trainloader, valloader, epochs=15)
    
    return objective

In [12]:
results = defaultdict(list)

if "OKRA_validation.csv" in os.listdir():
    done = pd.read_csv("OKRA_validation.csv")
    
    completed_runs = set(
            zip(done['inference'].astype(bool), 
                done['isco'].astype(bool), 
                done['model'].astype(str), 
                done['prompt'].astype(str))
        )
    print(f"Resuming... Found {len(completed_runs)} completed configurations.")
else:
    completed_runs = set()

for inference in [True, False]:
    for isco in [True, False]:
        for model in ["qwen", "gemma", "llama"]:
            for prompt in ["structured", "semi-structured", "unstructured"]:
                # Check if this combination was already evaluated
                if (inference, isco, model, prompt) in completed_runs:
                    print(f"Skipping {model} {prompt} with inference={inference} and isco={isco} (Already done)")
                    continue
                
                if inference:
                    if isco:
                        trainloader = torch.load(f'../dataloaders/graph_trainloader_{model}_{prompt}_isco.pth',
                                                 weights_only=False)
                        valloader = torch.load(f'../dataloaders/graph_valloader_{model}_{prompt}_isco.pth',
                                               weights_only=False)
                    else:
                        trainloader = torch.load(f'../dataloaders/graph_trainloader_{model}_{prompt}.pth',
                                                 weights_only=False)
                        valloader = torch.load(f'../dataloaders/graph_valloader_{model}_{prompt}.pth',
                                               weights_only=False)
                else:
                    if isco:
                        trainloader = torch.load(f'../dataloaders/{model}_{prompt}_isco_trainloader_no_inference.pth',
                                                 weights_only=False)
                        valloader = torch.load(f'../dataloaders/{model}_{prompt}_isco_valloader_no_inference.pth',
                                               weights_only=False)
                    else:
                        trainloader = torch.load(f'../dataloaders/{model}_{prompt}_trainloader_no_inference.pth',
                                                 weights_only=False)
                        valloader = torch.load(f'../dataloaders/{model}_{prompt}_valloader_no_inference.pth',
                                               weights_only=False)
                    
                torch.cuda.empty_cache() 
                gc.collect()
                
                # Hide user/future warnings
                warnings.filterwarnings('ignore')
                
                # Define the Optuna study
                study = optuna.create_study(direction='maximize')
                print(f"Running study for {model} {prompt} with inference={inference} and isco={isco}")
                
                # We need to provide trainloader and valloader to the training/validation loop
                wrapped_objective = objective_wrapper(trainloader, valloader)
                
                # Start optimization
                study.optimize(wrapped_objective, n_trials=3)  
                
                print("Best hyperparameters:", study.best_trial.params)

                results["model"].append(model)
                results["prompt"].append(prompt)
                results["inference"].append(inference)
                results["isco"].append(isco)
                
                for param in study.best_trial.params:
                    results[param].append(study.best_trial.params[param])

                results["epochs"].append(study.best_trial.user_attrs["epochs"])

                results["nDCG@10 (val)"].append(study.best_value)
                    
                df_results = pd.DataFrame(results)
                display(df_results)

df_results.to_csv("OKRA_validation.csv")

[I 2026-06-08 01:20:47,596] A new study created in memory with name: no-name-8512ef6a-e265-41b3-b80c-9b5c2471de81

Running study for qwen structured with inference=True and isco=True

    Config:
    - learning_rate = 0.0004382333856990665
    - embedding_size = 128
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.0373, NDCG: 0.7039

Training nDCG: 0.6778
Training random nDCG: 0.3569

Batch (val): 41/41
Validation nDCG: 0.7695
Validation  random nDCG: 0.3831

--> Improvement! Best nDCG: 0.7695
Epoch: 2, Batch: 288/289, Pred Mean: 0.3304, NDCG: 0.8711

Training nDCG: 0.7567
Training random nDCG: 0.3940

Batch (val): 41/41
Validation nDCG: 0.7819
Validation  random nDCG: 0.4433

--> Improvement! Best nDCG: 0.7819
Epoch: 3, Batch: 288/289, Pred Mean: 0.5831, NDCG: 0.9060

Training nDCG: 0.7959
Training random nDCG: 0.3573

Batch (val): 41/41
Validation nDCG: 0.7619
Validation  random nDCG: 0.3141

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.2058, NDCG: 0.7328

Training nDCG: 0.8190
Training random nDCG: 0.3949

Batch (val): 41/41
Validation nDCG: 0.7921
Validation  random nDCG: 0.3809

--> Improvement! Best nDCG: 0.7921
Epoch: 5, Batch: 288/289, Pred Mean: 1.4019, NDCG: 0.7328

Training nDCG: 0.8307
Training random nDCG: 0.3719

Batch (val): 41/41
Validation nDCG: 0.7927
Validation  random nDCG: 0.3728

--> Improvement! Best nDCG: 0.7927
Epoch: 6, Batch: 288/289, Pred Mean: 1.5876, NDCG: 0.8855

Training nDCG: 0.8456
Training random nDCG: 0.3685

Batch (val): 41/41
Validation nDCG: 0.7929
Validation  random nDCG: 0.3816

--> Improvement! Best nDCG: 0.7929
Epoch: 7, Batch: 288/289, Pred Mean: 1.3559, NDCG: 0.9469

Training nDCG: 0.8608
Training random nDCG: 0.3667

Batch (val): 41/41
Validation nDCG: 0.7775
Validation  random nDCG: 0.4028

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.5591, NDCG: 0.9469

Training nDCG: 0.8804
Training random nDCG: 0.3620

Batch (val): 41/41
Validation nDCG: 0.7845
Validation  random nDCG: 0.3547

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.5945, NDCG: 0.9675

Training nDCG: 0.8857
Training random nDCG: 0.3754

Batch (val): 41/41
Validation nDCG: 0.7736
Validation  random nDCG: 0.3948

--> No improvement. Patience: 3/4
Epoch: 10, Batch: 288/289, Pred Mean: 2.1410, NDCG: 0.8529

Training nDCG: 0.8841
Training random nDCG: 0.3801

Batch (val): 41/41
Validation nDCG: 0.8058
Validation  random nDCG: 0.4054

--> Improvement! Best nDCG: 0.8058
Epoch: 11, Batch: 288/289, Pred Mean: 1.6693, NDCG: 0.7328

Training nDCG: 0.8959
Training random nDCG: 0.3720

Batch (val): 41/41
Validation nDCG: 0.8031
Validation  random nDCG: 0.3926

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: 1.5554, NDCG: 0.9675

Training nDCG: 0.9014
Training random nDCG: 0.3517

Batch (val): 41/41
Validation nDCG: 0.8047
Validation  random nDCG: 0.3963

--> No improvement. Patience: 2/4
Epoch: 13, Batch: 288/289, Pred Mean: 1.3168, NDCG: 1.0000

Training nDCG: 0.9143
Training random nDCG: 0.3783

Batch (val): 41/41
Validation nDCG: 0.8088
Validation  random nDCG: 0.3015

--> Improvement! Best nDCG: 0.8088
Epoch: 14, Batch: 288/289, Pred Mean: 1.3461, NDCG: 1.0000

Training nDCG: 0.9114
Training random nDCG: 0.3529

Batch (val): 41/41
Validation nDCG: 0.7932
Validation  random nDCG: 0.3747

--> No improvement. Patience: 1/4
Epoch: 15, Batch: 288/289, Pred Mean: 1.4963, NDCG: 0.9325

Training nDCG: 0.9133
Training random nDCG: 0.3470

Batch (val): 39/41

[I 2026-06-08 01:27:55,720] Trial 0 finished with value: 0.8087630974071186 and parameters: {'learning_rate': 0.0004382333856990665, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.8087630974071186.

Batch (val): 41/41
Validation nDCG: 0.7871
Validation  random nDCG: 0.3056

--> No improvement. Patience: 2/4
Training for 15 epochs took 427.91 seconds

    Config:
    - learning_rate = 0.0012856154878068266
    - embedding_size = 8
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.0552, NDCG: 0.6797

Training nDCG: 0.6124
Training random nDCG: 0.3854

Batch (val): 41/41
Validation nDCG: 0.7671
Validation  random nDCG: 0.4220

--> Improvement! Best nDCG: 0.7671
Epoch: 2, Batch: 288/289, Pred Mean: 0.7287, NDCG: 0.7328

Training nDCG: 0.7808
Training random nDCG: 0.3703

Batch (val): 41/41
Validation nDCG: 0.7820
Validation  random nDCG: 0.3941

--> Improvement! Best nDCG: 0.7820
Epoch: 3, Batch: 288/289, Pred Mean: 1.0623, NDCG: 0.7328

Training nDCG: 0.8064
Training random nDCG: 0.3672

Batch (val): 41/41
Validation nDCG: 0.7916
Validation  random nDCG: 0.3353

--> Improvement! Best nDCG: 0.7916
Epoch: 4, Batch: 288/289, Pred Mean: 1.1778, NDCG: 0.9060

Training nDCG: 0.8126
Training random nDCG: 0.3528

Batch (val): 41/41
Validation nDCG: 0.7970
Validation  random nDCG: 0.3370

--> Improvement! Best nDCG: 0.7970
Epoch: 5, Batch: 288/289, Pred Mean: 1.2574, NDCG: 0.9675

Training nDCG: 0.8283
Training random nDCG: 0.3533

Batch (val): 41/41
Validation nDCG: 0.8020
Validation  random nDCG: 0.3505

--> Improvement! Best nDCG: 0.8020
Epoch: 6, Batch: 288/289, Pred Mean: 1.2552, NDCG: 0.9060

Training nDCG: 0.8365
Training random nDCG: 0.3590

Batch (val): 41/41
Validation nDCG: 0.7936
Validation  random nDCG: 0.3567

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.3126, NDCG: 0.9675

Training nDCG: 0.8476
Training random nDCG: 0.3784

Batch (val): 41/41
Validation nDCG: 0.8023
Validation  random nDCG: 0.3653

--> Improvement! Best nDCG: 0.8023
Epoch: 8, Batch: 288/289, Pred Mean: 1.1640, NDCG: 0.9060

Training nDCG: 0.8582
Training random nDCG: 0.3563

Batch (val): 41/41
Validation nDCG: 0.7931
Validation  random nDCG: 0.3908

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.1550, NDCG: 0.9060

Training nDCG: 0.8711
Training random nDCG: 0.3873

Batch (val): 41/41
Validation nDCG: 0.7958
Validation  random nDCG: 0.4101

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.2885, NDCG: 0.9675

Training nDCG: 0.8760
Training random nDCG: 0.3552

Batch (val): 41/41
Validation nDCG: 0.8075
Validation  random nDCG: 0.3268

--> Improvement! Best nDCG: 0.8075
Epoch: 11, Batch: 288/289, Pred Mean: 1.2386, NDCG: 0.9060

Training nDCG: 0.8840
Training random nDCG: 0.3644

Batch (val): 41/41
Validation nDCG: 0.8048
Validation  random nDCG: 0.3183

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: 1.3327, NDCG: 0.9060

Training nDCG: 0.8878
Training random nDCG: 0.3404

Batch (val): 41/41
Validation nDCG: 0.7904
Validation  random nDCG: 0.4023

--> No improvement. Patience: 2/4
Epoch: 13, Batch: 288/289, Pred Mean: 1.2433, NDCG: 0.9675

Training nDCG: 0.8920
Training random nDCG: 0.3584

Batch (val): 41/41
Validation nDCG: 0.8057
Validation  random nDCG: 0.3292

--> No improvement. Patience: 3/4
Epoch: 14, Batch: 288/289, Pred Mean: 1.4130, NDCG: 1.0000

Training nDCG: 0.8988
Training random nDCG: 0.3884

Batch (val): 41/41
Validation nDCG: 0.8082
Validation  random nDCG: 0.3269

--> Improvement! Best nDCG: 0.8082
Epoch: 15, Batch: 288/289, Pred Mean: 1.5246, NDCG: 0.9675

Training nDCG: 0.9057
Training random nDCG: 0.3544

Batch (val): 38/41

[I 2026-06-08 01:34:07,381] Trial 1 finished with value: 0.8082293714244813 and parameters: {'learning_rate': 0.0012856154878068266, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.8087630974071186.

Batch (val): 41/41
Validation nDCG: 0.8012
Validation  random nDCG: 0.4048

--> No improvement. Patience: 1/4
Training for 15 epochs took 371.63 seconds

    Config:
    - learning_rate = 0.0001752869356265148
    - embedding_size = 8
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.2965, NDCG: 0.3836

Training nDCG: 0.4697
Training random nDCG: 0.3817

Batch (val): 41/41
Validation nDCG: 0.5242
Validation  random nDCG: 0.3503

--> Improvement! Best nDCG: 0.5242
Epoch: 2, Batch: 288/289, Pred Mean: -0.9168, NDCG: 0.7654

Training nDCG: 0.6400
Training random nDCG: 0.3689

Batch (val): 41/41
Validation nDCG: 0.6333
Validation  random nDCG: 0.3439

--> Improvement! Best nDCG: 0.6333
Epoch: 3, Batch: 288/289, Pred Mean: -0.3075, NDCG: 0.6714

Training nDCG: 0.7206
Training random nDCG: 0.3704

Batch (val): 41/41
Validation nDCG: 0.6982
Validation  random nDCG: 0.3472

--> Improvement! Best nDCG: 0.6982
Epoch: 4, Batch: 288/289, Pred Mean: -0.2218, NDCG: 0.6714

Training nDCG: 0.7600
Training random nDCG: 0.3760

Batch (val): 41/41
Validation nDCG: 0.7124
Validation  random nDCG: 0.3859

--> Improvement! Best nDCG: 0.7124
Epoch: 5, Batch: 288/289, Pred Mean: -0.1269, NDCG: 0.8855

Training nDCG: 0.7787
Training random nDCG: 0.3680

Batch (val): 41/41
Validation nDCG: 0.7293
Validation  random nDCG: 0.3725

--> Improvement! Best nDCG: 0.7293
Epoch: 6, Batch: 288/289, Pred Mean: -0.0781, NDCG: 0.8855

Training nDCG: 0.7894
Training random nDCG: 0.3417

Batch (val): 41/41
Validation nDCG: 0.7541
Validation  random nDCG: 0.3045

--> Improvement! Best nDCG: 0.7541
Epoch: 7, Batch: 288/289, Pred Mean: -0.0439, NDCG: 0.8855

Training nDCG: 0.8022
Training random nDCG: 0.3589

Batch (val): 41/41
Validation nDCG: 0.7628
Validation  random nDCG: 0.3315

--> Improvement! Best nDCG: 0.7628
Epoch: 8, Batch: 288/289, Pred Mean: 0.0245, NDCG: 0.8855

Training nDCG: 0.8169
Training random nDCG: 0.3583

Batch (val): 41/41
Validation nDCG: 0.7725
Validation  random nDCG: 0.3158

--> Improvement! Best nDCG: 0.7725
Epoch: 9, Batch: 288/289, Pred Mean: 0.0985, NDCG: 0.8711

Training nDCG: 0.8327
Training random nDCG: 0.3539

Batch (val): 41/41
Validation nDCG: 0.7814
Validation  random nDCG: 0.4518

--> Improvement! Best nDCG: 0.7814
Epoch: 10, Batch: 288/289, Pred Mean: 0.2051, NDCG: 0.8180

Training nDCG: 0.8413
Training random nDCG: 0.3653

Batch (val): 41/41
Validation nDCG: 0.7828
Validation  random nDCG: 0.3942

--> Improvement! Best nDCG: 0.7828
Epoch: 11, Batch: 288/289, Pred Mean: 0.2953, NDCG: 0.8180

Training nDCG: 0.8504
Training random nDCG: 0.3721

Batch (val): 41/41
Validation nDCG: 0.7671
Validation  random nDCG: 0.3989

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: 0.3725, NDCG: 0.7929

Training nDCG: 0.8591
Training random nDCG: 0.3468

Batch (val): 41/41
Validation nDCG: 0.7814
Validation  random nDCG: 0.3524

--> No improvement. Patience: 2/4
Epoch: 13, Batch: 288/289, Pred Mean: 0.4652, NDCG: 0.7929

Training nDCG: 0.8590
Training random nDCG: 0.3633

Batch (val): 41/41
Validation nDCG: 0.7682
Validation  random nDCG: 0.3599

--> No improvement. Patience: 3/4
Epoch: 14, Batch: 288/289, Pred Mean: 0.5255, NDCG: 0.8603

Training nDCG: 0.8654
Training random nDCG: 0.3510

Batch (val): 41/41
Validation nDCG: 0.7883
Validation  random nDCG: 0.4129

--> Improvement! Best nDCG: 0.7883
Epoch: 15, Batch: 288/289, Pred Mean: 0.5595, NDCG: 0.9218

Training nDCG: 0.8725
Training random nDCG: 0.3948

Batch (val): 38/41

[I 2026-06-08 01:40:49,682] Trial 2 finished with value: 0.792897405399892 and parameters: {'learning_rate': 0.0001752869356265148, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.8087630974071186.

Batch (val): 41/41
Validation nDCG: 0.7929
Validation  random nDCG: 0.3488

--> Improvement! Best nDCG: 0.7929
Training for 15 epochs took 402.27 seconds
Best hyperparameters: {'learning_rate': 0.0004382333856990665, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763

[I 2026-06-08 01:40:50,389] A new study created in memory with name: no-name-9954b1b5-6e54-4946-ac90-b47971d67b35

Running study for qwen semi-structured with inference=True and isco=True

    Config:
    - learning_rate = 0.00048692826981980975
    - embedding_size = 32
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.3230, NDCG: 0.8180

Training nDCG: 0.6983
Training random nDCG: 0.3636

Batch (val): 41/41
Validation nDCG: 0.7769
Validation  random nDCG: 0.3601

--> Improvement! Best nDCG: 0.7769
Epoch: 2, Batch: 288/289, Pred Mean: 0.8571, NDCG: 0.8180

Training nDCG: 0.7902
Training random nDCG: 0.3767

Batch (val): 41/41
Validation nDCG: 0.7751
Validation  random nDCG: 0.3320

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.2531, NDCG: 0.6448

Training nDCG: 0.8087
Training random nDCG: 0.3794

Batch (val): 41/41
Validation nDCG: 0.7672
Validation  random nDCG: 0.2769

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.3201, NDCG: 0.6448

Training nDCG: 0.8287
Training random nDCG: 0.3758

Batch (val): 41/41
Validation nDCG: 0.7716
Validation  random nDCG: 0.3203

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.5349, NDCG: 0.6448

Training nDCG: 0.8549
Training random nDCG: 0.3652

Batch (val): 41/41
Validation nDCG: 0.7805
Validation  random nDCG: 0.3551

--> Improvement! Best nDCG: 0.7805
Epoch: 6, Batch: 288/289, Pred Mean: 1.6873, NDCG: 0.8180

Training nDCG: 0.8586
Training random nDCG: 0.3798

Batch (val): 41/41
Validation nDCG: 0.7676
Validation  random nDCG: 0.3599

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.6710, NDCG: 0.8529

Training nDCG: 0.8751
Training random nDCG: 0.3859

Batch (val): 41/41
Validation nDCG: 0.7570
Validation  random nDCG: 0.3663

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.6556, NDCG: 0.9060

Training nDCG: 0.8920
Training random nDCG: 0.3565

Batch (val): 41/41
Validation nDCG: 0.7602
Validation  random nDCG: 0.3170

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.7347, NDCG: 0.9060

Training nDCG: 0.8960
Training random nDCG: 0.3782

Batch (val): 41/41
Validation nDCG: 0.7800
Validation  random nDCG: 0.3631

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 222.36 seconds

[I 2026-06-08 01:44:32,784] Trial 0 finished with value: 0.7805240945242404 and parameters: {'learning_rate': 0.00048692826981980975, 'embedding_size': 32, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.7805240945242404.

    Config:
    - learning_rate = 0.00023786015558887347
    - embedding_size = 128
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.4351, NDCG: 0.8385

Training nDCG: 0.6915
Training random nDCG: 0.3710

Batch (val): 41/41
Validation nDCG: 0.7648
Validation  random nDCG: 0.3054

--> Improvement! Best nDCG: 0.7648
Epoch: 2, Batch: 288/289, Pred Mean: 0.9736, NDCG: 0.8180

Training nDCG: 0.7762
Training random nDCG: 0.3625

Batch (val): 41/41
Validation nDCG: 0.7824
Validation  random nDCG: 0.4250

--> Improvement! Best nDCG: 0.7824
Epoch: 3, Batch: 288/289, Pred Mean: 1.2287, NDCG: 0.6448

Training nDCG: 0.8144
Training random nDCG: 0.3708

Batch (val): 41/41
Validation nDCG: 0.7641
Validation  random nDCG: 0.4205

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.3840, NDCG: 0.8180

Training nDCG: 0.8443
Training random nDCG: 0.3564

Batch (val): 41/41
Validation nDCG: 0.7745
Validation  random nDCG: 0.3106

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.4345, NDCG: 0.7328

Training nDCG: 0.8536
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.7706
Validation  random nDCG: 0.2825

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.5136, NDCG: 0.8855

Training nDCG: 0.8741
Training random nDCG: 0.3661

Batch (val): 41/41
Validation nDCG: 0.7884
Validation  random nDCG: 0.3236

--> Improvement! Best nDCG: 0.7884
Epoch: 7, Batch: 288/289, Pred Mean: 1.7137, NDCG: 0.9469

Training nDCG: 0.8825
Training random nDCG: 0.3546

Batch (val): 41/41
Validation nDCG: 0.7798
Validation  random nDCG: 0.3237

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.7848, NDCG: 0.9469

Training nDCG: 0.8916
Training random nDCG: 0.3468

Batch (val): 41/41
Validation nDCG: 0.7810
Validation  random nDCG: 0.3487

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.8336, NDCG: 0.8385

Training nDCG: 0.8945
Training random nDCG: 0.3528

Batch (val): 41/41
Validation nDCG: 0.7930
Validation  random nDCG: 0.3750

--> Improvement! Best nDCG: 0.7930
Epoch: 10, Batch: 288/289, Pred Mean: 2.4809, NDCG: 0.6197

Training nDCG: 0.8967
Training random nDCG: 0.3816

Batch (val): 41/41
Validation nDCG: 0.7586
Validation  random nDCG: 0.3383

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: 2.2961, NDCG: 0.9469

Training nDCG: 0.9012
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.7805
Validation  random nDCG: 0.3799

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: 2.3493, NDCG: 0.9060

Training nDCG: 0.8984
Training random nDCG: 0.3446

Batch (val): 41/41
Validation nDCG: 0.7787
Validation  random nDCG: 0.3135

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: 2.2562, NDCG: 0.9675

Training nDCG: 0.8966
Training random nDCG: 0.3522

Batch (val): 36/41

[I 2026-06-08 01:49:50,278] Trial 1 finished with value: 0.7929560100007493 and parameters: {'learning_rate': 0.00023786015558887347, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 2}. Best is trial 1 with value: 0.7929560100007493.

Batch (val): 41/41
Validation nDCG: 0.7630
Validation  random nDCG: 0.3006

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 317.46 seconds

    Config:
    - learning_rate = 0.006518548218726926
    - embedding_size = 8
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.6798, NDCG: 0.9469

Training nDCG: 0.7108
Training random nDCG: 0.3593

Batch (val): 41/41
Validation nDCG: 0.7812
Validation  random nDCG: 0.4148

--> Improvement! Best nDCG: 0.7812
Epoch: 2, Batch: 288/289, Pred Mean: 1.3203, NDCG: 0.9675

Training nDCG: 0.7789
Training random nDCG: 0.3696

Batch (val): 41/41
Validation nDCG: 0.7695
Validation  random nDCG: 0.3377

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.3260, NDCG: 0.9675

Training nDCG: 0.8028
Training random nDCG: 0.3797

Batch (val): 41/41
Validation nDCG: 0.7678
Validation  random nDCG: 0.4293

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.1472, NDCG: 0.7123

Training nDCG: 0.7907
Training random nDCG: 0.3488

Batch (val): 41/41
Validation nDCG: 0.7465
Validation  random nDCG: 0.3937

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.5496, NDCG: 0.7123

Training nDCG: 0.8105
Training random nDCG: 0.3861

Batch (val): 40/41

[I 2026-06-08 01:51:52,605] Trial 2 finished with value: 0.7812038851240108 and parameters: {'learning_rate': 0.006518548218726926, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 4}. Best is trial 1 with value: 0.7929560100007493.

Batch (val): 41/41
Validation nDCG: 0.7514
Validation  random nDCG: 0.3049

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 122.30 seconds
Best hyperparameters: {'learning_rate': 0.00023786015558887347, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956

[I 2026-06-08 01:51:53,287] A new study created in memory with name: no-name-12905d24-099c-4367-b592-80f9607cf790

Running study for qwen unstructured with inference=True and isco=True

    Config:
    - learning_rate = 0.00024806135313421116
    - embedding_size = 16
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.0541, NDCG: 0.5706

Training nDCG: 0.5334
Training random nDCG: 0.4175

Batch (val): 41/41
Validation nDCG: 0.5697
Validation  random nDCG: 0.3872

--> Improvement! Best nDCG: 0.5697
Epoch: 2, Batch: 288/289, Pred Mean: -0.1303, NDCG: 0.6934

Training nDCG: 0.6915
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.6948
Validation  random nDCG: 0.3736

--> Improvement! Best nDCG: 0.6948
Epoch: 3, Batch: 288/289, Pred Mean: 0.1516, NDCG: 0.6934

Training nDCG: 0.7415
Training random nDCG: 0.4061

Batch (val): 41/41
Validation nDCG: 0.7320
Validation  random nDCG: 0.3844

--> Improvement! Best nDCG: 0.7320
Epoch: 4, Batch: 288/289, Pred Mean: 0.2432, NDCG: 0.6241

Training nDCG: 0.7689
Training random nDCG: 0.3794

Batch (val): 41/41
Validation nDCG: 0.7570
Validation  random nDCG: 0.3233

--> Improvement! Best nDCG: 0.7570
Epoch: 5, Batch: 288/289, Pred Mean: 0.2506, NDCG: 0.6241

Training nDCG: 0.7874
Training random nDCG: 0.3957

Batch (val): 41/41
Validation nDCG: 0.7622
Validation  random nDCG: 0.3964

--> Improvement! Best nDCG: 0.7622
Epoch: 6, Batch: 288/289, Pred Mean: 0.2740, NDCG: 0.8175

Training nDCG: 0.8071
Training random nDCG: 0.3739

Batch (val): 41/41
Validation nDCG: 0.7653
Validation  random nDCG: 0.3580

--> Improvement! Best nDCG: 0.7653
Epoch: 7, Batch: 288/289, Pred Mean: 0.3150, NDCG: 0.8772

Training nDCG: 0.8205
Training random nDCG: 0.3939

Batch (val): 41/41
Validation nDCG: 0.7663
Validation  random nDCG: 0.3621

--> Improvement! Best nDCG: 0.7663
Epoch: 8, Batch: 288/289, Pred Mean: 0.7138, NDCG: 0.3869

Training nDCG: 0.8277
Training random nDCG: 0.3878

Batch (val): 41/41
Validation nDCG: 0.7499
Validation  random nDCG: 0.3345

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.3006, NDCG: 0.8772

Training nDCG: 0.8378
Training random nDCG: 0.3908

Batch (val): 41/41
Validation nDCG: 0.7405
Validation  random nDCG: 0.3973

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 0.3969, NDCG: 0.3869

Training nDCG: 0.8385
Training random nDCG: 0.3845

Batch (val): 41/41
Validation nDCG: 0.7037
Validation  random nDCG: 0.4429

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.3473, NDCG: 0.6131

Training nDCG: 0.8418
Training random nDCG: 0.3815

Batch (val): 41/41
Validation nDCG: 0.7206
Validation  random nDCG: 0.3297

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 266.55 seconds

[I 2026-06-08 01:56:19,871] Trial 0 finished with value: 0.766273829706399 and parameters: {'learning_rate': 0.00024806135313421116, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}. Best is trial 0 with value: 0.766273829706399.

    Config:
    - learning_rate = 0.00037124462916325086
    - embedding_size = 16
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.0857, NDCG: 0.6934

Training nDCG: 0.5949
Training random nDCG: 0.3902

Batch (val): 41/41
Validation nDCG: 0.7100
Validation  random nDCG: 0.3665

--> Improvement! Best nDCG: 0.7100
Epoch: 2, Batch: 288/289, Pred Mean: -0.0442, NDCG: 0.9197

Training nDCG: 0.7637
Training random nDCG: 0.3835

Batch (val): 41/41
Validation nDCG: 0.7302
Validation  random nDCG: 0.3835

--> Improvement! Best nDCG: 0.7302
Epoch: 3, Batch: 288/289, Pred Mean: 0.2997, NDCG: 0.9197

Training nDCG: 0.7812
Training random nDCG: 0.3739

Batch (val): 41/41
Validation nDCG: 0.7572
Validation  random nDCG: 0.3465

--> Improvement! Best nDCG: 0.7572
Epoch: 4, Batch: 288/289, Pred Mean: 0.4661, NDCG: 0.8772

Training nDCG: 0.7955
Training random nDCG: 0.3933

Batch (val): 41/41
Validation nDCG: 0.7882
Validation  random nDCG: 0.3870

--> Improvement! Best nDCG: 0.7882
Epoch: 5, Batch: 288/289, Pred Mean: 0.3889, NDCG: 0.8772

Training nDCG: 0.8229
Training random nDCG: 0.3899

Batch (val): 41/41
Validation nDCG: 0.7719
Validation  random nDCG: 0.4651

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.6419, NDCG: 0.8503

Training nDCG: 0.8298
Training random nDCG: 0.3903

Batch (val): 41/41
Validation nDCG: 0.7702
Validation  random nDCG: 0.3100

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.5589, NDCG: 0.8772

Training nDCG: 0.8395
Training random nDCG: 0.3765

Batch (val): 41/41
Validation nDCG: 0.7791
Validation  random nDCG: 0.3239

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.4971, NDCG: 0.8772

Training nDCG: 0.8504
Training random nDCG: 0.4128

Batch (val): 36/41

[I 2026-06-08 01:59:27,949] Trial 1 finished with value: 0.7882081930330562 and parameters: {'learning_rate': 0.00037124462916325086, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 4}. Best is trial 1 with value: 0.7882081930330562.

Batch (val): 41/41
Validation nDCG: 0.7408
Validation  random nDCG: 0.3933

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 188.05 seconds

    Config:
    - learning_rate = 0.0010330327505085521
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.1938, NDCG: 0.6934

Training nDCG: 0.6181
Training random nDCG: 0.3891

Batch (val): 41/41
Validation nDCG: 0.6980
Validation  random nDCG: 0.3639

--> Improvement! Best nDCG: 0.6980
Epoch: 2, Batch: 288/289, Pred Mean: 0.6006, NDCG: 0.6509

Training nDCG: 0.7492
Training random nDCG: 0.3852

Batch (val): 41/41
Validation nDCG: 0.7646
Validation  random nDCG: 0.4351

--> Improvement! Best nDCG: 0.7646
Epoch: 3, Batch: 288/289, Pred Mean: 0.8498, NDCG: 0.6509

Training nDCG: 0.7665
Training random nDCG: 0.3787

Batch (val): 41/41
Validation nDCG: 0.7788
Validation  random nDCG: 0.3822

--> Improvement! Best nDCG: 0.7788
Epoch: 4, Batch: 288/289, Pred Mean: 1.1378, NDCG: 0.6509

Training nDCG: 0.7933
Training random nDCG: 0.3816

Batch (val): 41/41
Validation nDCG: 0.7799
Validation  random nDCG: 0.3547

--> Improvement! Best nDCG: 0.7799
Epoch: 5, Batch: 288/289, Pred Mean: 1.0247, NDCG: 0.5706

Training nDCG: 0.8110
Training random nDCG: 0.3801

Batch (val): 41/41
Validation nDCG: 0.7757
Validation  random nDCG: 0.3593

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.2372, NDCG: 0.6509

Training nDCG: 0.8233
Training random nDCG: 0.4077

Batch (val): 41/41
Validation nDCG: 0.7893
Validation  random nDCG: 0.3204

--> Improvement! Best nDCG: 0.7893
Epoch: 7, Batch: 288/289, Pred Mean: 1.5128, NDCG: 0.8772

Training nDCG: 0.8387
Training random nDCG: 0.3976

Batch (val): 41/41
Validation nDCG: 0.7820
Validation  random nDCG: 0.4020

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.1669, NDCG: 0.8772

Training nDCG: 0.8434
Training random nDCG: 0.3782

Batch (val): 41/41
Validation nDCG: 0.8035
Validation  random nDCG: 0.3848

--> Improvement! Best nDCG: 0.8035
Epoch: 9, Batch: 288/289, Pred Mean: 1.1725, NDCG: 0.8772

Training nDCG: 0.8500
Training random nDCG: 0.3885

Batch (val): 41/41
Validation nDCG: 0.8126
Validation  random nDCG: 0.3540

--> Improvement! Best nDCG: 0.8126
Epoch: 10, Batch: 288/289, Pred Mean: 1.3599, NDCG: 0.8772

Training nDCG: 0.8540
Training random nDCG: 0.3796

Batch (val): 41/41
Validation nDCG: 0.7887
Validation  random nDCG: 0.3670

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.5652, NDCG: 0.8772

Training nDCG: 0.8614
Training random nDCG: 0.3780

Batch (val): 41/41
Validation nDCG: 0.7949
Validation  random nDCG: 0.4007

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: 1.4291, NDCG: 0.8772

Training nDCG: 0.8662
Training random nDCG: 0.3881

Batch (val): 41/41
Validation nDCG: 0.7906
Validation  random nDCG: 0.3831

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: 1.7326, NDCG: 1.0000

Training nDCG: 0.8715
Training random nDCG: 0.3864

Batch (val): 38/41

[I 2026-06-08 02:04:33,923] Trial 2 finished with value: 0.8125629078086732 and parameters: {'learning_rate': 0.0010330327505085521, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 2 with value: 0.8125629078086732.

Batch (val): 41/41
Validation nDCG: 0.7718
Validation  random nDCG: 0.3522

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 305.95 seconds
Best hyperparameters: {'learning_rate': 0.0010330327505085521, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563

[I 2026-06-08 02:04:34,466] A new study created in memory with name: no-name-d4df8017-cc41-49ef-a3f3-d85ce7825106

Running study for gemma structured with inference=True and isco=True

    Config:
    - learning_rate = 0.006162396054165385
    - embedding_size = 128
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -3.8506, NDCG: 0.6979

Training nDCG: 0.7499
Training random nDCG: 0.3645

Batch (val): 41/41
Validation nDCG: 0.7840
Validation  random nDCG: 0.3752

--> Improvement! Best nDCG: 0.7840
Epoch: 2, Batch: 288/289, Pred Mean: -1.9249, NDCG: 0.8855

Training nDCG: 0.7777
Training random nDCG: 0.3465

Batch (val): 41/41
Validation nDCG: 0.7813
Validation  random nDCG: 0.2908

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -2.4488, NDCG: 0.9469

Training nDCG: 0.7856
Training random nDCG: 0.3591

Batch (val): 41/41
Validation nDCG: 0.8106
Validation  random nDCG: 0.3905

--> Improvement! Best nDCG: 0.8106
Epoch: 4, Batch: 288/289, Pred Mean: -0.7825, NDCG: 0.7123

Training nDCG: 0.7914
Training random nDCG: 0.3810

Batch (val): 41/41
Validation nDCG: 0.7838
Validation  random nDCG: 0.3779

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -2.1183, NDCG: 0.7123

Training nDCG: 0.7988
Training random nDCG: 0.3307

Batch (val): 41/41
Validation nDCG: 0.7857
Validation  random nDCG: 0.3245

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.6358, NDCG: 0.7123

Training nDCG: 0.8014
Training random nDCG: 0.3443

Batch (val): 41/41
Validation nDCG: 0.7742
Validation  random nDCG: 0.3842

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: -0.5080, NDCG: 0.9469

Training nDCG: 0.7886
Training random nDCG: 0.3665

Batch (val): 36/41

[I 2026-06-08 02:07:32,592] Trial 0 finished with value: 0.8106089335407566 and parameters: {'learning_rate': 0.006162396054165385, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 8}. Best is trial 0 with value: 0.8106089335407566.

Batch (val): 41/41
Validation nDCG: 0.7857
Validation  random nDCG: 0.3434

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 178.07 seconds

    Config:
    - learning_rate = 0.0007019686201876916
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.1123, NDCG: 0.6979

Training nDCG: 0.5662
Training random nDCG: 0.3362

Batch (val): 41/41
Validation nDCG: 0.6937
Validation  random nDCG: 0.3527

--> Improvement! Best nDCG: 0.6937
Epoch: 2, Batch: 288/289, Pred Mean: 0.4930, NDCG: 0.8529

Training nDCG: 0.7454
Training random nDCG: 0.3551

Batch (val): 41/41
Validation nDCG: 0.7659
Validation  random nDCG: 0.3737

--> Improvement! Best nDCG: 0.7659
Epoch: 3, Batch: 288/289, Pred Mean: 0.8441, NDCG: 0.8529

Training nDCG: 0.7820
Training random nDCG: 0.3675

Batch (val): 41/41
Validation nDCG: 0.7758
Validation  random nDCG: 0.3185

--> Improvement! Best nDCG: 0.7758
Epoch: 4, Batch: 288/289, Pred Mean: 0.9689, NDCG: 0.6797

Training nDCG: 0.7861
Training random nDCG: 0.3409

Batch (val): 41/41
Validation nDCG: 0.7728
Validation  random nDCG: 0.3733

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.0950, NDCG: 0.8529

Training nDCG: 0.8124
Training random nDCG: 0.3612

Batch (val): 41/41
Validation nDCG: 0.7999
Validation  random nDCG: 0.3776

--> Improvement! Best nDCG: 0.7999
Epoch: 6, Batch: 288/289, Pred Mean: 1.0322, NDCG: 0.8855

Training nDCG: 0.8495
Training random nDCG: 0.3546

Batch (val): 41/41
Validation nDCG: 0.8028
Validation  random nDCG: 0.4267

--> Improvement! Best nDCG: 0.8028
Epoch: 7, Batch: 288/289, Pred Mean: 1.3055, NDCG: 0.7123

Training nDCG: 0.8609
Training random nDCG: 0.3404

Batch (val): 41/41
Validation nDCG: 0.8045
Validation  random nDCG: 0.3654

--> Improvement! Best nDCG: 0.8045
Epoch: 8, Batch: 288/289, Pred Mean: 1.5447, NDCG: 0.7123

Training nDCG: 0.8754
Training random nDCG: 0.3642

Batch (val): 41/41
Validation nDCG: 0.8132
Validation  random nDCG: 0.3897

--> Improvement! Best nDCG: 0.8132
Epoch: 9, Batch: 288/289, Pred Mean: 1.6262, NDCG: 0.7123

Training nDCG: 0.8803
Training random nDCG: 0.3756

Batch (val): 41/41
Validation nDCG: 0.7802
Validation  random nDCG: 0.3886

--> No improvement. Patience: 1/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.6613, NDCG: 0.7123

Training nDCG: 0.8821
Training random nDCG: 0.3718

Batch (val): 41/41
Validation nDCG: 0.7924
Validation  random nDCG: 0.3559

--> No improvement. Patience: 2/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.7965, NDCG: 0.7328

Training nDCG: 0.8934
Training random nDCG: 0.3673

Batch (val): 41/41
Validation nDCG: 0.7781
Validation  random nDCG: 0.4049

--> No improvement. Patience: 3/4
Epoch: 12, Batch: 288/289, Pred Mean: 2.0079, NDCG: 0.7328

Training nDCG: 0.8982
Training random nDCG: 0.3853

Batch (val): 36/41

[I 2026-06-08 02:12:39,135] Trial 1 finished with value: 0.8131834514093154 and parameters: {'learning_rate': 0.0007019686201876916, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.8131834514093154.

Batch (val): 41/41
Validation nDCG: 0.7590
Validation  random nDCG: 0.4372

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 12
Training for 15 epochs took 306.51 seconds

    Config:
    - learning_rate = 0.00028237530727820637
    - embedding_size = 64
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.4501, NDCG: 0.4367

Training nDCG: 0.6188
Training random nDCG: 0.3664

Batch (val): 41/41
Validation nDCG: 0.7373
Validation  random nDCG: 0.3869

--> Improvement! Best nDCG: 0.7373
Epoch: 2, Batch: 288/289, Pred Mean: 0.8119, NDCG: 0.4367

Training nDCG: 0.6951
Training random nDCG: 0.3914

Batch (val): 41/41
Validation nDCG: 0.7753
Validation  random nDCG: 0.3401

--> Improvement! Best nDCG: 0.7753
Epoch: 3, Batch: 288/289, Pred Mean: 0.7585, NDCG: 0.6183

Training nDCG: 0.7689
Training random nDCG: 0.3750

Batch (val): 41/41
Validation nDCG: 0.7871
Validation  random nDCG: 0.3348

--> Improvement! Best nDCG: 0.7871
Epoch: 4, Batch: 288/289, Pred Mean: 0.9268, NDCG: 0.6183

Training nDCG: 0.8163
Training random nDCG: 0.3553

Batch (val): 41/41
Validation nDCG: 0.8018
Validation  random nDCG: 0.4045

--> Improvement! Best nDCG: 0.8018
Epoch: 5, Batch: 288/289, Pred Mean: 1.0188, NDCG: 0.6183

Training nDCG: 0.8444
Training random nDCG: 0.3476

Batch (val): 41/41
Validation nDCG: 0.8142
Validation  random nDCG: 0.3625

--> Improvement! Best nDCG: 0.8142
Epoch: 6, Batch: 288/289, Pred Mean: 1.0630, NDCG: 0.7123

Training nDCG: 0.8512
Training random nDCG: 0.3248

Batch (val): 41/41
Validation nDCG: 0.7902
Validation  random nDCG: 0.3869

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.1443, NDCG: 0.7123

Training nDCG: 0.8679
Training random nDCG: 0.3575

Batch (val): 41/41
Validation nDCG: 0.7744
Validation  random nDCG: 0.3545

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.1768, NDCG: 0.8855

Training nDCG: 0.8760
Training random nDCG: 0.3775

Batch (val): 41/41
Validation nDCG: 0.7743
Validation  random nDCG: 0.3384

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.2902, NDCG: 0.9675

Training nDCG: 0.8825
Training random nDCG: 0.3505

Batch (val): 34/41

[I 2026-06-08 02:16:33,495] Trial 2 finished with value: 0.8142142558203096 and parameters: {'learning_rate': 0.00028237530727820637, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 2}. Best is trial 2 with value: 0.8142142558203096.

Batch (val): 41/41
Validation nDCG: 0.7457
Validation  random nDCG: 0.3057

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 234.31 seconds
Best hyperparameters: {'learning_rate': 0.00028237530727820637, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214

[I 2026-06-08 02:16:34,160] A new study created in memory with name: no-name-e47e6234-8542-46a7-8a42-116b9118b900

Running study for gemma semi-structured with inference=True and isco=True

    Config:
    - learning_rate = 0.004547958189016718
    - embedding_size = 128
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -2.1028, NDCG: 0.7328

Training nDCG: 0.7313
Training random nDCG: 0.3744

Batch (val): 41/41
Validation nDCG: 0.8024
Validation  random nDCG: 0.3376

--> Improvement! Best nDCG: 0.8024
Epoch: 2, Batch: 288/289, Pred Mean: 0.2418, NDCG: 0.9675

Training nDCG: 0.8077
Training random nDCG: 0.3563

Batch (val): 41/41
Validation nDCG: 0.8603
Validation  random nDCG: 0.3055

--> Improvement! Best nDCG: 0.8603
Epoch: 3, Batch: 288/289, Pred Mean: 1.4636, NDCG: 1.0000

Training nDCG: 0.8186
Training random nDCG: 0.3549

Batch (val): 41/41
Validation nDCG: 0.8854
Validation  random nDCG: 0.4014

--> Improvement! Best nDCG: 0.8854
Epoch: 4, Batch: 288/289, Pred Mean: 2.2237, NDCG: 1.0000

Training nDCG: 0.8382
Training random nDCG: 0.3567

Batch (val): 41/41
Validation nDCG: 0.8684
Validation  random nDCG: 0.3647

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.5898, NDCG: 1.0000

Training nDCG: 0.8443
Training random nDCG: 0.3411

Batch (val): 41/41
Validation nDCG: 0.8603
Validation  random nDCG: 0.3694

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 80.0177, NDCG: 0.7328

Training nDCG: 0.8478
Training random nDCG: 0.3750

Batch (val): 41/41
Validation nDCG: 0.8538
Validation  random nDCG: 0.3734

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: -1.0548, NDCG: 0.9675

Training nDCG: 0.8257
Training random nDCG: 0.3547

Batch (val): 41/41
Validation nDCG: 0.8240
Validation  random nDCG: 0.4021

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 178.78 seconds

[I 2026-06-08 02:19:32,987] Trial 0 finished with value: 0.885388813574368 and parameters: {'learning_rate': 0.004547958189016718, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.885388813574368.

    Config:
    - learning_rate = 0.002486190256475129
    - embedding_size = 32
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.0053, NDCG: 1.0000

Training nDCG: 0.7256
Training random nDCG: 0.3558

Batch (val): 41/41
Validation nDCG: 0.8430
Validation  random nDCG: 0.4050

--> Improvement! Best nDCG: 0.8430
Epoch: 2, Batch: 288/289, Pred Mean: -0.5427, NDCG: 1.0000

Training nDCG: 0.8102
Training random nDCG: 0.3637

Batch (val): 41/41
Validation nDCG: 0.8510
Validation  random nDCG: 0.3543

--> Improvement! Best nDCG: 0.8510
Epoch: 3, Batch: 288/289, Pred Mean: -0.5080, NDCG: 1.0000

Training nDCG: 0.8354
Training random nDCG: 0.3559

Batch (val): 41/41
Validation nDCG: 0.8303
Validation  random nDCG: 0.3870

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.2406, NDCG: 0.9675

Training nDCG: 0.8516
Training random nDCG: 0.3524

Batch (val): 41/41
Validation nDCG: 0.8213
Validation  random nDCG: 0.4489

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.6381, NDCG: 1.0000

Training nDCG: 0.8438
Training random nDCG: 0.3664

Batch (val): 41/41
Validation nDCG: 0.8145
Validation  random nDCG: 0.3234

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.5608, NDCG: 1.0000

Training nDCG: 0.8598
Training random nDCG: 0.3859

Batch (val): 38/41

[I 2026-06-08 02:22:01,496] Trial 1 finished with value: 0.8509988284746015 and parameters: {'learning_rate': 0.002486190256475129, 'embedding_size': 32, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.885388813574368.

Batch (val): 41/41
Validation nDCG: 0.8314
Validation  random nDCG: 0.3505

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 148.48 seconds

    Config:
    - learning_rate = 0.0005158518431311746
    - embedding_size = 128
    - pooling_method = max
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.3043, NDCG: 0.9675

Training nDCG: 0.7136
Training random nDCG: 0.3681

Batch (val): 41/41
Validation nDCG: 0.8519
Validation  random nDCG: 0.3022

--> Improvement! Best nDCG: 0.8519
Epoch: 2, Batch: 288/289, Pred Mean: 0.6172, NDCG: 0.9060

Training nDCG: 0.8067
Training random nDCG: 0.3726

Batch (val): 41/41
Validation nDCG: 0.8286
Validation  random nDCG: 0.3942

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.5846, NDCG: 0.9060

Training nDCG: 0.8216
Training random nDCG: 0.3474

Batch (val): 41/41
Validation nDCG: 0.8418
Validation  random nDCG: 0.3316

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.5300, NDCG: 0.9060

Training nDCG: 0.8106
Training random nDCG: 0.3570

Batch (val): 41/41
Validation nDCG: 0.8379
Validation  random nDCG: 0.3568

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.4974, NDCG: 0.9675

Training nDCG: 0.8172
Training random nDCG: 0.3771

Batch (val): 38/41

[I 2026-06-08 02:24:05,986] Trial 2 finished with value: 0.8519245947311906 and parameters: {'learning_rate': 0.0005158518431311746, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 8}. Best is trial 0 with value: 0.885388813574368.

Batch (val): 41/41
Validation nDCG: 0.8369
Validation  random nDCG: 0.2905

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 124.46 seconds
Best hyperparameters: {'learning_rate': 0.004547958189016718, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389

[I 2026-06-08 02:24:06,855] A new study created in memory with name: no-name-15791f06-285e-4b0f-a36d-51591887acc7

Running study for gemma unstructured with inference=True and isco=True

    Config:
    - learning_rate = 0.00032775890669816895
    - embedding_size = 8
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.2395, NDCG: 0.7039

Training nDCG: 0.4357
Training random nDCG: 0.3475

Batch (val): 41/41
Validation nDCG: 0.4517
Validation  random nDCG: 0.3408

--> Improvement! Best nDCG: 0.4517
Epoch: 2, Batch: 288/289, Pred Mean: -0.1292, NDCG: 0.3693

Training nDCG: 0.5681
Training random nDCG: 0.3702

Batch (val): 41/41
Validation nDCG: 0.6372
Validation  random nDCG: 0.3525

--> Improvement! Best nDCG: 0.6372
Epoch: 3, Batch: 288/289, Pred Mean: -0.1020, NDCG: 0.7123

Training nDCG: 0.7616
Training random nDCG: 0.3672

Batch (val): 41/41
Validation nDCG: 0.7310
Validation  random nDCG: 0.3369

--> Improvement! Best nDCG: 0.7310
Epoch: 4, Batch: 288/289, Pred Mean: -0.0733, NDCG: 0.9675

Training nDCG: 0.8019
Training random nDCG: 0.3673

Batch (val): 41/41
Validation nDCG: 0.7392
Validation  random nDCG: 0.3045

--> Improvement! Best nDCG: 0.7392
Epoch: 5, Batch: 288/289, Pred Mean: -0.0094, NDCG: 0.9675

Training nDCG: 0.8228
Training random nDCG: 0.3444

Batch (val): 41/41
Validation nDCG: 0.7610
Validation  random nDCG: 0.3943

--> Improvement! Best nDCG: 0.7610
Epoch: 6, Batch: 288/289, Pred Mean: 0.0551, NDCG: 1.0000

Training nDCG: 0.8445
Training random nDCG: 0.3708

Batch (val): 41/41
Validation nDCG: 0.7643
Validation  random nDCG: 0.3234

--> Improvement! Best nDCG: 0.7643
Epoch: 7, Batch: 288/289, Pred Mean: 0.1396, NDCG: 1.0000

Training nDCG: 0.8534
Training random nDCG: 0.3756

Batch (val): 41/41
Validation nDCG: 0.7677
Validation  random nDCG: 0.2885

--> Improvement! Best nDCG: 0.7677
Epoch: 8, Batch: 288/289, Pred Mean: 0.2662, NDCG: 1.0000

Training nDCG: 0.8666
Training random nDCG: 0.3776

Batch (val): 41/41
Validation nDCG: 0.7663
Validation  random nDCG: 0.3089

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.3246, NDCG: 1.0000

Training nDCG: 0.8802
Training random nDCG: 0.3612

Batch (val): 41/41
Validation nDCG: 0.7586
Validation  random nDCG: 0.3441

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 0.3744, NDCG: 1.0000

Training nDCG: 0.8871
Training random nDCG: 0.3531

Batch (val): 41/41
Validation nDCG: 0.7534
Validation  random nDCG: 0.3795

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.4450, NDCG: 1.0000

Training nDCG: 0.8926
Training random nDCG: 0.3471

Batch (val): 37/41

[I 2026-06-08 02:29:12,585] Trial 0 finished with value: 0.7677494815003458 and parameters: {'learning_rate': 0.00032775890669816895, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.7677494815003458.

Batch (val): 41/41
Validation nDCG: 0.7531
Validation  random nDCG: 0.3157

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 305.70 seconds

    Config:
    - learning_rate = 0.007878673358046623
    - embedding_size = 8
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.9139, NDCG: 0.9060

Training nDCG: 0.7444
Training random nDCG: 0.3665

Batch (val): 41/41
Validation nDCG: 0.8372
Validation  random nDCG: 0.3550

--> Improvement! Best nDCG: 0.8372
Epoch: 2, Batch: 288/289, Pred Mean: 1.3143, NDCG: 0.6797

Training nDCG: 0.8082
Training random nDCG: 0.3836

Batch (val): 41/41
Validation nDCG: 0.8026
Validation  random nDCG: 0.4145

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.3452, NDCG: 0.9060

Training nDCG: 0.8141
Training random nDCG: 0.3706

Batch (val): 41/41
Validation nDCG: 0.8242
Validation  random nDCG: 0.4014

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.5062, NDCG: 0.9469

Training nDCG: 0.8265
Training random nDCG: 0.3788

Batch (val): 41/41
Validation nDCG: 0.8416
Validation  random nDCG: 0.3167

--> Improvement! Best nDCG: 0.8416
Epoch: 5, Batch: 288/289, Pred Mean: 0.7987, NDCG: 1.0000

Training nDCG: 0.8364
Training random nDCG: 0.3507

Batch (val): 41/41
Validation nDCG: 0.8000
Validation  random nDCG: 0.3535

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.8509, NDCG: 0.9675

Training nDCG: 0.8476
Training random nDCG: 0.3592

Batch (val): 41/41
Validation nDCG: 0.8023
Validation  random nDCG: 0.3757

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.4313, NDCG: 0.9675

Training nDCG: 0.8494
Training random nDCG: 0.3784

Batch (val): 41/41
Validation nDCG: 0.8150
Validation  random nDCG: 0.4080

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.3904, NDCG: 0.9675

Training nDCG: 0.8590
Training random nDCG: 0.3583

Batch (val): 40/41

[I 2026-06-08 02:33:07,303] Trial 1 finished with value: 0.8416473490362315 and parameters: {'learning_rate': 0.007878673358046623, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 4}. Best is trial 1 with value: 0.8416473490362315.

Batch (val): 41/41
Validation nDCG: 0.8016
Validation  random nDCG: 0.3896

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 234.68 seconds

    Config:
    - learning_rate = 0.00716203487662184
    - embedding_size = 32
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.9550, NDCG: 0.6797

Training nDCG: 0.7393
Training random nDCG: 0.3876

Batch (val): 41/41
Validation nDCG: 0.7987
Validation  random nDCG: 0.3925

--> Improvement! Best nDCG: 0.7987
Epoch: 2, Batch: 288/289, Pred Mean: 0.4830, NDCG: 0.6183

Training nDCG: 0.8110
Training random nDCG: 0.3941

Batch (val): 41/41
Validation nDCG: 0.8320
Validation  random nDCG: 0.3811

--> Improvement! Best nDCG: 0.8320
Epoch: 3, Batch: 288/289, Pred Mean: 0.5809, NDCG: 0.8855

Training nDCG: 0.8211
Training random nDCG: 0.3650

Batch (val): 41/41
Validation nDCG: 0.8179
Validation  random nDCG: 0.3727

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.2963, NDCG: 0.8855

Training nDCG: 0.8224
Training random nDCG: 0.3779

Batch (val): 41/41
Validation nDCG: 0.8096
Validation  random nDCG: 0.3923

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.8331, NDCG: 0.7328

Training nDCG: 0.8324
Training random nDCG: 0.3672

Batch (val): 41/41
Validation nDCG: 0.7771
Validation  random nDCG: 0.4037

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.1516, NDCG: 0.6448

Training nDCG: 0.8339
Training random nDCG: 0.3573

Batch (val): 41/41

[I 2026-06-08 02:35:51,096] Trial 2 finished with value: 0.8319559352215123 and parameters: {'learning_rate': 0.00716203487662184, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 8}. Best is trial 1 with value: 0.8416473490362315.

Validation nDCG: 0.7831
Validation  random nDCG: 0.3349

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 163.76 seconds
Best hyperparameters: {'learning_rate': 0.007878673358046623, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647

[I 2026-06-08 02:35:51,883] A new study created in memory with name: no-name-56e97bde-44e3-4876-8d99-7a8fa3c2d776

Running study for llama structured with inference=True and isco=True

    Config:
    - learning_rate = 0.00013052654059543493
    - embedding_size = 16
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -0.0381, NDCG: 0.9469

Training nDCG: 0.4948
Training random nDCG: 0.3750

Batch (val): 41/41
Validation nDCG: 0.6157
Validation  random nDCG: 0.3746

--> Improvement! Best nDCG: 0.6157
Epoch: 2, Batch: 288/289, Pred Mean: 0.0302, NDCG: 0.6448

Training nDCG: 0.6825
Training random nDCG: 0.3722

Batch (val): 41/41
Validation nDCG: 0.7816
Validation  random nDCG: 0.3544

--> Improvement! Best nDCG: 0.7816
Epoch: 3, Batch: 288/289, Pred Mean: 0.0977, NDCG: 0.6448

Training nDCG: 0.7513
Training random nDCG: 0.4011

Batch (val): 41/41
Validation nDCG: 0.7746
Validation  random nDCG: 0.3361

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1737, NDCG: 0.5833

Training nDCG: 0.7709
Training random nDCG: 0.3599

Batch (val): 41/41
Validation nDCG: 0.7736
Validation  random nDCG: 0.3537

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.2391, NDCG: 0.5833

Training nDCG: 0.7748
Training random nDCG: 0.3621

Batch (val): 41/41
Validation nDCG: 0.7858
Validation  random nDCG: 0.3728

--> Improvement! Best nDCG: 0.7858
Epoch: 6, Batch: 288/289, Pred Mean: 0.2699, NDCG: 0.5833

Training nDCG: 0.7818
Training random nDCG: 0.3740

Batch (val): 41/41
Validation nDCG: 0.7734
Validation  random nDCG: 0.3942

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.2892, NDCG: 0.5833

Training nDCG: 0.7957
Training random nDCG: 0.3748

Batch (val): 41/41
Validation nDCG: 0.7715
Validation  random nDCG: 0.4010

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.3223, NDCG: 0.6448

Training nDCG: 0.8063
Training random nDCG: 0.3644

Batch (val): 41/41
Validation nDCG: 0.7494
Validation  random nDCG: 0.3453

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.3645, NDCG: 0.6448

Training nDCG: 0.8215
Training random nDCG: 0.3677

Batch (val): 40/41

[I 2026-06-08 02:40:10,747] Trial 0 finished with value: 0.7857703239360718 and parameters: {'learning_rate': 0.00013052654059543493, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}. Best is trial 0 with value: 0.7857703239360718.

Batch (val): 41/41
Validation nDCG: 0.7303
Validation  random nDCG: 0.3846

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 258.83 seconds

    Config:
    - learning_rate = 0.00012710183874886232
    - embedding_size = 8
    - pooling_method = max
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -0.1881, NDCG: 0.1413

Training nDCG: 0.4152
Training random nDCG: 0.3906

Batch (val): 41/41
Validation nDCG: 0.5718
Validation  random nDCG: 0.3442

--> Improvement! Best nDCG: 0.5718
Epoch: 2, Batch: 288/289, Pred Mean: 0.1682, NDCG: 0.6508

Training nDCG: 0.6071
Training random nDCG: 0.3744

Batch (val): 41/41
Validation nDCG: 0.5465
Validation  random nDCG: 0.3524

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.1097, NDCG: 0.2961

Training nDCG: 0.4637
Training random nDCG: 0.3799

Batch (val): 41/41
Validation nDCG: 0.4116
Validation  random nDCG: 0.4248

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1515, NDCG: 0.5780

Training nDCG: 0.4179
Training random nDCG: 0.3832

Batch (val): 41/41
Validation nDCG: 0.4887
Validation  random nDCG: 0.3839

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.0752, NDCG: 0.6039

Training nDCG: 0.6035
Training random nDCG: 0.3510

Batch (val): 41/41
Validation nDCG: 0.6575
Validation  random nDCG: 0.4252

--> Improvement! Best nDCG: 0.6575
Epoch: 6, Batch: 288/289, Pred Mean: 0.0177, NDCG: 0.6039

Training nDCG: 0.7177
Training random nDCG: 0.4119

Batch (val): 41/41
Validation nDCG: 0.7408
Validation  random nDCG: 0.4147

--> Improvement! Best nDCG: 0.7408
Epoch: 7, Batch: 288/289, Pred Mean: 0.5762, NDCG: 0.6039

Training nDCG: 0.7513
Training random nDCG: 0.3519

Batch (val): 41/41
Validation nDCG: 0.7593
Validation  random nDCG: 0.4004

--> Improvement! Best nDCG: 0.7593
Epoch: 8, Batch: 288/289, Pred Mean: 0.0222, NDCG: 0.7123

Training nDCG: 0.7767
Training random nDCG: 0.3831

Batch (val): 41/41
Validation nDCG: 0.7541
Validation  random nDCG: 0.4326

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.0339, NDCG: 0.7123

Training nDCG: 0.7902
Training random nDCG: 0.3573

Batch (val): 41/41
Validation nDCG: 0.7521
Validation  random nDCG: 0.3680

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: -0.0005, NDCG: 0.7123

Training nDCG: 0.8003
Training random nDCG: 0.3764

Batch (val): 41/41
Validation nDCG: 0.7337
Validation  random nDCG: 0.3806

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: -0.0021, NDCG: 0.6183

Training nDCG: 0.8143
Training random nDCG: 0.3707

Batch (val): 37/41

[I 2026-06-08 02:45:09,055] Trial 1 finished with value: 0.7593309071092692 and parameters: {'learning_rate': 0.00012710183874886232, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 8}. Best is trial 0 with value: 0.7857703239360718.

Batch (val): 41/41
Validation nDCG: 0.7260
Validation  random nDCG: 0.4031

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 298.28 seconds

    Config:
    - learning_rate = 0.009736219789300234
    - embedding_size = 16
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 1.3116, NDCG: 0.8711

Training nDCG: 0.7881
Training random nDCG: 0.3965

Batch (val): 41/41
Validation nDCG: 0.7828
Validation  random nDCG: 0.3847

--> Improvement! Best nDCG: 0.7828
Epoch: 2, Batch: 288/289, Pred Mean: 1.3310, NDCG: 0.8711

Training nDCG: 0.8103
Training random nDCG: 0.3761

Batch (val): 41/41
Validation nDCG: 0.8192
Validation  random nDCG: 0.4121

--> Improvement! Best nDCG: 0.8192
Epoch: 3, Batch: 288/289, Pred Mean: 1.1868, NDCG: 0.6979

Training nDCG: 0.8198
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.8080
Validation  random nDCG: 0.3835

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.9699, NDCG: 0.6653

Training nDCG: 0.8391
Training random nDCG: 0.3550

Batch (val): 41/41
Validation nDCG: 0.8170
Validation  random nDCG: 0.3963

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 2.1648, NDCG: 0.6979

Training nDCG: 0.8454
Training random nDCG: 0.3609

Batch (val): 41/41
Validation nDCG: 0.8235
Validation  random nDCG: 0.3604

--> Improvement! Best nDCG: 0.8235
Epoch: 6, Batch: 288/289, Pred Mean: 1.6349, NDCG: 0.8385

Training nDCG: 0.8596
Training random nDCG: 0.3624

Batch (val): 41/41
Validation nDCG: 0.8589
Validation  random nDCG: 0.4355

--> Improvement! Best nDCG: 0.8589
Epoch: 7, Batch: 288/289, Pred Mean: 1.9367, NDCG: 0.6653

Training nDCG: 0.8627
Training random nDCG: 0.3501

Batch (val): 41/41
Validation nDCG: 0.8080
Validation  random nDCG: 0.3863

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.6117, NDCG: 0.9325

Training nDCG: 0.8587
Training random nDCG: 0.3765

Batch (val): 41/41
Validation nDCG: 0.8100
Validation  random nDCG: 0.3875

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.9462, NDCG: 0.8711

Training nDCG: 0.8754
Training random nDCG: 0.3550

Batch (val): 41/41
Validation nDCG: 0.8457
Validation  random nDCG: 0.3367

--> No improvement. Patience: 3/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.1497, NDCG: 0.8855

Training nDCG: 0.8668
Training random nDCG: 0.3796

Batch (val): 40/41

[I 2026-06-08 02:49:33,729] Trial 2 finished with value: 0.8588679971140017 and parameters: {'learning_rate': 0.009736219789300234, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}. Best is trial 2 with value: 0.8588679971140017.

Batch (val): 41/41
Validation nDCG: 0.8299
Validation  random nDCG: 0.3685

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 10
Training for 15 epochs took 264.63 seconds
Best hyperparameters: {'learning_rate': 0.009736219789300234, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868

[I 2026-06-08 02:49:34,554] A new study created in memory with name: no-name-32068e43-71cc-46e0-a3a8-84d56b3967e0

Running study for llama semi-structured with inference=True and isco=True

    Config:
    - learning_rate = 0.0007166049628460309
    - embedding_size = 64
    - pooling_method = max
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.3863, NDCG: 0.8772

Training nDCG: 0.6675
Training random nDCG: 0.3764

Batch (val): 41/41
Validation nDCG: 0.7698
Validation  random nDCG: 0.3475

--> Improvement! Best nDCG: 0.7698
Epoch: 2, Batch: 288/289, Pred Mean: 0.6388, NDCG: 0.6509

Training nDCG: 0.7922
Training random nDCG: 0.3470

Batch (val): 41/41
Validation nDCG: 0.7719
Validation  random nDCG: 0.3250

--> Improvement! Best nDCG: 0.7719
Epoch: 3, Batch: 288/289, Pred Mean: 0.7975, NDCG: 0.9197

Training nDCG: 0.8156
Training random nDCG: 0.3633

Batch (val): 41/41
Validation nDCG: 0.7673
Validation  random nDCG: 0.3566

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.7907, NDCG: 0.8772

Training nDCG: 0.8321
Training random nDCG: 0.3734

Batch (val): 41/41
Validation nDCG: 0.7966
Validation  random nDCG: 0.4750

--> Improvement! Best nDCG: 0.7966
Epoch: 5, Batch: 288/289, Pred Mean: 1.0907, NDCG: 0.8772

Training nDCG: 0.8424
Training random nDCG: 0.3836

Batch (val): 41/41
Validation nDCG: 0.8291
Validation  random nDCG: 0.3539

--> Improvement! Best nDCG: 0.8291
Epoch: 6, Batch: 288/289, Pred Mean: 1.1362, NDCG: 0.9197

Training nDCG: 0.8665
Training random nDCG: 0.3657

Batch (val): 41/41
Validation nDCG: 0.8311
Validation  random nDCG: 0.3322

--> Improvement! Best nDCG: 0.8311
Epoch: 7, Batch: 288/289, Pred Mean: 1.1266, NDCG: 0.9197

Training nDCG: 0.8368
Training random nDCG: 0.3629

Batch (val): 41/41
Validation nDCG: 0.7967
Validation  random nDCG: 0.3929

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.2201, NDCG: 0.8772

Training nDCG: 0.8639
Training random nDCG: 0.3701

Batch (val): 41/41
Validation nDCG: 0.8342
Validation  random nDCG: 0.3696

--> Improvement! Best nDCG: 0.8342
Epoch: 9, Batch: 288/289, Pred Mean: 1.3670, NDCG: 0.9197

Training nDCG: 0.8763
Training random nDCG: 0.3426

Batch (val): 41/41
Validation nDCG: 0.8161
Validation  random nDCG: 0.3644

--> No improvement. Patience: 1/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.5527, NDCG: 1.0000

Training nDCG: 0.8863
Training random nDCG: 0.3676

Batch (val): 41/41
Validation nDCG: 0.8086
Validation  random nDCG: 0.3152

--> No improvement. Patience: 2/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.6811, NDCG: 1.0000

Training nDCG: 0.9024
Training random nDCG: 0.3712

Batch (val): 41/41
Validation nDCG: 0.7784
Validation  random nDCG: 0.3559

--> No improvement. Patience: 3/4
Epoch: 12, Batch: 288/289, Pred Mean: 2.1009, NDCG: 1.0000

Training nDCG: 0.9144
Training random nDCG: 0.3708

Batch (val): 38/41

[I 2026-06-08 02:55:03,972] Trial 0 finished with value: 0.8342131369218606 and parameters: {'learning_rate': 0.0007166049628460309, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 8}. Best is trial 0 with value: 0.8342131369218606.

Batch (val): 41/41
Validation nDCG: 0.7653
Validation  random nDCG: 0.3779

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 12
Training for 15 epochs took 329.37 seconds

    Config:
    - learning_rate = 0.0038140432606948564
    - embedding_size = 8
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.8360, NDCG: 0.8772

Training nDCG: 0.7046
Training random nDCG: 0.3585

Batch (val): 41/41
Validation nDCG: 0.7526
Validation  random nDCG: 0.3626

--> Improvement! Best nDCG: 0.7526
Epoch: 2, Batch: 288/289, Pred Mean: 1.3859, NDCG: 0.5706

Training nDCG: 0.8079
Training random nDCG: 0.3741

Batch (val): 41/41
Validation nDCG: 0.7925
Validation  random nDCG: 0.3230

--> Improvement! Best nDCG: 0.7925
Epoch: 3, Batch: 288/289, Pred Mean: 1.1244, NDCG: 0.5706

Training nDCG: 0.8139
Training random nDCG: 0.3703

Batch (val): 41/41
Validation nDCG: 0.7910
Validation  random nDCG: 0.3412

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.0881, NDCG: 0.6509

Training nDCG: 0.8290
Training random nDCG: 0.3850

Batch (val): 41/41
Validation nDCG: 0.8063
Validation  random nDCG: 0.3902

--> Improvement! Best nDCG: 0.8063
Epoch: 5, Batch: 288/289, Pred Mean: 1.3673, NDCG: 0.6509

Training nDCG: 0.8382
Training random nDCG: 0.3583

Batch (val): 41/41
Validation nDCG: 0.7877
Validation  random nDCG: 0.4163

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.1694, NDCG: 0.6509

Training nDCG: 0.8270
Training random nDCG: 0.3542

Batch (val): 41/41
Validation nDCG: 0.7972
Validation  random nDCG: 0.4077

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.2360, NDCG: 0.6241

Training nDCG: 0.8476
Training random nDCG: 0.3575

Batch (val): 41/41
Validation nDCG: 0.7774
Validation  random nDCG: 0.3253

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.1079, NDCG: 0.8772

Training nDCG: 0.8428
Training random nDCG: 0.3711

Batch (val): 38/41

[I 2026-06-08 02:58:40,650] Trial 1 finished with value: 0.8063477518124609 and parameters: {'learning_rate': 0.0038140432606948564, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.8342131369218606.

Batch (val): 41/41
Validation nDCG: 0.8049
Validation  random nDCG: 0.3866

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 216.66 seconds

    Config:
    - learning_rate = 0.005018882042494451
    - embedding_size = 64
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.0921, NDCG: 0.8772

Training nDCG: 0.7449
Training random nDCG: 0.3531

Batch (val): 41/41
Validation nDCG: 0.8134
Validation  random nDCG: 0.3697

--> Improvement! Best nDCG: 0.8134
Epoch: 2, Batch: 288/289, Pred Mean: 0.8852, NDCG: 0.5706

Training nDCG: 0.7934
Training random nDCG: 0.3814

Batch (val): 41/41
Validation nDCG: 0.8407
Validation  random nDCG: 0.3912

--> Improvement! Best nDCG: 0.8407
Epoch: 3, Batch: 288/289, Pred Mean: 1.6826, NDCG: 0.5706

Training nDCG: 0.8058
Training random nDCG: 0.3588

Batch (val): 41/41
Validation nDCG: 0.8044
Validation  random nDCG: 0.3674

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 2.9651, NDCG: 0.5706

Training nDCG: 0.8024
Training random nDCG: 0.3787

Batch (val): 41/41
Validation nDCG: 0.8341
Validation  random nDCG: 0.3378

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 3.2004, NDCG: 0.6509

Training nDCG: 0.8168
Training random nDCG: 0.3593

Batch (val): 41/41
Validation nDCG: 0.8311
Validation  random nDCG: 0.3059

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 2.8404, NDCG: 0.6934

Training nDCG: 0.8241
Training random nDCG: 0.3619

Batch (val): 40/41

[I 2026-06-08 03:01:24,954] Trial 2 finished with value: 0.8406828746346533 and parameters: {'learning_rate': 0.005018882042494451, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 2}. Best is trial 2 with value: 0.8406828746346533.

Batch (val): 41/41
Validation nDCG: 0.8188
Validation  random nDCG: 0.3481

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 164.27 seconds
Best hyperparameters: {'learning_rate': 0.005018882042494451, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683

[I 2026-06-08 03:01:25,832] A new study created in memory with name: no-name-eaf6a281-782c-497c-9741-b9e51f8c0ef8

Running study for llama unstructured with inference=True and isco=True

    Config:
    - learning_rate = 0.00011374711905637005
    - embedding_size = 128
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.2611, NDCG: 1.0000

Training nDCG: 0.5578
Training random nDCG: 0.4040

Batch (val): 41/41
Validation nDCG: 0.6192
Validation  random nDCG: 0.3881

--> Improvement! Best nDCG: 0.6192
Epoch: 2, Batch: 288/289, Pred Mean: -0.1490, NDCG: 1.0000

Training nDCG: 0.7405
Training random nDCG: 0.3962

Batch (val): 41/41
Validation nDCG: 0.6478
Validation  random nDCG: 0.3672

--> Improvement! Best nDCG: 0.6478
Epoch: 3, Batch: 288/289, Pred Mean: -0.1545, NDCG: 1.0000

Training nDCG: 0.7805
Training random nDCG: 0.4050

Batch (val): 41/41
Validation nDCG: 0.6983
Validation  random nDCG: 0.3669

--> Improvement! Best nDCG: 0.6983
Epoch: 4, Batch: 288/289, Pred Mean: 0.1668, NDCG: 1.0000

Training nDCG: 0.8099
Training random nDCG: 0.3904

Batch (val): 41/41
Validation nDCG: 0.6731
Validation  random nDCG: 0.4008

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.0894, NDCG: 0.9675

Training nDCG: 0.8308
Training random nDCG: 0.3986

Batch (val): 41/41
Validation nDCG: 0.6674
Validation  random nDCG: 0.3386

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.3319, NDCG: 1.0000

Training nDCG: 0.8391
Training random nDCG: 0.3811

Batch (val): 41/41
Validation nDCG: 0.6713
Validation  random nDCG: 0.3072

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.1237, NDCG: 1.0000

Training nDCG: 0.8507
Training random nDCG: 0.3861

Batch (val): 41/41

[I 2026-06-08 03:04:20,852] Trial 0 finished with value: 0.6982628033091818 and parameters: {'learning_rate': 0.00011374711905637005, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.6982628033091818.

Validation nDCG: 0.6680
Validation  random nDCG: 0.3018

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 174.98 seconds

    Config:
    - learning_rate = 0.00013042552292743905
    - embedding_size = 64
    - pooling_method = max
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.0304, NDCG: 0.9469

Training nDCG: 0.5507
Training random nDCG: 0.4171

Batch (val): 41/41
Validation nDCG: 0.6368
Validation  random nDCG: 0.3640

--> Improvement! Best nDCG: 0.6368
Epoch: 2, Batch: 288/289, Pred Mean: -0.0545, NDCG: 1.0000

Training nDCG: 0.7238
Training random nDCG: 0.3943

Batch (val): 41/41
Validation nDCG: 0.6585
Validation  random nDCG: 0.3706

--> Improvement! Best nDCG: 0.6585
Epoch: 3, Batch: 288/289, Pred Mean: 0.0310, NDCG: 1.0000

Training nDCG: 0.7650
Training random nDCG: 0.3871

Batch (val): 41/41
Validation nDCG: 0.6590
Validation  random nDCG: 0.4039

--> Improvement! Best nDCG: 0.6590
Epoch: 4, Batch: 288/289, Pred Mean: -0.0290, NDCG: 0.9060

Training nDCG: 0.7911
Training random nDCG: 0.3932

Batch (val): 41/41
Validation nDCG: 0.6416
Validation  random nDCG: 0.3555

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.2220, NDCG: 0.7328

Training nDCG: 0.7978
Training random nDCG: 0.3902

Batch (val): 41/41
Validation nDCG: 0.6343
Validation  random nDCG: 0.3394

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.0864, NDCG: 0.6183

Training nDCG: 0.8182
Training random nDCG: 0.4024

Batch (val): 41/41
Validation nDCG: 0.6397
Validation  random nDCG: 0.3974

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.4893, NDCG: 0.7123

Training nDCG: 0.8269
Training random nDCG: 0.4080

Batch (val): 38/41

[I 2026-06-08 03:07:21,937] Trial 1 finished with value: 0.6590479198703553 and parameters: {'learning_rate': 0.00013042552292743905, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 8}. Best is trial 0 with value: 0.6982628033091818.

Batch (val): 41/41
Validation nDCG: 0.6453
Validation  random nDCG: 0.3893

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 181.05 seconds

    Config:
    - learning_rate = 0.0001074326824465145
    - embedding_size = 8
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.0232, NDCG: 0.1480

Training nDCG: 0.3582
Training random nDCG: 0.3798

Batch (val): 41/41
Validation nDCG: 0.3317
Validation  random nDCG: 0.3289

--> Improvement! Best nDCG: 0.3317
Epoch: 2, Batch: 288/289, Pred Mean: -1.1095, NDCG: 0.1672

Training nDCG: 0.4010
Training random nDCG: 0.3985

Batch (val): 41/41
Validation nDCG: 0.3421
Validation  random nDCG: 0.3660

--> Improvement! Best nDCG: 0.3421
Epoch: 3, Batch: 288/289, Pred Mean: -0.1070, NDCG: 0.0000

Training nDCG: 0.4250
Training random nDCG: 0.3861

Batch (val): 41/41
Validation nDCG: 0.4079
Validation  random nDCG: 0.3969

--> Improvement! Best nDCG: 0.4079
Epoch: 4, Batch: 288/289, Pred Mean: -0.1541, NDCG: 0.5307

Training nDCG: 0.4588
Training random nDCG: 0.3943

Batch (val): 41/41
Validation nDCG: 0.4914
Validation  random nDCG: 0.3498

--> Improvement! Best nDCG: 0.4914
Epoch: 5, Batch: 288/289, Pred Mean: -0.1081, NDCG: 0.6720

Training nDCG: 0.4942
Training random nDCG: 0.4144

Batch (val): 41/41
Validation nDCG: 0.4911
Validation  random nDCG: 0.3591

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.1227, NDCG: 0.9675

Training nDCG: 0.5247
Training random nDCG: 0.3881

Batch (val): 41/41
Validation nDCG: 0.5361
Validation  random nDCG: 0.3757

--> Improvement! Best nDCG: 0.5361
Epoch: 7, Batch: 288/289, Pred Mean: -0.0905, NDCG: 0.9675

Training nDCG: 0.5819
Training random nDCG: 0.3599

Batch (val): 41/41
Validation nDCG: 0.5230
Validation  random nDCG: 0.3717

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: -0.0750, NDCG: 1.0000

Training nDCG: 0.5811
Training random nDCG: 0.3971

Batch (val): 41/41
Validation nDCG: 0.5516
Validation  random nDCG: 0.3566

--> Improvement! Best nDCG: 0.5516
Epoch: 9, Batch: 288/289, Pred Mean: -0.1032, NDCG: 1.0000

Training nDCG: 0.6278
Training random nDCG: 0.3895

Batch (val): 41/41
Validation nDCG: 0.5736
Validation  random nDCG: 0.3930

--> Improvement! Best nDCG: 0.5736
Epoch: 10, Batch: 288/289, Pred Mean: -0.0977, NDCG: 1.0000

Training nDCG: 0.6511
Training random nDCG: 0.3933

Batch (val): 41/41
Validation nDCG: 0.5892
Validation  random nDCG: 0.3236

--> Improvement! Best nDCG: 0.5892
Epoch: 11, Batch: 288/289, Pred Mean: -0.0999, NDCG: 1.0000

Training nDCG: 0.6820
Training random nDCG: 0.4061

Batch (val): 41/41
Validation nDCG: 0.5692
Validation  random nDCG: 0.3216

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: -0.1115, NDCG: 1.0000

Training nDCG: 0.6939
Training random nDCG: 0.4016

Batch (val): 41/41
Validation nDCG: 0.5973
Validation  random nDCG: 0.3582

--> Improvement! Best nDCG: 0.5973
Epoch: 13, Batch: 288/289, Pred Mean: -0.1175, NDCG: 0.9675

Training nDCG: 0.7080
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.5798
Validation  random nDCG: 0.3225

--> No improvement. Patience: 1/4
Epoch: 14, Batch: 288/289, Pred Mean: -0.1178, NDCG: 0.9675

Training nDCG: 0.7286
Training random nDCG: 0.4020

Batch (val): 41/41
Validation nDCG: 0.5812
Validation  random nDCG: 0.3401

--> No improvement. Patience: 2/4
Epoch: 15, Batch: 288/289, Pred Mean: -0.1245, NDCG: 0.9675

Training nDCG: 0.7442
Training random nDCG: 0.3977

Batch (val): 39/41

[I 2026-06-08 03:13:45,347] Trial 2 finished with value: 0.5972712427546997 and parameters: {'learning_rate': 0.0001074326824465145, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.6982628033091818.

Batch (val): 41/41
Validation nDCG: 0.5839
Validation  random nDCG: 0.3923

--> No improvement. Patience: 3/4
Training for 15 epochs took 383.38 seconds
Best hyperparameters: {'learning_rate': 0.00011374711905637005, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263

[I 2026-06-08 03:13:46,059] A new study created in memory with name: no-name-80a0889b-17d7-4370-b7a7-b7f12f57f71b

Running study for qwen structured with inference=True and isco=False

    Config:
    - learning_rate = 0.0039035309714451068
    - embedding_size = 128
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -0.8130, NDCG: 0.9060

Training nDCG: 0.7355
Training random nDCG: 0.3834

Batch (val): 41/41
Validation nDCG: 0.7984
Validation  random nDCG: 0.3440

--> Improvement! Best nDCG: 0.7984
Epoch: 2, Batch: 288/289, Pred Mean: 1.4807, NDCG: 1.0000

Training nDCG: 0.7823
Training random nDCG: 0.3770

Batch (val): 41/41
Validation nDCG: 0.7971
Validation  random nDCG: 0.3436

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.3940, NDCG: 1.0000

Training nDCG: 0.7972
Training random nDCG: 0.3683

Batch (val): 41/41
Validation nDCG: 0.7946
Validation  random nDCG: 0.3288

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.8012, NDCG: 0.9469

Training nDCG: 0.8114
Training random nDCG: 0.3701

Batch (val): 41/41
Validation nDCG: 0.8081
Validation  random nDCG: 0.4109

--> Improvement! Best nDCG: 0.8081
Epoch: 5, Batch: 288/289, Pred Mean: 1.0953, NDCG: 0.9675

Training nDCG: 0.8039
Training random nDCG: 0.3586

Batch (val): 41/41
Validation nDCG: 0.8043
Validation  random nDCG: 0.3813

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.5219, NDCG: 0.9469

Training nDCG: 0.8159
Training random nDCG: 0.3608

Batch (val): 41/41
Validation nDCG: 0.8125
Validation  random nDCG: 0.3071

--> Improvement! Best nDCG: 0.8125
Epoch: 7, Batch: 288/289, Pred Mean: -0.4823, NDCG: 0.9469

Training nDCG: 0.8226
Training random nDCG: 0.3742

Batch (val): 41/41
Validation nDCG: 0.8147
Validation  random nDCG: 0.4085

--> Improvement! Best nDCG: 0.8147
Epoch: 8, Batch: 288/289, Pred Mean: 1.8945, NDCG: 0.9675

Training nDCG: 0.8179
Training random nDCG: 0.3643

Batch (val): 41/41
Validation nDCG: 0.8013
Validation  random nDCG: 0.3494

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.1413, NDCG: 0.9469

Training nDCG: 0.8312
Training random nDCG: 0.3764

Batch (val): 41/41
Validation nDCG: 0.8391
Validation  random nDCG: 0.3672

--> Improvement! Best nDCG: 0.8391
Epoch: 10, Batch: 288/289, Pred Mean: 2.8843, NDCG: 0.9675

Training nDCG: 0.8423
Training random nDCG: 0.3649

Batch (val): 41/41
Validation nDCG: 0.8110
Validation  random nDCG: 0.3499

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.8235, NDCG: 0.8855

Training nDCG: 0.8443
Training random nDCG: 0.3607

Batch (val): 41/41
Validation nDCG: 0.8493
Validation  random nDCG: 0.4237

--> Improvement! Best nDCG: 0.8493
Epoch: 12, Batch: 288/289, Pred Mean: 0.9221, NDCG: 1.0000

Training nDCG: 0.8541
Training random nDCG: 0.3964

Batch (val): 41/41
Validation nDCG: 0.8530
Validation  random nDCG: 0.2971

--> Improvement! Best nDCG: 0.8530
Epoch: 13, Batch: 288/289, Pred Mean: 2.2028, NDCG: 0.9060

Training nDCG: 0.8580
Training random nDCG: 0.3652

Batch (val): 41/41
Validation nDCG: 0.8450
Validation  random nDCG: 0.3510

--> No improvement. Patience: 1/4
Epoch: 14, Batch: 288/289, Pred Mean: 2.4782, NDCG: 1.0000

Training nDCG: 0.8628
Training random nDCG: 0.3843

Batch (val): 41/41
Validation nDCG: 0.8244
Validation  random nDCG: 0.3791

--> No improvement. Patience: 2/4
Epoch: 15, Batch: 288/289, Pred Mean: 3.8358, NDCG: 1.0000

Training nDCG: 0.8712
Training random nDCG: 0.3614

Batch (val): 36/41

[I 2026-06-08 03:19:51,194] Trial 0 finished with value: 0.8530092800505186 and parameters: {'learning_rate': 0.0039035309714451068, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 8}. Best is trial 0 with value: 0.8530092800505186.

Batch (val): 41/41
Validation nDCG: 0.8491
Validation  random nDCG: 0.3551

--> No improvement. Patience: 3/4
Training for 15 epochs took 365.09 seconds

    Config:
    - learning_rate = 0.0013480038065713505
    - embedding_size = 32
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.1177, NDCG: 0.7328

Training nDCG: 0.6186
Training random nDCG: 0.3631

Batch (val): 41/41
Validation nDCG: 0.8021
Validation  random nDCG: 0.3670

--> Improvement! Best nDCG: 0.8021
Epoch: 2, Batch: 288/289, Pred Mean: 1.0385, NDCG: 0.7123

Training nDCG: 0.7967
Training random nDCG: 0.3501

Batch (val): 41/41
Validation nDCG: 0.7970
Validation  random nDCG: 0.3519

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.3812, NDCG: 0.7123

Training nDCG: 0.8166
Training random nDCG: 0.3559

Batch (val): 41/41
Validation nDCG: 0.8063
Validation  random nDCG: 0.3734

--> Improvement! Best nDCG: 0.8063
Epoch: 4, Batch: 288/289, Pred Mean: 1.6345, NDCG: 0.7328

Training nDCG: 0.8237
Training random nDCG: 0.3754

Batch (val): 41/41
Validation nDCG: 0.8316
Validation  random nDCG: 0.3790

--> Improvement! Best nDCG: 0.8316
Epoch: 5, Batch: 288/289, Pred Mean: 1.4951, NDCG: 0.8855

Training nDCG: 0.8365
Training random nDCG: 0.3623

Batch (val): 41/41
Validation nDCG: 0.8058
Validation  random nDCG: 0.3844

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 2.0163, NDCG: 0.9469

Training nDCG: 0.8452
Training random nDCG: 0.3785

Batch (val): 41/41
Validation nDCG: 0.7979
Validation  random nDCG: 0.3205

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 3.3009, NDCG: 0.6039

Training nDCG: 0.8493
Training random nDCG: 0.3742

Batch (val): 41/41
Validation nDCG: 0.8073
Validation  random nDCG: 0.3558

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.9296, NDCG: 0.9469

Training nDCG: 0.8470
Training random nDCG: 0.3700

Batch (val): 40/41

[I 2026-06-08 03:23:30,511] Trial 1 finished with value: 0.8316176441476238 and parameters: {'learning_rate': 0.0013480038065713505, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.8530092800505186.

Batch (val): 41/41
Validation nDCG: 0.8035
Validation  random nDCG: 0.3020

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 219.29 seconds

    Config:
    - learning_rate = 0.0001283592906365915
    - embedding_size = 64
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.2793, NDCG: 0.7654

Training nDCG: 0.5347
Training random nDCG: 0.3565

Batch (val): 41/41
Validation nDCG: 0.6504
Validation  random nDCG: 0.3944

--> Improvement! Best nDCG: 0.6504
Epoch: 2, Batch: 288/289, Pred Mean: -0.1105, NDCG: 0.7039

Training nDCG: 0.6784
Training random nDCG: 0.3476

Batch (val): 41/41
Validation nDCG: 0.7001
Validation  random nDCG: 0.3684

--> Improvement! Best nDCG: 0.7001
Epoch: 3, Batch: 288/289, Pred Mean: 0.2441, NDCG: 0.8711

Training nDCG: 0.7370
Training random nDCG: 0.3786

Batch (val): 41/41
Validation nDCG: 0.7523
Validation  random nDCG: 0.4012

--> Improvement! Best nDCG: 0.7523
Epoch: 4, Batch: 288/289, Pred Mean: 0.2314, NDCG: 0.8711

Training nDCG: 0.7637
Training random nDCG: 0.3554

Batch (val): 41/41
Validation nDCG: 0.7474
Validation  random nDCG: 0.4198

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.3938, NDCG: 0.7328

Training nDCG: 0.8086
Training random nDCG: 0.3727

Batch (val): 41/41
Validation nDCG: 0.7834
Validation  random nDCG: 0.3816

--> Improvement! Best nDCG: 0.7834
Epoch: 6, Batch: 288/289, Pred Mean: 0.5781, NDCG: 0.9060

Training nDCG: 0.8418
Training random nDCG: 0.3879

Batch (val): 41/41
Validation nDCG: 0.7803
Validation  random nDCG: 0.4050

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.8068, NDCG: 0.9060

Training nDCG: 0.8577
Training random nDCG: 0.3681

Batch (val): 41/41
Validation nDCG: 0.7745
Validation  random nDCG: 0.3916

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.0417, NDCG: 0.9325

Training nDCG: 0.8638
Training random nDCG: 0.3824

Batch (val): 41/41
Validation nDCG: 0.7701
Validation  random nDCG: 0.3772

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.0373, NDCG: 0.9060

Training nDCG: 0.8833
Training random nDCG: 0.3960

Batch (val): 41/41
Validation nDCG: 0.7869
Validation  random nDCG: 0.3569

--> Improvement! Best nDCG: 0.7869
Epoch: 10, Batch: 288/289, Pred Mean: 1.0702, NDCG: 1.0000

Training nDCG: 0.8821
Training random nDCG: 0.3808

Batch (val): 41/41
Validation nDCG: 0.7870
Validation  random nDCG: 0.3437

--> Improvement! Best nDCG: 0.7870
Epoch: 11, Batch: 288/289, Pred Mean: 0.9279, NDCG: 1.0000

Training nDCG: 0.8953
Training random nDCG: 0.3795

Batch (val): 41/41
Validation nDCG: 0.7905
Validation  random nDCG: 0.3626

--> Improvement! Best nDCG: 0.7905
Epoch: 12, Batch: 288/289, Pred Mean: 0.9262, NDCG: 0.9675

Training nDCG: 0.8946
Training random nDCG: 0.3748

Batch (val): 41/41
Validation nDCG: 0.8033
Validation  random nDCG: 0.3497

--> Improvement! Best nDCG: 0.8033
Epoch: 13, Batch: 288/289, Pred Mean: 2.3777, NDCG: 0.6448

Training nDCG: 0.9040
Training random nDCG: 0.3630

Batch (val): 41/41
Validation nDCG: 0.7707
Validation  random nDCG: 0.4060

--> No improvement. Patience: 1/4
Epoch: 14, Batch: 288/289, Pred Mean: 1.4713, NDCG: 0.8855

Training nDCG: 0.9083
Training random nDCG: 0.3711

Batch (val): 41/41
Validation nDCG: 0.7835
Validation  random nDCG: 0.3975

--> No improvement. Patience: 2/4
Epoch: 15, Batch: 288/289, Pred Mean: 1.4465, NDCG: 0.8529

Training nDCG: 0.9088
Training random nDCG: 0.3598

Batch (val): 37/41

[I 2026-06-08 03:29:37,048] Trial 2 finished with value: 0.803305357402548 and parameters: {'learning_rate': 0.0001283592906365915, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.8530092800505186.

Batch (val): 41/41
Validation nDCG: 0.7825
Validation  random nDCG: 0.3388

--> No improvement. Patience: 3/4
Training for 15 epochs took 366.51 seconds
Best hyperparameters: {'learning_rate': 0.0039035309714451068, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009

[I 2026-06-08 03:29:37,749] A new study created in memory with name: no-name-06fde42d-ee63-488f-a053-24d540d324cf

Running study for qwen semi-structured with inference=True and isco=False

    Config:
    - learning_rate = 0.0005122479582886235
    - embedding_size = 128
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.6595, NDCG: 0.9060

Training nDCG: 0.6999
Training random nDCG: 0.3504

Batch (val): 41/41
Validation nDCG: 0.7991
Validation  random nDCG: 0.3532

--> Improvement! Best nDCG: 0.7991
Epoch: 2, Batch: 288/289, Pred Mean: 1.0606, NDCG: 0.9675

Training nDCG: 0.7746
Training random nDCG: 0.3695

Batch (val): 41/41
Validation nDCG: 0.7850
Validation  random nDCG: 0.3472

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.2198, NDCG: 1.0000

Training nDCG: 0.7866
Training random nDCG: 0.3706

Batch (val): 41/41
Validation nDCG: 0.7695
Validation  random nDCG: 0.3450

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.3260, NDCG: 1.0000

Training nDCG: 0.8063
Training random nDCG: 0.3543

Batch (val): 41/41
Validation nDCG: 0.7652
Validation  random nDCG: 0.3269

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.3832, NDCG: 0.9675

Training nDCG: 0.8234
Training random nDCG: 0.3860

Batch (val): 41/41

[I 2026-06-08 03:31:37,507] Trial 0 finished with value: 0.7991028638381142 and parameters: {'learning_rate': 0.0005122479582886235, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 2}. Best is trial 0 with value: 0.7991028638381142.

Validation nDCG: 0.7860
Validation  random nDCG: 0.3113

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 119.72 seconds

    Config:
    - learning_rate = 0.0063143120968281365
    - embedding_size = 8
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 1.1698, NDCG: 0.8529

Training nDCG: 0.7195
Training random nDCG: 0.3629

Batch (val): 41/41
Validation nDCG: 0.7919
Validation  random nDCG: 0.3605

--> Improvement! Best nDCG: 0.7919
Epoch: 2, Batch: 288/289, Pred Mean: 1.3418, NDCG: 0.7328

Training nDCG: 0.7690
Training random nDCG: 0.3696

Batch (val): 41/41
Validation nDCG: 0.7784
Validation  random nDCG: 0.4444

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.1593, NDCG: 0.9469

Training nDCG: 0.7946
Training random nDCG: 0.3459

Batch (val): 41/41
Validation nDCG: 0.8099
Validation  random nDCG: 0.3941

--> Improvement! Best nDCG: 0.8099
Epoch: 4, Batch: 288/289, Pred Mean: 1.4668, NDCG: 0.9675

Training nDCG: 0.8033
Training random nDCG: 0.3509

Batch (val): 41/41
Validation nDCG: 0.8227
Validation  random nDCG: 0.3657

--> Improvement! Best nDCG: 0.8227
Epoch: 5, Batch: 288/289, Pred Mean: 1.0459, NDCG: 0.8855

Training nDCG: 0.8136
Training random nDCG: 0.3548

Batch (val): 41/41
Validation nDCG: 0.8087
Validation  random nDCG: 0.4050

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.7363, NDCG: 0.7328

Training nDCG: 0.8185
Training random nDCG: 0.3608

Batch (val): 41/41
Validation nDCG: 0.8041
Validation  random nDCG: 0.3570

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.0937, NDCG: 0.7328

Training nDCG: 0.8242
Training random nDCG: 0.3628

Batch (val): 41/41
Validation nDCG: 0.8172
Validation  random nDCG: 0.3855

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: -0.0645, NDCG: 0.7328

Training nDCG: 0.8353
Training random nDCG: 0.3448

Batch (val): 38/41

[I 2026-06-08 03:35:09,344] Trial 1 finished with value: 0.8226874398617182 and parameters: {'learning_rate': 0.0063143120968281365, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 4}. Best is trial 1 with value: 0.8226874398617182.

Batch (val): 41/41
Validation nDCG: 0.8049
Validation  random nDCG: 0.3817

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 211.69 seconds

    Config:
    - learning_rate = 0.0005681959974084141
    - embedding_size = 16
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.1752, NDCG: 0.6653

Training nDCG: 0.4409
Training random nDCG: 0.3564

Batch (val): 41/41
Validation nDCG: 0.5846
Validation  random nDCG: 0.3359

--> Improvement! Best nDCG: 0.5846
Epoch: 2, Batch: 288/289, Pred Mean: -0.1113, NDCG: 0.8385

Training nDCG: 0.6916
Training random nDCG: 0.3596

Batch (val): 41/41
Validation nDCG: 0.7356
Validation  random nDCG: 0.3601

--> Improvement! Best nDCG: 0.7356
Epoch: 3, Batch: 288/289, Pred Mean: 0.3467, NDCG: 0.9060

Training nDCG: 0.7812
Training random nDCG: 0.3565

Batch (val): 41/41
Validation nDCG: 0.7744
Validation  random nDCG: 0.3330

--> Improvement! Best nDCG: 0.7744
Epoch: 4, Batch: 288/289, Pred Mean: 0.5937, NDCG: 0.7123

Training nDCG: 0.8009
Training random nDCG: 0.3501

Batch (val): 41/41
Validation nDCG: 0.8132
Validation  random nDCG: 0.3204

--> Improvement! Best nDCG: 0.8132
Epoch: 5, Batch: 288/289, Pred Mean: 0.6688, NDCG: 0.7123

Training nDCG: 0.8239
Training random nDCG: 0.3741

Batch (val): 41/41
Validation nDCG: 0.8015
Validation  random nDCG: 0.3533

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.6611, NDCG: 0.7123

Training nDCG: 0.8344
Training random nDCG: 0.3668

Batch (val): 41/41
Validation nDCG: 0.8263
Validation  random nDCG: 0.3119

--> Improvement! Best nDCG: 0.8263
Epoch: 7, Batch: 288/289, Pred Mean: 0.7192, NDCG: 0.8711

Training nDCG: 0.8602
Training random nDCG: 0.3718

Batch (val): 41/41
Validation nDCG: 0.8071
Validation  random nDCG: 0.3233

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.7390, NDCG: 0.9060

Training nDCG: 0.8626
Training random nDCG: 0.3564

Batch (val): 41/41
Validation nDCG: 0.8271
Validation  random nDCG: 0.3271

--> Improvement! Best nDCG: 0.8271
Epoch: 9, Batch: 288/289, Pred Mean: 0.7257, NDCG: 0.8855

Training nDCG: 0.8685
Training random nDCG: 0.3507

Batch (val): 41/41
Validation nDCG: 0.8315
Validation  random nDCG: 0.3562

--> Improvement! Best nDCG: 0.8315
Epoch: 10, Batch: 288/289, Pred Mean: 0.7431, NDCG: 0.9675

Training nDCG: 0.8756
Training random nDCG: 0.3677

Batch (val): 41/41
Validation nDCG: 0.8499
Validation  random nDCG: 0.3132

--> Improvement! Best nDCG: 0.8499
Epoch: 11, Batch: 288/289, Pred Mean: 0.5702, NDCG: 1.0000

Training nDCG: 0.8889
Training random nDCG: 0.3504

Batch (val): 41/41
Validation nDCG: 0.8461
Validation  random nDCG: 0.4015

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: 0.5270, NDCG: 1.0000

Training nDCG: 0.9018
Training random nDCG: 0.3785

Batch (val): 41/41
Validation nDCG: 0.8571
Validation  random nDCG: 0.3189

--> Improvement! Best nDCG: 0.8571
Epoch: 13, Batch: 288/289, Pred Mean: 0.3032, NDCG: 1.0000

Training nDCG: 0.9009
Training random nDCG: 0.3626

Batch (val): 41/41
Validation nDCG: 0.8262
Validation  random nDCG: 0.3282

--> No improvement. Patience: 1/4
Epoch: 14, Batch: 288/289, Pred Mean: 0.4394, NDCG: 1.0000

Training nDCG: 0.9062
Training random nDCG: 0.3824

Batch (val): 41/41
Validation nDCG: 0.8027
Validation  random nDCG: 0.3989

--> No improvement. Patience: 2/4
Epoch: 15, Batch: 288/289, Pred Mean: 0.4265, NDCG: 1.0000

Training nDCG: 0.9073
Training random nDCG: 0.3635

Batch (val): 36/41

[I 2026-06-08 03:41:16,561] Trial 2 finished with value: 0.8570521086928155 and parameters: {'learning_rate': 0.0005681959974084141, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 8}. Best is trial 2 with value: 0.8570521086928155.

Batch (val): 41/41
Validation nDCG: 0.8153
Validation  random nDCG: 0.3580

--> No improvement. Patience: 3/4
Training for 15 epochs took 367.20 seconds
Best hyperparameters: {'learning_rate': 0.0005681959974084141, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052

[I 2026-06-08 03:41:17,273] A new study created in memory with name: no-name-41cbbb0e-c86e-43af-9f04-21aacef18d22

Running study for qwen unstructured with inference=True and isco=False

    Config:
    - learning_rate = 0.0003511402518731789
    - embedding_size = 64
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.1236, NDCG: 0.6934

Training nDCG: 0.5855
Training random nDCG: 0.3987

Batch (val): 41/41
Validation nDCG: 0.6194
Validation  random nDCG: 0.3773

--> Improvement! Best nDCG: 0.6194
Epoch: 2, Batch: 288/289, Pred Mean: 0.2872, NDCG: 0.9197

Training nDCG: 0.7386
Training random nDCG: 0.3977

Batch (val): 41/41
Validation nDCG: 0.7542
Validation  random nDCG: 0.4438

--> Improvement! Best nDCG: 0.7542
Epoch: 3, Batch: 288/289, Pred Mean: 0.3099, NDCG: 0.6934

Training nDCG: 0.7727
Training random nDCG: 0.3881

Batch (val): 41/41
Validation nDCG: 0.7621
Validation  random nDCG: 0.3399

--> Improvement! Best nDCG: 0.7621
Epoch: 4, Batch: 288/289, Pred Mean: 0.3207, NDCG: 1.0000

Training nDCG: 0.8021
Training random nDCG: 0.3994

Batch (val): 41/41
Validation nDCG: 0.7567
Validation  random nDCG: 0.3613

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.2944, NDCG: 1.0000

Training nDCG: 0.8127
Training random nDCG: 0.3971

Batch (val): 41/41
Validation nDCG: 0.7487
Validation  random nDCG: 0.3838

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.2671, NDCG: 1.0000

Training nDCG: 0.8296
Training random nDCG: 0.3602

Batch (val): 41/41
Validation nDCG: 0.7559
Validation  random nDCG: 0.3661

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.2495, NDCG: 1.0000

Training nDCG: 0.8422
Training random nDCG: 0.4141

Batch (val): 35/41

[I 2026-06-08 03:44:05,737] Trial 0 finished with value: 0.762075474025438 and parameters: {'learning_rate': 0.0003511402518731789, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.762075474025438.

Batch (val): 41/41
Validation nDCG: 0.7509
Validation  random nDCG: 0.3954

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 168.42 seconds

    Config:
    - learning_rate = 0.0006724992879192853
    - embedding_size = 16
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.1121, NDCG: 0.9197

Training nDCG: 0.6587
Training random nDCG: 0.3995

Batch (val): 41/41
Validation nDCG: 0.7658
Validation  random nDCG: 0.3312

--> Improvement! Best nDCG: 0.7658
Epoch: 2, Batch: 288/289, Pred Mean: 0.4391, NDCG: 0.6934

Training nDCG: 0.7555
Training random nDCG: 0.3861

Batch (val): 41/41
Validation nDCG: 0.7573
Validation  random nDCG: 0.3773

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.6730, NDCG: 0.6934

Training nDCG: 0.7756
Training random nDCG: 0.3939

Batch (val): 41/41
Validation nDCG: 0.7874
Validation  random nDCG: 0.3695

--> Improvement! Best nDCG: 0.7874
Epoch: 4, Batch: 288/289, Pred Mean: 0.6362, NDCG: 1.0000

Training nDCG: 0.7896
Training random nDCG: 0.4008

Batch (val): 41/41
Validation nDCG: 0.7646
Validation  random nDCG: 0.3953

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.7141, NDCG: 1.0000

Training nDCG: 0.8055
Training random nDCG: 0.4125

Batch (val): 41/41
Validation nDCG: 0.7709
Validation  random nDCG: 0.3972

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.6869, NDCG: 1.0000

Training nDCG: 0.8155
Training random nDCG: 0.3991

Batch (val): 41/41
Validation nDCG: 0.7599
Validation  random nDCG: 0.4199

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.7321, NDCG: 1.0000

Training nDCG: 0.8241
Training random nDCG: 0.3722

Batch (val): 36/41

[I 2026-06-08 03:46:45,074] Trial 1 finished with value: 0.7874218497474944 and parameters: {'learning_rate': 0.0006724992879192853, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}. Best is trial 1 with value: 0.7874218497474944.

Batch (val): 41/41
Validation nDCG: 0.7712
Validation  random nDCG: 0.3236

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 159.31 seconds

    Config:
    - learning_rate = 0.0021120785353221797
    - embedding_size = 8
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.4569, NDCG: 1.0000

Training nDCG: 0.6564
Training random nDCG: 0.3867

Batch (val): 41/41
Validation nDCG: 0.7873
Validation  random nDCG: 0.3853

--> Improvement! Best nDCG: 0.7873
Epoch: 2, Batch: 288/289, Pred Mean: 0.7860, NDCG: 1.0000

Training nDCG: 0.7618
Training random nDCG: 0.3984

Batch (val): 41/41
Validation nDCG: 0.7433
Validation  random nDCG: 0.3778

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.9200, NDCG: 1.0000

Training nDCG: 0.7551
Training random nDCG: 0.4042

Batch (val): 41/41
Validation nDCG: 0.7368
Validation  random nDCG: 0.3789

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.9493, NDCG: 1.0000

Training nDCG: 0.7692
Training random nDCG: 0.3982

Batch (val): 41/41
Validation nDCG: 0.7550
Validation  random nDCG: 0.3467

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.0698, NDCG: 0.9197

Training nDCG: 0.7800
Training random nDCG: 0.3904

Batch (val): 41/41
Validation nDCG: 0.7282
Validation  random nDCG: 0.3964

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 119.00 seconds

[I 2026-06-08 03:48:44,097] Trial 2 finished with value: 0.787286260780973 and parameters: {'learning_rate': 0.0021120785353221797, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 4}. Best is trial 1 with value: 0.7874218497474944.

Best hyperparameters: {'learning_rate': 0.0006724992879192853, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422

[I 2026-06-08 03:48:44,636] A new study created in memory with name: no-name-8f5656f3-b194-4fef-8d73-7d54932ad3ca

Running study for gemma structured with inference=True and isco=False

    Config:
    - learning_rate = 0.000778726906566581
    - embedding_size = 64
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.4440, NDCG: 0.7328

Training nDCG: 0.6683
Training random nDCG: 0.3540

Batch (val): 41/41
Validation nDCG: 0.8071
Validation  random nDCG: 0.3377

--> Improvement! Best nDCG: 0.8071
Epoch: 2, Batch: 288/289, Pred Mean: 0.7953, NDCG: 0.9060

Training nDCG: 0.7891
Training random nDCG: 0.3648

Batch (val): 41/41
Validation nDCG: 0.8035
Validation  random nDCG: 0.4040

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.0060, NDCG: 0.9060

Training nDCG: 0.8105
Training random nDCG: 0.3667

Batch (val): 41/41
Validation nDCG: 0.8235
Validation  random nDCG: 0.3748

--> Improvement! Best nDCG: 0.8235
Epoch: 4, Batch: 288/289, Pred Mean: 1.1420, NDCG: 0.9060

Training nDCG: 0.8068
Training random nDCG: 0.3754

Batch (val): 41/41
Validation nDCG: 0.8483
Validation  random nDCG: 0.3905

--> Improvement! Best nDCG: 0.8483
Epoch: 5, Batch: 288/289, Pred Mean: 1.2230, NDCG: 0.9675

Training nDCG: 0.8286
Training random nDCG: 0.3240

Batch (val): 41/41
Validation nDCG: 0.8403
Validation  random nDCG: 0.3439

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.2543, NDCG: 0.9060

Training nDCG: 0.8166
Training random nDCG: 0.3441

Batch (val): 41/41
Validation nDCG: 0.8194
Validation  random nDCG: 0.3295

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.3747, NDCG: 0.9060

Training nDCG: 0.8407
Training random nDCG: 0.3856

Batch (val): 41/41
Validation nDCG: 0.8139
Validation  random nDCG: 0.3662

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.3365, NDCG: 0.9060

Training nDCG: 0.8602
Training random nDCG: 0.3720

Batch (val): 40/41

[I 2026-06-08 03:52:18,608] Trial 0 finished with value: 0.8482803777175711 and parameters: {'learning_rate': 0.000778726906566581, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.8482803777175711.

Batch (val): 41/41
Validation nDCG: 0.8072
Validation  random nDCG: 0.3259

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 213.92 seconds

    Config:
    - learning_rate = 0.0005769031054685276
    - embedding_size = 128
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.5453, NDCG: 0.9675

Training nDCG: 0.6746
Training random nDCG: 0.3646

Batch (val): 41/41
Validation nDCG: 0.7748
Validation  random nDCG: 0.3782

--> Improvement! Best nDCG: 0.7748
Epoch: 2, Batch: 288/289, Pred Mean: 0.9447, NDCG: 0.9675

Training nDCG: 0.7924
Training random nDCG: 0.3755

Batch (val): 41/41
Validation nDCG: 0.7732
Validation  random nDCG: 0.3337

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.1575, NDCG: 0.9060

Training nDCG: 0.7895
Training random nDCG: 0.3562

Batch (val): 41/41
Validation nDCG: 0.8055
Validation  random nDCG: 0.3340

--> Improvement! Best nDCG: 0.8055
Epoch: 4, Batch: 288/289, Pred Mean: 1.2642, NDCG: 0.9060

Training nDCG: 0.8119
Training random nDCG: 0.3829

Batch (val): 41/41
Validation nDCG: 0.8245
Validation  random nDCG: 0.3591

--> Improvement! Best nDCG: 0.8245
Epoch: 5, Batch: 288/289, Pred Mean: 1.3807, NDCG: 0.9675

Training nDCG: 0.8173
Training random nDCG: 0.3762

Batch (val): 41/41
Validation nDCG: 0.8171
Validation  random nDCG: 0.3383

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.3752, NDCG: 0.9469

Training nDCG: 0.8292
Training random nDCG: 0.3575

Batch (val): 41/41
Validation nDCG: 0.8091
Validation  random nDCG: 0.3836

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.5185, NDCG: 0.9060

Training nDCG: 0.8290
Training random nDCG: 0.3591

Batch (val): 41/41
Validation nDCG: 0.8340
Validation  random nDCG: 0.3071

--> Improvement! Best nDCG: 0.8340
Epoch: 8, Batch: 288/289, Pred Mean: 1.4449, NDCG: 0.8855

Training nDCG: 0.8496
Training random nDCG: 0.3697

Batch (val): 41/41
Validation nDCG: 0.8179
Validation  random nDCG: 0.3304

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.3378, NDCG: 0.6979

Training nDCG: 0.8489
Training random nDCG: 0.3518

Batch (val): 41/41
Validation nDCG: 0.7885
Validation  random nDCG: 0.3529

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.5137, NDCG: 0.7328

Training nDCG: 0.8601
Training random nDCG: 0.3556

Batch (val): 41/41
Validation nDCG: 0.7928
Validation  random nDCG: 0.3490

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.7032, NDCG: 0.7123

Training nDCG: 0.8645
Training random nDCG: 0.3651

Batch (val): 38/41

[I 2026-06-08 03:56:42,570] Trial 1 finished with value: 0.8339685612613751 and parameters: {'learning_rate': 0.0005769031054685276, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 8}. Best is trial 0 with value: 0.8482803777175711.

Batch (val): 41/41
Validation nDCG: 0.7954
Validation  random nDCG: 0.4042

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 263.95 seconds

    Config:
    - learning_rate = 0.0014470198628970799
    - embedding_size = 128
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 1.0400, NDCG: 0.9675

Training nDCG: 0.7431
Training random nDCG: 0.3737

Batch (val): 41/41
Validation nDCG: 0.8102
Validation  random nDCG: 0.3423

--> Improvement! Best nDCG: 0.8102
Epoch: 2, Batch: 288/289, Pred Mean: 1.2286, NDCG: 0.9675

Training nDCG: 0.8036
Training random nDCG: 0.3757

Batch (val): 41/41
Validation nDCG: 0.7709
Validation  random nDCG: 0.3643

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.4473, NDCG: 0.7328

Training nDCG: 0.8085
Training random nDCG: 0.3642

Batch (val): 41/41
Validation nDCG: 0.8262
Validation  random nDCG: 0.3234

--> Improvement! Best nDCG: 0.8262
Epoch: 4, Batch: 288/289, Pred Mean: 1.1719, NDCG: 0.9675

Training nDCG: 0.8074
Training random nDCG: 0.3701

Batch (val): 41/41
Validation nDCG: 0.8029
Validation  random nDCG: 0.3419

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.2376, NDCG: 0.9675

Training nDCG: 0.8137
Training random nDCG: 0.3560

Batch (val): 41/41
Validation nDCG: 0.8016
Validation  random nDCG: 0.3590

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.2117, NDCG: 0.9675

Training nDCG: 0.8280
Training random nDCG: 0.3392

Batch (val): 41/41
Validation nDCG: 0.7928
Validation  random nDCG: 0.3428

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.5440, NDCG: 0.7328

Training nDCG: 0.8496
Training random nDCG: 0.3534

Batch (val): 35/41

[I 2026-06-08 03:59:37,807] Trial 2 finished with value: 0.8261620663323682 and parameters: {'learning_rate': 0.0014470198628970799, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 2}. Best is trial 0 with value: 0.8482803777175711.

Batch (val): 41/41
Validation nDCG: 0.7687
Validation  random nDCG: 0.3394

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 175.21 seconds
Best hyperparameters: {'learning_rate': 0.000778726906566581, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280

[I 2026-06-08 03:59:38,486] A new study created in memory with name: no-name-b71d4409-3e8b-4ec2-a526-74da87249bea

Running study for gemma semi-structured with inference=True and isco=False

    Config:
    - learning_rate = 0.0011754514032692287
    - embedding_size = 64
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.3382, NDCG: 0.9675

Training nDCG: 0.6889
Training random nDCG: 0.3606

Batch (val): 41/41
Validation nDCG: 0.8467
Validation  random nDCG: 0.3402

--> Improvement! Best nDCG: 0.8467
Epoch: 2, Batch: 288/289, Pred Mean: -0.0574, NDCG: 0.9675

Training nDCG: 0.8147
Training random nDCG: 0.3477

Batch (val): 41/41
Validation nDCG: 0.8270
Validation  random nDCG: 0.3958

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.0487, NDCG: 0.9675

Training nDCG: 0.8071
Training random nDCG: 0.3669

Batch (val): 41/41
Validation nDCG: 0.8388
Validation  random nDCG: 0.4255

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.5420, NDCG: 0.9675

Training nDCG: 0.8360
Training random nDCG: 0.3941

Batch (val): 41/41
Validation nDCG: 0.8196
Validation  random nDCG: 0.3524

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.9640, NDCG: 0.9675

Training nDCG: 0.8534
Training random nDCG: 0.3659

Batch (val): 38/41

[I 2026-06-08 04:01:40,751] Trial 0 finished with value: 0.8466874191733541 and parameters: {'learning_rate': 0.0011754514032692287, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.8466874191733541.

Batch (val): 41/41
Validation nDCG: 0.8276
Validation  random nDCG: 0.3876

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 122.23 seconds

    Config:
    - learning_rate = 0.001978043464336819
    - embedding_size = 16
    - pooling_method = max
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.8296, NDCG: 0.9675

Training nDCG: 0.6842
Training random nDCG: 0.3918

Batch (val): 41/41
Validation nDCG: 0.8421
Validation  random nDCG: 0.3322

--> Improvement! Best nDCG: 0.8421
Epoch: 2, Batch: 288/289, Pred Mean: 0.7678, NDCG: 0.9675

Training nDCG: 0.8128
Training random nDCG: 0.3683

Batch (val): 41/41
Validation nDCG: 0.8346
Validation  random nDCG: 0.4181

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.5920, NDCG: 0.9325

Training nDCG: 0.8309
Training random nDCG: 0.3598

Batch (val): 41/41
Validation nDCG: 0.8629
Validation  random nDCG: 0.3756

--> Improvement! Best nDCG: 0.8629
Epoch: 4, Batch: 288/289, Pred Mean: 0.6609, NDCG: 0.9675

Training nDCG: 0.8351
Training random nDCG: 0.3362

Batch (val): 41/41
Validation nDCG: 0.8674
Validation  random nDCG: 0.3424

--> Improvement! Best nDCG: 0.8674
Epoch: 5, Batch: 288/289, Pred Mean: 0.7848, NDCG: 0.9469

Training nDCG: 0.8604
Training random nDCG: 0.3568

Batch (val): 41/41
Validation nDCG: 0.8766
Validation  random nDCG: 0.3251

--> Improvement! Best nDCG: 0.8766
Epoch: 6, Batch: 288/289, Pred Mean: 1.0550, NDCG: 0.9675

Training nDCG: 0.8809
Training random nDCG: 0.3744

Batch (val): 41/41
Validation nDCG: 0.8621
Validation  random nDCG: 0.3530

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.1433, NDCG: 0.9675

Training nDCG: 0.8859
Training random nDCG: 0.3610

Batch (val): 41/41
Validation nDCG: 0.8915
Validation  random nDCG: 0.4004

--> Improvement! Best nDCG: 0.8915
Epoch: 8, Batch: 288/289, Pred Mean: 1.6055, NDCG: 0.9675

Training nDCG: 0.8876
Training random nDCG: 0.3630

Batch (val): 41/41
Validation nDCG: 0.8751
Validation  random nDCG: 0.3856

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.4834, NDCG: 0.9675

Training nDCG: 0.8935
Training random nDCG: 0.3726

Batch (val): 41/41
Validation nDCG: 0.8677
Validation  random nDCG: 0.3642

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.6823, NDCG: 0.9675

Training nDCG: 0.9087
Training random nDCG: 0.3517

Batch (val): 41/41
Validation nDCG: 0.8836
Validation  random nDCG: 0.2951

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.7696, NDCG: 0.9675

Training nDCG: 0.9067
Training random nDCG: 0.3613

Batch (val): 40/41

[I 2026-06-08 04:06:21,991] Trial 1 finished with value: 0.8915411430097363 and parameters: {'learning_rate': 0.001978043464336819, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 8}. Best is trial 1 with value: 0.8915411430097363.

Batch (val): 41/41
Validation nDCG: 0.8739
Validation  random nDCG: 0.3235

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 281.21 seconds

    Config:
    - learning_rate = 0.0005156727416913147
    - embedding_size = 64
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.3606, NDCG: 0.9675

Training nDCG: 0.7128
Training random nDCG: 0.4019

Batch (val): 41/41
Validation nDCG: 0.8557
Validation  random nDCG: 0.3607

--> Improvement! Best nDCG: 0.8557
Epoch: 2, Batch: 288/289, Pred Mean: 0.6973, NDCG: 0.9675

Training nDCG: 0.8156
Training random nDCG: 0.3608

Batch (val): 41/41
Validation nDCG: 0.8429
Validation  random nDCG: 0.3815

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.8768, NDCG: 0.9675

Training nDCG: 0.8273
Training random nDCG: 0.3698

Batch (val): 41/41
Validation nDCG: 0.8266
Validation  random nDCG: 0.3275

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.9624, NDCG: 0.9469

Training nDCG: 0.8468
Training random nDCG: 0.3614

Batch (val): 41/41
Validation nDCG: 0.8348
Validation  random nDCG: 0.4016

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.1675, NDCG: 0.9325

Training nDCG: 0.8682
Training random nDCG: 0.3748

Batch (val): 37/41

[I 2026-06-08 04:08:37,470] Trial 2 finished with value: 0.8556523995331844 and parameters: {'learning_rate': 0.0005156727416913147, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 4}. Best is trial 1 with value: 0.8915411430097363.

Batch (val): 41/41
Validation nDCG: 0.8289
Validation  random nDCG: 0.3686

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 135.45 seconds
Best hyperparameters: {'learning_rate': 0.001978043464336819, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541

[I 2026-06-08 04:08:38,366] A new study created in memory with name: no-name-201b47fc-6976-4193-a6d2-834f69823a26

Running study for gemma unstructured with inference=True and isco=False

    Config:
    - learning_rate = 0.0028293673463718133
    - embedding_size = 32
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 1.2792, NDCG: 0.7328

Training nDCG: 0.7874
Training random nDCG: 0.3556

Batch (val): 41/41
Validation nDCG: 0.8223
Validation  random nDCG: 0.3433

--> Improvement! Best nDCG: 0.8223
Epoch: 2, Batch: 288/289, Pred Mean: 1.6238, NDCG: 0.9060

Training nDCG: 0.8166
Training random nDCG: 0.3520

Batch (val): 41/41
Validation nDCG: 0.8268
Validation  random nDCG: 0.3978

--> Improvement! Best nDCG: 0.8268
Epoch: 3, Batch: 288/289, Pred Mean: 1.5325, NDCG: 0.7328

Training nDCG: 0.8352
Training random nDCG: 0.3567

Batch (val): 41/41
Validation nDCG: 0.8443
Validation  random nDCG: 0.3491

--> Improvement! Best nDCG: 0.8443
Epoch: 4, Batch: 288/289, Pred Mean: 1.7238, NDCG: 1.0000

Training nDCG: 0.8313
Training random nDCG: 0.3635

Batch (val): 41/41
Validation nDCG: 0.8179
Validation  random nDCG: 0.3176

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.9561, NDCG: 1.0000

Training nDCG: 0.8550
Training random nDCG: 0.3595

Batch (val): 41/41
Validation nDCG: 0.8115
Validation  random nDCG: 0.3584

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.9760, NDCG: 0.9675

Training nDCG: 0.8736
Training random nDCG: 0.3687

Batch (val): 41/41
Validation nDCG: 0.8067
Validation  random nDCG: 0.3527

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 2.4461, NDCG: 0.9060

Training nDCG: 0.8687
Training random nDCG: 0.3492

Batch (val): 41/41
Validation nDCG: 0.8267
Validation  random nDCG: 0.3481

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 191.62 seconds

[I 2026-06-08 04:11:50,024] Trial 0 finished with value: 0.8442785020470118 and parameters: {'learning_rate': 0.0028293673463718133, 'embedding_size': 32, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.8442785020470118.

    Config:
    - learning_rate = 0.0057996232525387974
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.8375, NDCG: 0.9060

Training nDCG: 0.7368
Training random nDCG: 0.3525

Batch (val): 41/41
Validation nDCG: 0.8469
Validation  random nDCG: 0.3116

--> Improvement! Best nDCG: 0.8469
Epoch: 2, Batch: 288/289, Pred Mean: 0.6700, NDCG: 0.9469

Training nDCG: 0.8081
Training random nDCG: 0.3694

Batch (val): 41/41
Validation nDCG: 0.8177
Validation  random nDCG: 0.3770

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.7272, NDCG: 0.7123

Training nDCG: 0.8287
Training random nDCG: 0.3777

Batch (val): 41/41
Validation nDCG: 0.8083
Validation  random nDCG: 0.4521

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.9700, NDCG: 0.7328

Training nDCG: 0.8376
Training random nDCG: 0.3690

Batch (val): 41/41
Validation nDCG: 0.8029
Validation  random nDCG: 0.3517

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.8406, NDCG: 0.7328

Training nDCG: 0.8559
Training random nDCG: 0.3794

Batch (val): 39/41

[I 2026-06-08 04:14:11,017] Trial 1 finished with value: 0.8469219066388872 and parameters: {'learning_rate': 0.0057996232525387974, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.8469219066388872.

Batch (val): 41/41
Validation nDCG: 0.8188
Validation  random nDCG: 0.3511

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 140.96 seconds

    Config:
    - learning_rate = 0.002520815775437636
    - embedding_size = 32
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.6977, NDCG: 0.9469

Training nDCG: 0.7157
Training random nDCG: 0.3732

Batch (val): 41/41
Validation nDCG: 0.8357
Validation  random nDCG: 0.3397

--> Improvement! Best nDCG: 0.8357
Epoch: 2, Batch: 288/289, Pred Mean: 1.0462, NDCG: 1.0000

Training nDCG: 0.8083
Training random nDCG: 0.3754

Batch (val): 41/41
Validation nDCG: 0.8231
Validation  random nDCG: 0.3344

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.8490, NDCG: 1.0000

Training nDCG: 0.8095
Training random nDCG: 0.3748

Batch (val): 41/41
Validation nDCG: 0.8176
Validation  random nDCG: 0.3071

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.8299, NDCG: 0.7328

Training nDCG: 0.8134
Training random nDCG: 0.3663

Batch (val): 41/41
Validation nDCG: 0.8710
Validation  random nDCG: 0.3729

--> Improvement! Best nDCG: 0.8710
Epoch: 5, Batch: 288/289, Pred Mean: 0.3796, NDCG: 0.7328

Training nDCG: 0.8312
Training random nDCG: 0.3824

Batch (val): 41/41
Validation nDCG: 0.8489
Validation  random nDCG: 0.3183

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -1.1149, NDCG: 0.9675

Training nDCG: 0.8465
Training random nDCG: 0.3594

Batch (val): 41/41
Validation nDCG: 0.8518
Validation  random nDCG: 0.3348

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.5864, NDCG: 0.7328

Training nDCG: 0.8559
Training random nDCG: 0.3536

Batch (val): 41/41
Validation nDCG: 0.8322
Validation  random nDCG: 0.3929

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.2315, NDCG: 0.9675

Training nDCG: 0.8675
Training random nDCG: 0.3684

Batch (val): 41/41

[I 2026-06-08 04:18:08,640] Trial 2 finished with value: 0.8710181016407652 and parameters: {'learning_rate': 0.002520815775437636, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 8}. Best is trial 2 with value: 0.8710181016407652.

Validation nDCG: 0.8596
Validation  random nDCG: 0.2915

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 237.60 seconds
Best hyperparameters: {'learning_rate': 0.002520815775437636, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018

[I 2026-06-08 04:18:09,400] A new study created in memory with name: no-name-58bfb550-f3ab-4f1b-b794-b3e183e53d8d

Running study for llama structured with inference=True and isco=False

    Config:
    - learning_rate = 0.0025994262596912253
    - embedding_size = 64
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.2973, NDCG: 0.9469

Training nDCG: 0.7295
Training random nDCG: 0.3543

Batch (val): 41/41
Validation nDCG: 0.8114
Validation  random nDCG: 0.3956

--> Improvement! Best nDCG: 0.8114
Epoch: 2, Batch: 288/289, Pred Mean: 1.0553, NDCG: 0.9469

Training nDCG: 0.8103
Training random nDCG: 0.3534

Batch (val): 41/41
Validation nDCG: 0.8287
Validation  random nDCG: 0.3537

--> Improvement! Best nDCG: 0.8287
Epoch: 3, Batch: 288/289, Pred Mean: 1.1443, NDCG: 0.9469

Training nDCG: 0.8032
Training random nDCG: 0.3748

Batch (val): 41/41
Validation nDCG: 0.8596
Validation  random nDCG: 0.4737

--> Improvement! Best nDCG: 0.8596
Epoch: 4, Batch: 288/289, Pred Mean: 0.1222, NDCG: 0.9469

Training nDCG: 0.7987
Training random nDCG: 0.3817

Batch (val): 41/41
Validation nDCG: 0.8231
Validation  random nDCG: 0.4399

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.5030, NDCG: 0.9325

Training nDCG: 0.8126
Training random nDCG: 0.3804

Batch (val): 41/41
Validation nDCG: 0.8293
Validation  random nDCG: 0.3819

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.0045, NDCG: 0.9469

Training nDCG: 0.8212
Training random nDCG: 0.3589

Batch (val): 41/41
Validation nDCG: 0.8462
Validation  random nDCG: 0.3872

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.5267, NDCG: 0.9469

Training nDCG: 0.8286
Training random nDCG: 0.3897

Batch (val): 39/41

[I 2026-06-08 04:21:18,739] Trial 0 finished with value: 0.8596373194639388 and parameters: {'learning_rate': 0.0025994262596912253, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.8596373194639388.

Batch (val): 41/41
Validation nDCG: 0.8355
Validation  random nDCG: 0.3496

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 189.29 seconds

    Config:
    - learning_rate = 0.0004913429249869507
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.0742, NDCG: 0.8180

Training nDCG: 0.5007
Training random nDCG: 0.3544

Batch (val): 41/41
Validation nDCG: 0.7844
Validation  random nDCG: 0.3289

--> Improvement! Best nDCG: 0.7844
Epoch: 2, Batch: 288/289, Pred Mean: 0.3627, NDCG: 0.8385

Training nDCG: 0.7763
Training random nDCG: 0.3699

Batch (val): 41/41
Validation nDCG: 0.8243
Validation  random nDCG: 0.3332

--> Improvement! Best nDCG: 0.8243
Epoch: 3, Batch: 288/289, Pred Mean: 0.6548, NDCG: 0.8385

Training nDCG: 0.8011
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.8456
Validation  random nDCG: 0.4147

--> Improvement! Best nDCG: 0.8456
Epoch: 4, Batch: 288/289, Pred Mean: 0.6902, NDCG: 0.8385

Training nDCG: 0.8148
Training random nDCG: 0.3735

Batch (val): 41/41
Validation nDCG: 0.8361
Validation  random nDCG: 0.3737

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.6994, NDCG: 0.8711

Training nDCG: 0.8379
Training random nDCG: 0.3688

Batch (val): 41/41
Validation nDCG: 0.8447
Validation  random nDCG: 0.3455

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.7987, NDCG: 0.9325

Training nDCG: 0.8720
Training random nDCG: 0.3665

Batch (val): 41/41
Validation nDCG: 0.8514
Validation  random nDCG: 0.3829

--> Improvement! Best nDCG: 0.8514
Epoch: 7, Batch: 288/289, Pred Mean: 0.8881, NDCG: 0.9325

Training nDCG: 0.8813
Training random nDCG: 0.3775

Batch (val): 41/41
Validation nDCG: 0.8330
Validation  random nDCG: 0.3385

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.9647, NDCG: 0.9325

Training nDCG: 0.8898
Training random nDCG: 0.3669

Batch (val): 41/41
Validation nDCG: 0.8278
Validation  random nDCG: 0.3910

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: 1.0846, NDCG: 0.9469

Training nDCG: 0.8973
Training random nDCG: 0.3670

Batch (val): 41/41
Validation nDCG: 0.8206
Validation  random nDCG: 0.3976

--> No improvement. Patience: 3/4
Epoch: 10, Batch: 288/289, Pred Mean: 1.3239, NDCG: 0.9469

Training nDCG: 0.8892
Training random nDCG: 0.3669

Batch (val): 41/41
Validation nDCG: 0.8065
Validation  random nDCG: 0.3568

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 10
Training for 15 epochs took 253.99 seconds

[I 2026-06-08 04:25:32,764] Trial 1 finished with value: 0.8513899417963051 and parameters: {'learning_rate': 0.0004913429249869507, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.8596373194639388.

    Config:
    - learning_rate = 0.0034664680245234973
    - embedding_size = 8
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.8039, NDCG: 0.8711

Training nDCG: 0.7135
Training random nDCG: 0.3572

Batch (val): 41/41
Validation nDCG: 0.8293
Validation  random nDCG: 0.3746

--> Improvement! Best nDCG: 0.8293
Epoch: 2, Batch: 288/289, Pred Mean: 1.1665, NDCG: 0.8855

Training nDCG: 0.8091
Training random nDCG: 0.3743

Batch (val): 41/41
Validation nDCG: 0.8237
Validation  random nDCG: 0.3865

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.1893, NDCG: 0.8855

Training nDCG: 0.8320
Training random nDCG: 0.3566

Batch (val): 41/41
Validation nDCG: 0.8339
Validation  random nDCG: 0.4369

--> Improvement! Best nDCG: 0.8339
Epoch: 4, Batch: 288/289, Pred Mean: 1.2535, NDCG: 0.8855

Training nDCG: 0.8449
Training random nDCG: 0.3697

Batch (val): 41/41
Validation nDCG: 0.8328
Validation  random nDCG: 0.3404

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.3758, NDCG: 0.8855

Training nDCG: 0.8511
Training random nDCG: 0.3886

Batch (val): 41/41
Validation nDCG: 0.8281
Validation  random nDCG: 0.3866

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.6571, NDCG: 0.8855

Training nDCG: 0.8681
Training random nDCG: 0.3818

Batch (val): 41/41
Validation nDCG: 0.8344
Validation  random nDCG: 0.3857

--> Improvement! Best nDCG: 0.8344
Epoch: 7, Batch: 288/289, Pred Mean: 1.7548, NDCG: 0.8855

Training nDCG: 0.8836
Training random nDCG: 0.3730

Batch (val): 41/41
Validation nDCG: 0.8132
Validation  random nDCG: 0.3755

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 2.0136, NDCG: 0.8711

Training nDCG: 0.8833
Training random nDCG: 0.3831

Batch (val): 41/41
Validation nDCG: 0.8261
Validation  random nDCG: 0.4202

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: 2.0851, NDCG: 0.8711

Training nDCG: 0.8954
Training random nDCG: 0.3772

Batch (val): 41/41
Validation nDCG: 0.8550
Validation  random nDCG: 0.4183

--> Improvement! Best nDCG: 0.8550
Epoch: 10, Batch: 288/289, Pred Mean: 1.7576, NDCG: 0.9469

Training nDCG: 0.8970
Training random nDCG: 0.3525

Batch (val): 41/41
Validation nDCG: 0.8140
Validation  random nDCG: 0.4164

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: 2.0497, NDCG: 0.9469

Training nDCG: 0.9064
Training random nDCG: 0.3657

Batch (val): 41/41
Validation nDCG: 0.8225
Validation  random nDCG: 0.3927

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: 1.9810, NDCG: 0.9469

Training nDCG: 0.9130
Training random nDCG: 0.3797

Batch (val): 41/41
Validation nDCG: 0.8320
Validation  random nDCG: 0.3705

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: 1.8946, NDCG: 0.9675

Training nDCG: 0.9177
Training random nDCG: 0.3836

Batch (val): 35/41

[I 2026-06-08 04:31:20,213] Trial 2 finished with value: 0.8550475178759539 and parameters: {'learning_rate': 0.0034664680245234973, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.8596373194639388.

Batch (val): 41/41
Validation nDCG: 0.8203
Validation  random nDCG: 0.3711

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 347.42 seconds
Best hyperparameters: {'learning_rate': 0.0025994262596912253, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637

[I 2026-06-08 04:31:21,159] A new study created in memory with name: no-name-e1c996a6-8267-44ac-a56a-a99c552106de

Running study for llama semi-structured with inference=True and isco=False

    Config:
    - learning_rate = 0.0005401747599961397
    - embedding_size = 128
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.6254, NDCG: 0.8772

Training nDCG: 0.7084
Training random nDCG: 0.3731

Batch (val): 41/41
Validation nDCG: 0.7832
Validation  random nDCG: 0.3975

--> Improvement! Best nDCG: 0.7832
Epoch: 2, Batch: 288/289, Pred Mean: 0.6372, NDCG: 0.6509

Training nDCG: 0.7713
Training random nDCG: 0.3724

Batch (val): 41/41
Validation nDCG: 0.8052
Validation  random nDCG: 0.3759

--> Improvement! Best nDCG: 0.8052
Epoch: 3, Batch: 288/289, Pred Mean: 1.0152, NDCG: 0.5706

Training nDCG: 0.7919
Training random nDCG: 0.3737

Batch (val): 41/41
Validation nDCG: 0.7939
Validation  random nDCG: 0.3622

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.7884, NDCG: 1.0000

Training nDCG: 0.8017
Training random nDCG: 0.3726

Batch (val): 41/41
Validation nDCG: 0.7941
Validation  random nDCG: 0.3977

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.6103, NDCG: 1.0000

Training nDCG: 0.8094
Training random nDCG: 0.3693

Batch (val): 41/41
Validation nDCG: 0.7815
Validation  random nDCG: 0.4201

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.3971, NDCG: 1.0000

Training nDCG: 0.8191
Training random nDCG: 0.3574

Batch (val): 38/41

[I 2026-06-08 04:34:20,267] Trial 0 finished with value: 0.8052175595109395 and parameters: {'learning_rate': 0.0005401747599961397, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.8052175595109395.

Batch (val): 41/41
Validation nDCG: 0.7905
Validation  random nDCG: 0.3193

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 179.06 seconds

    Config:
    - learning_rate = 0.00031965048909676227
    - embedding_size = 8
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.7379, NDCG: 0.6131

Training nDCG: 0.5186
Training random nDCG: 0.3723

Batch (val): 41/41
Validation nDCG: 0.6500
Validation  random nDCG: 0.4174

--> Improvement! Best nDCG: 0.6500
Epoch: 2, Batch: 288/289, Pred Mean: -0.0328, NDCG: 0.9197

Training nDCG: 0.6208
Training random nDCG: 0.3555

Batch (val): 41/41
Validation nDCG: 0.6942
Validation  random nDCG: 0.3532

--> Improvement! Best nDCG: 0.6942
Epoch: 3, Batch: 288/289, Pred Mean: 0.0913, NDCG: 0.9197

Training nDCG: 0.7425
Training random nDCG: 0.3764

Batch (val): 41/41
Validation nDCG: 0.7351
Validation  random nDCG: 0.3750

--> Improvement! Best nDCG: 0.7351
Epoch: 4, Batch: 288/289, Pred Mean: 0.2707, NDCG: 0.8772

Training nDCG: 0.7742
Training random nDCG: 0.3362

Batch (val): 41/41
Validation nDCG: 0.7402
Validation  random nDCG: 0.3528

--> Improvement! Best nDCG: 0.7402
Epoch: 5, Batch: 288/289, Pred Mean: 0.4092, NDCG: 0.8772

Training nDCG: 0.7980
Training random nDCG: 0.3678

Batch (val): 41/41
Validation nDCG: 0.7489
Validation  random nDCG: 0.3721

--> Improvement! Best nDCG: 0.7489
Epoch: 6, Batch: 288/289, Pred Mean: 0.5202, NDCG: 0.8772

Training nDCG: 0.8114
Training random nDCG: 0.3841

Batch (val): 41/41
Validation nDCG: 0.7565
Validation  random nDCG: 0.3527

--> Improvement! Best nDCG: 0.7565
Epoch: 7, Batch: 288/289, Pred Mean: 0.6176, NDCG: 0.8772

Training nDCG: 0.8238
Training random nDCG: 0.3801

Batch (val): 41/41
Validation nDCG: 0.7649
Validation  random nDCG: 0.3752

--> Improvement! Best nDCG: 0.7649
Epoch: 8, Batch: 288/289, Pred Mean: 0.7308, NDCG: 0.8772

Training nDCG: 0.8327
Training random nDCG: 0.3813

Batch (val): 41/41
Validation nDCG: 0.7835
Validation  random nDCG: 0.3632

--> Improvement! Best nDCG: 0.7835
Epoch: 9, Batch: 288/289, Pred Mean: 0.8606, NDCG: 0.8772

Training nDCG: 0.8412
Training random nDCG: 0.3649

Batch (val): 41/41
Validation nDCG: 0.7845
Validation  random nDCG: 0.3403

--> Improvement! Best nDCG: 0.7845
Epoch: 10, Batch: 288/289, Pred Mean: 0.9599, NDCG: 0.8772

Training nDCG: 0.8421
Training random nDCG: 0.3559

Batch (val): 41/41
Validation nDCG: 0.7833
Validation  random nDCG: 0.3872

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: 1.0890, NDCG: 0.9197

Training nDCG: 0.8478
Training random nDCG: 0.3351

Batch (val): 41/41
Validation nDCG: 0.7817
Validation  random nDCG: 0.3274

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: 1.2213, NDCG: 0.9197

Training nDCG: 0.8512
Training random nDCG: 0.3653

Batch (val): 41/41
Validation nDCG: 0.7753
Validation  random nDCG: 0.3148

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: 1.3081, NDCG: 0.9197

Training nDCG: 0.8569
Training random nDCG: 0.3704

Batch (val): 36/41

[I 2026-06-08 04:40:12,238] Trial 1 finished with value: 0.7844532311911712 and parameters: {'learning_rate': 0.00031965048909676227, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.8052175595109395.

Batch (val): 41/41
Validation nDCG: 0.7663
Validation  random nDCG: 0.3656

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 351.94 seconds

    Config:
    - learning_rate = 0.0011591192826342978
    - embedding_size = 16
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.4392, NDCG: 0.8772

Training nDCG: 0.6691
Training random nDCG: 0.3644

Batch (val): 41/41
Validation nDCG: 0.7731
Validation  random nDCG: 0.3525

--> Improvement! Best nDCG: 0.7731
Epoch: 2, Batch: 288/289, Pred Mean: 1.1088, NDCG: 0.8772

Training nDCG: 0.8003
Training random nDCG: 0.3680

Batch (val): 41/41
Validation nDCG: 0.7897
Validation  random nDCG: 0.3520

--> Improvement! Best nDCG: 0.7897
Epoch: 3, Batch: 288/289, Pred Mean: 1.1940, NDCG: 0.8503

Training nDCG: 0.8204
Training random nDCG: 0.3563

Batch (val): 41/41
Validation nDCG: 0.7966
Validation  random nDCG: 0.3628

--> Improvement! Best nDCG: 0.7966
Epoch: 4, Batch: 288/289, Pred Mean: 1.4095, NDCG: 0.6241

Training nDCG: 0.8334
Training random nDCG: 0.3322

Batch (val): 41/41
Validation nDCG: 0.7868
Validation  random nDCG: 0.3396

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.4392, NDCG: 0.8503

Training nDCG: 0.8569
Training random nDCG: 0.3583

Batch (val): 41/41
Validation nDCG: 0.7907
Validation  random nDCG: 0.4073

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.3730, NDCG: 0.8503

Training nDCG: 0.8617
Training random nDCG: 0.3486

Batch (val): 41/41
Validation nDCG: 0.7883
Validation  random nDCG: 0.3742

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.4279, NDCG: 0.9197

Training nDCG: 0.8714
Training random nDCG: 0.3640

Batch (val): 38/41

[I 2026-06-08 04:43:11,134] Trial 2 finished with value: 0.7966454281420703 and parameters: {'learning_rate': 0.0011591192826342978, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}. Best is trial 0 with value: 0.8052175595109395.

Batch (val): 41/41
Validation nDCG: 0.7662
Validation  random nDCG: 0.3864

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 178.86 seconds
Best hyperparameters: {'learning_rate': 0.0005401747599961397, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218

[I 2026-06-08 04:43:12,182] A new study created in memory with name: no-name-7b2fc9d8-ed98-4ed7-9fd0-4edf124cb066

Running study for llama unstructured with inference=True and isco=False

    Config:
    - learning_rate = 0.002090100453020921
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.1181, NDCG: 1.0000

Training nDCG: 0.6653
Training random nDCG: 0.3868

Batch (val): 41/41
Validation nDCG: 0.6732
Validation  random nDCG: 0.3574

--> Improvement! Best nDCG: 0.6732
Epoch: 2, Batch: 288/289, Pred Mean: 0.7715, NDCG: 0.7328

Training nDCG: 0.7695
Training random nDCG: 0.3849

Batch (val): 41/41
Validation nDCG: 0.6744
Validation  random nDCG: 0.3637

--> Improvement! Best nDCG: 0.6744
Epoch: 3, Batch: 288/289, Pred Mean: 0.9391, NDCG: 0.7328

Training nDCG: 0.7954
Training random nDCG: 0.3926

Batch (val): 41/41
Validation nDCG: 0.6902
Validation  random nDCG: 0.4250

--> Improvement! Best nDCG: 0.6902
Epoch: 4, Batch: 288/289, Pred Mean: 1.4415, NDCG: 0.7328

Training nDCG: 0.8094
Training random nDCG: 0.3997

Batch (val): 41/41
Validation nDCG: 0.6860
Validation  random nDCG: 0.3789

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.0837, NDCG: 1.0000

Training nDCG: 0.8129
Training random nDCG: 0.3919

Batch (val): 41/41
Validation nDCG: 0.6669
Validation  random nDCG: 0.3607

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.1192, NDCG: 1.0000

Training nDCG: 0.8157
Training random nDCG: 0.3835

Batch (val): 41/41
Validation nDCG: 0.6753
Validation  random nDCG: 0.3729

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.7166, NDCG: 1.0000

Training nDCG: 0.8151
Training random nDCG: 0.3912

Batch (val): 37/41

[I 2026-06-08 04:46:09,073] Trial 0 finished with value: 0.6901761110866906 and parameters: {'learning_rate': 0.002090100453020921, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.6901761110866906.

Batch (val): 41/41
Validation nDCG: 0.6747
Validation  random nDCG: 0.3296

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 176.85 seconds

    Config:
    - learning_rate = 0.0020378978896436442
    - embedding_size = 16
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.3010, NDCG: 0.8529

Training nDCG: 0.6512
Training random nDCG: 0.4057

Batch (val): 41/41
Validation nDCG: 0.6979
Validation  random nDCG: 0.3511

--> Improvement! Best nDCG: 0.6979
Epoch: 2, Batch: 288/289, Pred Mean: 1.0140, NDCG: 0.9060

Training nDCG: 0.7623
Training random nDCG: 0.4009

Batch (val): 41/41
Validation nDCG: 0.6809
Validation  random nDCG: 0.3509

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 1.2657, NDCG: 0.9060

Training nDCG: 0.7753
Training random nDCG: 0.4096

Batch (val): 41/41
Validation nDCG: 0.6797
Validation  random nDCG: 0.3515

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.4162, NDCG: 1.0000

Training nDCG: 0.7894
Training random nDCG: 0.4258

Batch (val): 41/41
Validation nDCG: 0.6830
Validation  random nDCG: 0.3743

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.5811, NDCG: 1.0000

Training nDCG: 0.7956
Training random nDCG: 0.3737

Batch (val): 41/41
Validation nDCG: 0.6854
Validation  random nDCG: 0.3083

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 129.72 seconds

[I 2026-06-08 04:48:18,817] Trial 1 finished with value: 0.6978600084855717 and parameters: {'learning_rate': 0.0020378978896436442, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}. Best is trial 1 with value: 0.6978600084855717.

    Config:
    - learning_rate = 0.0015217055649598714
    - embedding_size = 32
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.9916, NDCG: 0.9060

Training nDCG: 0.7037
Training random nDCG: 0.4180

Batch (val): 41/41
Validation nDCG: 0.6583
Validation  random nDCG: 0.3428

--> Improvement! Best nDCG: 0.6583
Epoch: 2, Batch: 288/289, Pred Mean: 1.1975, NDCG: 0.7328

Training nDCG: 0.7635
Training random nDCG: 0.4028

Batch (val): 41/41
Validation nDCG: 0.6975
Validation  random nDCG: 0.3328

--> Improvement! Best nDCG: 0.6975
Epoch: 3, Batch: 288/289, Pred Mean: 1.2617, NDCG: 0.7328

Training nDCG: 0.7785
Training random nDCG: 0.4149

Batch (val): 41/41
Validation nDCG: 0.6752
Validation  random nDCG: 0.2897

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.4320, NDCG: 0.7328

Training nDCG: 0.7914
Training random nDCG: 0.4092

Batch (val): 41/41
Validation nDCG: 0.6883
Validation  random nDCG: 0.3668

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 1.0229, NDCG: 0.9675

Training nDCG: 0.8098
Training random nDCG: 0.4079

Batch (val): 41/41
Validation nDCG: 0.6846
Validation  random nDCG: 0.3950

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 1.3204, NDCG: 0.9675

Training nDCG: 0.7916
Training random nDCG: 0.3990

Batch (val): 39/41

[I 2026-06-08 04:50:51,801] Trial 2 finished with value: 0.6975295441174688 and parameters: {'learning_rate': 0.0015217055649598714, 'embedding_size': 32, 'pooling_method': 'mean', 'heads': 8}. Best is trial 1 with value: 0.6978600084855717.

Batch (val): 41/41
Validation nDCG: 0.6598
Validation  random nDCG: 0.3769

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 152.95 seconds
Best hyperparameters: {'learning_rate': 0.0020378978896436442, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860

[I 2026-06-08 04:50:53,172] A new study created in memory with name: no-name-ed6e9d93-9983-433c-9e4a-075365cd144d

Running study for qwen structured with inference=False and isco=True

    Config:
    - learning_rate = 0.0019080848495433146
    - embedding_size = 16
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -1.0069, NDCG: 0.6105

Training nDCG: 0.6605
Training random nDCG: 0.3550

Batch (val): 41/41
Validation nDCG: 0.7727
Validation  random nDCG: 0.3730

--> Improvement! Best nDCG: 0.7727
Epoch: 2, Batch: 288/289, Pred Mean: -0.4394, NDCG: 0.6508

Training nDCG: 0.7875
Training random nDCG: 0.3664

Batch (val): 41/41
Validation nDCG: 0.7526
Validation  random nDCG: 0.3367

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.7306, NDCG: 0.6508

Training nDCG: 0.7841
Training random nDCG: 0.3414

Batch (val): 41/41
Validation nDCG: 0.7133
Validation  random nDCG: 0.3230

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.1880, NDCG: 0.7654

Training nDCG: 0.7958
Training random nDCG: 0.3416

Batch (val): 41/41
Validation nDCG: 0.7516
Validation  random nDCG: 0.3668

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.7771, NDCG: 0.7654

Training nDCG: 0.8180
Training random nDCG: 0.3426

Batch (val): 41/41

[I 2026-06-08 04:59:53,279] Trial 0 finished with value: 0.7726664058294559 and parameters: {'learning_rate': 0.0019080848495433146, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.7726664058294559.

Validation nDCG: 0.7505
Validation  random nDCG: 0.3366

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 540.07 seconds

    Config:
    - learning_rate = 0.009396292002507295
    - embedding_size = 16
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.2811, NDCG: 0.6173

Training nDCG: 0.7701
Training random nDCG: 0.3385

Batch (val): 41/41
Validation nDCG: 0.7661
Validation  random nDCG: 0.3351

--> Improvement! Best nDCG: 0.7661
Epoch: 2, Batch: 288/289, Pred Mean: 0.3047, NDCG: 0.4693

Training nDCG: 0.7782
Training random nDCG: 0.3445

Batch (val): 41/41
Validation nDCG: 0.7932
Validation  random nDCG: 0.3617

--> Improvement! Best nDCG: 0.7932
Epoch: 3, Batch: 288/289, Pred Mean: 0.2232, NDCG: 0.4693

Training nDCG: 0.7831
Training random nDCG: 0.3508

Batch (val): 41/41
Validation nDCG: 0.7873
Validation  random nDCG: 0.3894

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.4469, NDCG: 0.6173

Training nDCG: 0.7901
Training random nDCG: 0.3764

Batch (val): 41/41
Validation nDCG: 0.7769
Validation  random nDCG: 0.3770

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.5118, NDCG: 0.4693

Training nDCG: 0.7814
Training random nDCG: 0.3458

Batch (val): 41/41
Validation nDCG: 0.7588
Validation  random nDCG: 0.3539

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.5248, NDCG: 0.4693

Training nDCG: 0.7913
Training random nDCG: 0.3516

Batch (val): 41/41

[I 2026-06-08 05:10:21,346] Trial 1 finished with value: 0.7932136576092838 and parameters: {'learning_rate': 0.009396292002507295, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 4}. Best is trial 1 with value: 0.7932136576092838.

Validation nDCG: 0.7671
Validation  random nDCG: 0.3014

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 628.03 seconds

    Config:
    - learning_rate = 0.005862325979909419
    - embedding_size = 32
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.4225, NDCG: 0.6714

Training nDCG: 0.7455
Training random nDCG: 0.3429

Batch (val): 41/41
Validation nDCG: 0.7472
Validation  random nDCG: 0.3679

--> Improvement! Best nDCG: 0.7472
Epoch: 2, Batch: 288/289, Pred Mean: -4.1806, NDCG: 0.4693

Training nDCG: 0.7856
Training random nDCG: 0.3558

Batch (val): 41/41
Validation nDCG: 0.7922
Validation  random nDCG: 0.4114

--> Improvement! Best nDCG: 0.7922
Epoch: 3, Batch: 288/289, Pred Mean: -0.2010, NDCG: 0.7654

Training nDCG: 0.7854
Training random nDCG: 0.3524

Batch (val): 41/41
Validation nDCG: 0.7626
Validation  random nDCG: 0.4164

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.7442, NDCG: 0.4693

Training nDCG: 0.7836
Training random nDCG: 0.3441

Batch (val): 41/41
Validation nDCG: 0.7839
Validation  random nDCG: 0.3763

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.7244, NDCG: 0.7039

Training nDCG: 0.7833
Training random nDCG: 0.3566

Batch (val): 41/41
Validation nDCG: 0.7675
Validation  random nDCG: 0.3507

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.3780, NDCG: 0.6508

Training nDCG: 0.7865
Training random nDCG: 0.3534

Batch (val): 41/41

[I 2026-06-08 05:20:31,389] Trial 2 finished with value: 0.7922007006973816 and parameters: {'learning_rate': 0.005862325979909419, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 4}. Best is trial 1 with value: 0.7932136576092838.

Validation nDCG: 0.7624
Validation  random nDCG: 0.3455

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 610.01 seconds
Best hyperparameters: {'learning_rate': 0.009396292002507295, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214

[I 2026-06-08 05:20:33,001] A new study created in memory with name: no-name-d017059a-7637-469b-befe-ef27044e2174

Running study for qwen semi-structured with inference=False and isco=True

    Config:
    - learning_rate = 0.0037955843965978026
    - embedding_size = 64
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.1548, NDCG: 0.6364

Training nDCG: 0.7878
Training random nDCG: 0.3726

Batch (val): 41/41
Validation nDCG: 0.7752
Validation  random nDCG: 0.4024

--> Improvement! Best nDCG: 0.7752
Epoch: 2, Batch: 288/289, Pred Mean: 0.0512, NDCG: 0.7654

Training nDCG: 0.7934
Training random nDCG: 0.3496

Batch (val): 41/41
Validation nDCG: 0.7713
Validation  random nDCG: 0.3816

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.2168, NDCG: 0.7654

Training nDCG: 0.7980
Training random nDCG: 0.3415

Batch (val): 41/41
Validation nDCG: 0.7547
Validation  random nDCG: 0.3123

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.3261, NDCG: 0.8520

Training nDCG: 0.7884
Training random nDCG: 0.3575

Batch (val): 41/41
Validation nDCG: 0.7575
Validation  random nDCG: 0.3254

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.3971, NDCG: 0.7845

Training nDCG: 0.7995
Training random nDCG: 0.3593

Batch (val): 40/41

[I 2026-06-08 05:29:39,970] Trial 0 finished with value: 0.7751944006201171 and parameters: {'learning_rate': 0.0037955843965978026, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 8}. Best is trial 0 with value: 0.7751944006201171.

Batch (val): 41/41
Validation nDCG: 0.7664
Validation  random nDCG: 0.3494

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 546.91 seconds

    Config:
    - learning_rate = 0.00896451487332896
    - embedding_size = 64
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.7346, NDCG: 0.7654

Training nDCG: 0.7762
Training random nDCG: 0.3354

Batch (val): 41/41
Validation nDCG: 0.7795
Validation  random nDCG: 0.2956

--> Improvement! Best nDCG: 0.7795
Epoch: 2, Batch: 288/289, Pred Mean: -4.1815, NDCG: 0.6049

Training nDCG: 0.7898
Training random nDCG: 0.3400

Batch (val): 41/41
Validation nDCG: 0.7692
Validation  random nDCG: 0.3448

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -3.0007, NDCG: 0.4693

Training nDCG: 0.7854
Training random nDCG: 0.3375

Batch (val): 41/41
Validation nDCG: 0.7910
Validation  random nDCG: 0.3702

--> Improvement! Best nDCG: 0.7910
Epoch: 4, Batch: 288/289, Pred Mean: -3.9392, NDCG: 0.6173

Training nDCG: 0.7936
Training random nDCG: 0.3470

Batch (val): 41/41
Validation nDCG: 0.7857
Validation  random nDCG: 0.3415

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -2.3662, NDCG: 0.9010

Training nDCG: 0.8014
Training random nDCG: 0.3557

Batch (val): 41/41
Validation nDCG: 0.7710
Validation  random nDCG: 0.3799

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -1.4790, NDCG: 0.6257

Training nDCG: 0.7988
Training random nDCG: 0.3632

Batch (val): 41/41
Validation nDCG: 0.7709
Validation  random nDCG: 0.3734

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: 11.7744, NDCG: 0.6105

Training nDCG: 0.8052
Training random nDCG: 0.3520

Batch (val): 41/41
Validation nDCG: 0.7706
Validation  random nDCG: 0.3010

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 810.61 seconds

[I 2026-06-08 05:43:10,609] Trial 1 finished with value: 0.7909872055793752 and parameters: {'learning_rate': 0.00896451487332896, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.7909872055793752.

    Config:
    - learning_rate = 0.0005002612297369284
    - embedding_size = 8
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -1.1238, NDCG: 0.4367

Training nDCG: 0.4225
Training random nDCG: 0.3581

Batch (val): 41/41
Validation nDCG: 0.6161
Validation  random nDCG: 0.3227

--> Improvement! Best nDCG: 0.6161
Epoch: 2, Batch: 288/289, Pred Mean: -0.4352, NDCG: 0.6508

Training nDCG: 0.6193
Training random nDCG: 0.3516

Batch (val): 41/41
Validation nDCG: 0.7055
Validation  random nDCG: 0.3079

--> Improvement! Best nDCG: 0.7055
Epoch: 3, Batch: 288/289, Pred Mean: -1.1745, NDCG: 0.9134

Training nDCG: 0.7452
Training random nDCG: 0.3356

Batch (val): 41/41
Validation nDCG: 0.7621
Validation  random nDCG: 0.3481

--> Improvement! Best nDCG: 0.7621
Epoch: 4, Batch: 288/289, Pred Mean: -1.3453, NDCG: 0.7462

Training nDCG: 0.7958
Training random nDCG: 0.3892

Batch (val): 41/41
Validation nDCG: 0.7600
Validation  random nDCG: 0.3543

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.4537, NDCG: 0.4693

Training nDCG: 0.8110
Training random nDCG: 0.3317

Batch (val): 41/41
Validation nDCG: 0.7734
Validation  random nDCG: 0.3396

--> Improvement! Best nDCG: 0.7734
Epoch: 6, Batch: 288/289, Pred Mean: -1.6698, NDCG: 0.4693

Training nDCG: 0.8195
Training random nDCG: 0.3856

Batch (val): 41/41
Validation nDCG: 0.7313
Validation  random nDCG: 0.3689

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -2.0180, NDCG: 0.4693

Training nDCG: 0.8301
Training random nDCG: 0.3693

Batch (val): 41/41
Validation nDCG: 0.7879
Validation  random nDCG: 0.3077

--> Improvement! Best nDCG: 0.7879
Epoch: 8, Batch: 288/289, Pred Mean: -2.1138, NDCG: 0.4693

Training nDCG: 0.8385
Training random nDCG: 0.3683

Batch (val): 41/41
Validation nDCG: 0.7832
Validation  random nDCG: 0.3376

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: -2.1912, NDCG: 0.4693

Training nDCG: 0.8449
Training random nDCG: 0.3730

Batch (val): 41/41
Validation nDCG: 0.7566
Validation  random nDCG: 0.3848

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: -1.9756, NDCG: 0.4693

Training nDCG: 0.8545
Training random nDCG: 0.3432

Batch (val): 41/41
Validation nDCG: 0.7097
Validation  random nDCG: 0.3830

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: -1.9700, NDCG: 0.7039

Training nDCG: 0.8620
Training random nDCG: 0.3474

Batch (val): 40/41

[I 2026-06-08 06:03:52,033] Trial 2 finished with value: 0.7879196905687519 and parameters: {'learning_rate': 0.0005002612297369284, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 8}. Best is trial 1 with value: 0.7909872055793752.

Batch (val): 41/41
Validation nDCG: 0.7014
Validation  random nDCG: 0.3362

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 1241.39 seconds
Best hyperparameters: {'learning_rate': 0.00896451487332896, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987

[I 2026-06-08 06:03:54,771] A new study created in memory with name: no-name-ddd569ac-053d-4457-8e64-9febd569f1f6

Running study for qwen unstructured with inference=False and isco=True

    Config:
    - learning_rate = 0.00020473641286100416
    - embedding_size = 8
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -4.1975, NDCG: 0.6257

Training nDCG: 0.3761
Training random nDCG: 0.3527

Batch (val): 41/41
Validation nDCG: 0.3302
Validation  random nDCG: 0.3713

--> Improvement! Best nDCG: 0.3302
Epoch: 2, Batch: 288/289, Pred Mean: -3.8715, NDCG: 0.6364

Training nDCG: 0.4157
Training random nDCG: 0.3495

Batch (val): 41/41
Validation nDCG: 0.3280
Validation  random nDCG: 0.3596

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -3.0403, NDCG: 0.6364

Training nDCG: 0.4642
Training random nDCG: 0.3549

Batch (val): 41/41
Validation nDCG: 0.3466
Validation  random nDCG: 0.3886

--> Improvement! Best nDCG: 0.3466
Epoch: 4, Batch: 288/289, Pred Mean: -3.4015, NDCG: 0.1564

Training nDCG: 0.4998
Training random nDCG: 0.3598

Batch (val): 41/41
Validation nDCG: 0.4249
Validation  random nDCG: 0.3577

--> Improvement! Best nDCG: 0.4249
Epoch: 5, Batch: 288/289, Pred Mean: -2.8148, NDCG: 0.4632

Training nDCG: 0.5308
Training random nDCG: 0.3412

Batch (val): 41/41
Validation nDCG: 0.3758
Validation  random nDCG: 0.4073

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -2.4666, NDCG: 0.4982

Training nDCG: 0.5599
Training random nDCG: 0.3545

Batch (val): 41/41
Validation nDCG: 0.4509
Validation  random nDCG: 0.4165

--> Improvement! Best nDCG: 0.4509
Epoch: 7, Batch: 288/289, Pred Mean: -1.2758, NDCG: 0.3836

Training nDCG: 0.5539
Training random nDCG: 0.3542

Batch (val): 41/41
Validation nDCG: 0.4507
Validation  random nDCG: 0.3629

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: -1.5680, NDCG: 0.2961

Training nDCG: 0.6041
Training random nDCG: 0.3363

Batch (val): 41/41
Validation nDCG: 0.5452
Validation  random nDCG: 0.3138

--> Improvement! Best nDCG: 0.5452
Epoch: 9, Batch: 288/289, Pred Mean: -0.1830, NDCG: 0.4693

Training nDCG: 0.6091
Training random nDCG: 0.3510

Batch (val): 41/41
Validation nDCG: 0.4146
Validation  random nDCG: 0.3530

--> No improvement. Patience: 1/4
Epoch: 10, Batch: 288/289, Pred Mean: -1.7069, NDCG: 0.0000

Training nDCG: 0.6262
Training random nDCG: 0.3498

Batch (val): 41/41
Validation nDCG: 0.6800
Validation  random nDCG: 0.4060

--> Improvement! Best nDCG: 0.6800
Epoch: 11, Batch: 288/289, Pred Mean: 0.2663, NDCG: 0.2961

Training nDCG: 0.6490
Training random nDCG: 0.3399

Batch (val): 41/41
Validation nDCG: 0.3751
Validation  random nDCG: 0.2832

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: -0.5094, NDCG: 0.4693

Training nDCG: 0.6709
Training random nDCG: 0.3739

Batch (val): 41/41
Validation nDCG: 0.3044
Validation  random nDCG: 0.4174

--> No improvement. Patience: 2/4
Epoch: 13, Batch: 288/289, Pred Mean: -0.8790, NDCG: 0.4693

Training nDCG: 0.6961
Training random nDCG: 0.3532

Batch (val): 41/41
Validation nDCG: 0.5539
Validation  random nDCG: 0.3705

--> No improvement. Patience: 3/4
Epoch: 14, Batch: 288/289, Pred Mean: -0.7098, NDCG: 0.6364

Training nDCG: 0.7229
Training random nDCG: 0.3560

Batch (val): 40/41

[I 2026-06-08 06:47:22,559] Trial 0 finished with value: 0.680028146134672 and parameters: {'learning_rate': 0.00020473641286100416, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.680028146134672.

Batch (val): 41/41
Validation nDCG: 0.6036
Validation  random nDCG: 0.3197

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 14
Training for 15 epochs took 2607.72 seconds

    Config:
    - learning_rate = 0.007983750506348555
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -2.9549, NDCG: 0.4693

Training nDCG: 0.7626
Training random nDCG: 0.3546

Batch (val): 41/41
Validation nDCG: 0.7739
Validation  random nDCG: 0.3392

--> Improvement! Best nDCG: 0.7739
Epoch: 2, Batch: 288/289, Pred Mean: -3.3427, NDCG: 0.4693

Training nDCG: 0.7869
Training random nDCG: 0.3340

Batch (val): 41/41
Validation nDCG: 0.7637
Validation  random nDCG: 0.3848

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -3.2984, NDCG: 0.6714

Training nDCG: 0.7884
Training random nDCG: 0.3524

Batch (val): 41/41
Validation nDCG: 0.7439
Validation  random nDCG: 0.3159

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -3.9976, NDCG: 0.7921

Training nDCG: 0.7998
Training random nDCG: 0.3624

Batch (val): 41/41
Validation nDCG: 0.7583
Validation  random nDCG: 0.3372

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -6.5120, NDCG: 0.4693

Training nDCG: 0.8029
Training random nDCG: 0.3633

Batch (val): 40/41

[I 2026-06-08 07:02:38,546] Trial 1 finished with value: 0.7739032758811878 and parameters: {'learning_rate': 0.007983750506348555, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.7739032758811878.

Batch (val): 41/41
Validation nDCG: 0.7631
Validation  random nDCG: 0.3244

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 915.94 seconds

    Config:
    - learning_rate = 0.0021985891605534485
    - embedding_size = 128
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.1381, NDCG: 0.4693

Training nDCG: 0.7537
Training random nDCG: 0.3401

Batch (val): 41/41
Validation nDCG: 0.7636
Validation  random nDCG: 0.3605

--> Improvement! Best nDCG: 0.7636
Epoch: 2, Batch: 288/289, Pred Mean: 0.1272, NDCG: 0.4693

Training nDCG: 0.7871
Training random nDCG: 0.3470

Batch (val): 41/41
Validation nDCG: 0.7762
Validation  random nDCG: 0.3777

--> Improvement! Best nDCG: 0.7762
Epoch: 3, Batch: 288/289, Pred Mean: -0.0744, NDCG: 0.6049

Training nDCG: 0.7932
Training random nDCG: 0.3548

Batch (val): 41/41
Validation nDCG: 0.7723
Validation  random nDCG: 0.2894

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.4420, NDCG: 0.7039

Training nDCG: 0.7999
Training random nDCG: 0.3485

Batch (val): 41/41
Validation nDCG: 0.7669
Validation  random nDCG: 0.3499

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.6513, NDCG: 0.7039

Training nDCG: 0.7987
Training random nDCG: 0.3578

Batch (val): 41/41
Validation nDCG: 0.7543
Validation  random nDCG: 0.3492

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.8903, NDCG: 0.7654

Training nDCG: 0.7999
Training random nDCG: 0.3603

Batch (val): 41/41
Validation nDCG: 0.7530
Validation  random nDCG: 0.3613

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 1147.32 seconds

[I 2026-06-08 07:21:45,910] Trial 2 finished with value: 0.7761690546380654 and parameters: {'learning_rate': 0.0021985891605534485, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 4}. Best is trial 2 with value: 0.7761690546380654.

Best hyperparameters: {'learning_rate': 0.0021985891605534485, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169

[I 2026-06-08 07:21:47,387] A new study created in memory with name: no-name-7f74eeb7-8db6-4e28-92c3-75ae9c787b49

Running study for gemma structured with inference=False and isco=True

    Config:
    - learning_rate = 0.00010531969924959433
    - embedding_size = 8
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -2.3852, NDCG: 0.7654

Training nDCG: 0.6189
Training random nDCG: 0.3445

Batch (val): 41/41
Validation nDCG: 0.7693
Validation  random nDCG: 0.3619

--> Improvement! Best nDCG: 0.7693
Epoch: 2, Batch: 288/289, Pred Mean: -55.8461, NDCG: 0.5307

Training nDCG: 0.6946
Training random nDCG: 0.3463

Batch (val): 41/41
Validation nDCG: 0.4581
Validation  random nDCG: 0.3917

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 3.1555, NDCG: 0.4693

Training nDCG: 0.3311
Training random nDCG: 0.3415

Batch (val): 41/41
Validation nDCG: 0.2294
Validation  random nDCG: 0.3673

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.8476, NDCG: 0.4525

Training nDCG: 0.3281
Training random nDCG: 0.3433

Batch (val): 41/41
Validation nDCG: 0.5559
Validation  random nDCG: 0.3590

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.0621, NDCG: 0.4693

Training nDCG: 0.7475
Training random nDCG: 0.3490

Batch (val): 41/41

[I 2026-06-08 07:29:41,907] Trial 0 finished with value: 0.769258818976191 and parameters: {'learning_rate': 0.00010531969924959433, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.769258818976191.

Validation nDCG: 0.7377
Validation  random nDCG: 0.3837

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 474.46 seconds

    Config:
    - learning_rate = 0.005491171314353858
    - embedding_size = 64
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.0685, NDCG: 0.4693

Training nDCG: 0.7756
Training random nDCG: 0.3427

Batch (val): 41/41
Validation nDCG: 0.7940
Validation  random nDCG: 0.3756

--> Improvement! Best nDCG: 0.7940
Epoch: 2, Batch: 288/289, Pred Mean: -0.3248, NDCG: 0.6714

Training nDCG: 0.7939
Training random nDCG: 0.3481

Batch (val): 41/41
Validation nDCG: 0.7607
Validation  random nDCG: 0.3282

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.2556, NDCG: 0.6105

Training nDCG: 0.7947
Training random nDCG: 0.3604

Batch (val): 41/41
Validation nDCG: 0.8051
Validation  random nDCG: 0.3859

--> Improvement! Best nDCG: 0.8051
Epoch: 4, Batch: 288/289, Pred Mean: -0.7431, NDCG: 0.6173

Training nDCG: 0.7898
Training random nDCG: 0.3641

Batch (val): 41/41
Validation nDCG: 0.7902
Validation  random nDCG: 0.3852

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.3925, NDCG: 0.4693

Training nDCG: 0.7957
Training random nDCG: 0.3403

Batch (val): 41/41
Validation nDCG: 0.7923
Validation  random nDCG: 0.3879

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.4122, NDCG: 0.4693

Training nDCG: 0.7907
Training random nDCG: 0.3420

Batch (val): 41/41
Validation nDCG: 0.7928
Validation  random nDCG: 0.3741

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: -0.4234, NDCG: 0.6105

Training nDCG: 0.7949
Training random nDCG: 0.3680

Batch (val): 41/41

[I 2026-06-08 07:40:53,208] Trial 1 finished with value: 0.8050984585721089 and parameters: {'learning_rate': 0.005491171314353858, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 2}. Best is trial 1 with value: 0.8050984585721089.

Validation nDCG: 0.7881
Validation  random nDCG: 0.4434

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 671.27 seconds

    Config:
    - learning_rate = 0.0006218227074760943
    - embedding_size = 64
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.3002, NDCG: 0.4693

Training nDCG: 0.7381
Training random nDCG: 0.3469

Batch (val): 41/41
Validation nDCG: 0.7602
Validation  random nDCG: 0.3881

--> Improvement! Best nDCG: 0.7602
Epoch: 2, Batch: 288/289, Pred Mean: -0.4130, NDCG: 0.6508

Training nDCG: 0.7925
Training random nDCG: 0.3433

Batch (val): 41/41
Validation nDCG: 0.7641
Validation  random nDCG: 0.3668

--> Improvement! Best nDCG: 0.7641
Epoch: 3, Batch: 288/289, Pred Mean: -0.0756, NDCG: 0.4693

Training nDCG: 0.7927
Training random nDCG: 0.3564

Batch (val): 41/41
Validation nDCG: 0.7727
Validation  random nDCG: 0.3449

--> Improvement! Best nDCG: 0.7727
Epoch: 4, Batch: 288/289, Pred Mean: -0.7317, NDCG: 0.8452

Training nDCG: 0.7991
Training random nDCG: 0.3457

Batch (val): 41/41
Validation nDCG: 0.7695
Validation  random nDCG: 0.3851

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.2017, NDCG: 0.7654

Training nDCG: 0.8101
Training random nDCG: 0.3504

Batch (val): 41/41
Validation nDCG: 0.7703
Validation  random nDCG: 0.4022

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -1.5068, NDCG: 0.6173

Training nDCG: 0.8166
Training random nDCG: 0.3903

Batch (val): 41/41
Validation nDCG: 0.7853
Validation  random nDCG: 0.3322

--> Improvement! Best nDCG: 0.7853
Epoch: 7, Batch: 288/289, Pred Mean: -2.0648, NDCG: 0.6173

Training nDCG: 0.8183
Training random nDCG: 0.3624

Batch (val): 41/41
Validation nDCG: 0.7577
Validation  random nDCG: 0.4235

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: -2.4433, NDCG: 0.7654

Training nDCG: 0.8284
Training random nDCG: 0.3381

Batch (val): 41/41
Validation nDCG: 0.7664
Validation  random nDCG: 0.3419

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: -3.3497, NDCG: 0.7654

Training nDCG: 0.8362
Training random nDCG: 0.3679

Batch (val): 41/41
Validation nDCG: 0.7967
Validation  random nDCG: 0.3888

--> Improvement! Best nDCG: 0.7967
Epoch: 10, Batch: 288/289, Pred Mean: -3.7170, NDCG: 0.7654

Training nDCG: 0.8472
Training random nDCG: 0.3722

Batch (val): 41/41
Validation nDCG: 0.7784
Validation  random nDCG: 0.2913

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: -4.1077, NDCG: 0.7654

Training nDCG: 0.8508
Training random nDCG: 0.3669

Batch (val): 41/41
Validation nDCG: 0.7885
Validation  random nDCG: 0.3263

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: -4.9006, NDCG: 0.7654

Training nDCG: 0.8554
Training random nDCG: 0.3687

Batch (val): 41/41
Validation nDCG: 0.7919
Validation  random nDCG: 0.3665

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: -5.3326, NDCG: 0.7654

Training nDCG: 0.8705
Training random nDCG: 0.3444

Batch (val): 41/41

[I 2026-06-08 08:01:30,709] Trial 2 finished with value: 0.7966668864688166 and parameters: {'learning_rate': 0.0006218227074760943, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 4}. Best is trial 1 with value: 0.8050984585721089.

Validation nDCG: 0.7853
Validation  random nDCG: 0.3006

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 1237.47 seconds
Best hyperparameters: {'learning_rate': 0.005491171314353858, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098

[I 2026-06-08 08:01:32,258] A new study created in memory with name: no-name-11944f2f-3bce-4224-a2af-2c2d3c27f241

Running study for gemma semi-structured with inference=False and isco=True

    Config:
    - learning_rate = 0.009825194373953664
    - embedding_size = 64
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.8275, NDCG: 0.6257

Training nDCG: 0.7863
Training random nDCG: 0.3263

Batch (val): 41/41
Validation nDCG: 0.7661
Validation  random nDCG: 0.4007

--> Improvement! Best nDCG: 0.7661
Epoch: 2, Batch: 288/289, Pred Mean: -0.8714, NDCG: 0.4693

Training nDCG: 0.7950
Training random nDCG: 0.3585

Batch (val): 41/41
Validation nDCG: 0.7722
Validation  random nDCG: 0.3403

--> Improvement! Best nDCG: 0.7722
Epoch: 3, Batch: 288/289, Pred Mean: -0.7195, NDCG: 0.6257

Training nDCG: 0.8033
Training random nDCG: 0.3654

Batch (val): 41/41
Validation nDCG: 0.7903
Validation  random nDCG: 0.3626

--> Improvement! Best nDCG: 0.7903
Epoch: 4, Batch: 288/289, Pred Mean: -1.3577, NDCG: 0.6049

Training nDCG: 0.7960
Training random nDCG: 0.3406

Batch (val): 41/41
Validation nDCG: 0.7785
Validation  random nDCG: 0.3814

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.9418, NDCG: 0.6049

Training nDCG: 0.7949
Training random nDCG: 0.3639

Batch (val): 41/41
Validation nDCG: 0.7699
Validation  random nDCG: 0.3085

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -2.5546, NDCG: 0.6173

Training nDCG: 0.7988
Training random nDCG: 0.3619

Batch (val): 41/41
Validation nDCG: 0.7783
Validation  random nDCG: 0.3702

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: -2.5506, NDCG: 0.6364

Training nDCG: 0.7929
Training random nDCG: 0.3391

Batch (val): 40/41

[I 2026-06-08 08:14:35,868] Trial 0 finished with value: 0.7903340662390905 and parameters: {'learning_rate': 0.009825194373953664, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.7903340662390905.

Batch (val): 41/41
Validation nDCG: 0.7713
Validation  random nDCG: 0.3338

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 783.56 seconds

    Config:
    - learning_rate = 0.0006508976502061023
    - embedding_size = 64
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.2766, NDCG: 0.7845

Training nDCG: 0.7556
Training random nDCG: 0.3783

Batch (val): 41/41
Validation nDCG: 0.7885
Validation  random nDCG: 0.4166

--> Improvement! Best nDCG: 0.7885
Epoch: 2, Batch: 288/289, Pred Mean: 0.3679, NDCG: 0.8072

Training nDCG: 0.7944
Training random nDCG: 0.3547

Batch (val): 41/41
Validation nDCG: 0.7969
Validation  random nDCG: 0.3214

--> Improvement! Best nDCG: 0.7969
Epoch: 3, Batch: 288/289, Pred Mean: 0.3828, NDCG: 0.6364

Training nDCG: 0.7885
Training random nDCG: 0.3632

Batch (val): 41/41
Validation nDCG: 0.7740
Validation  random nDCG: 0.3020

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1989, NDCG: 0.8278

Training nDCG: 0.7902
Training random nDCG: 0.3379

Batch (val): 41/41
Validation nDCG: 0.7634
Validation  random nDCG: 0.3620

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.2273, NDCG: 0.9218

Training nDCG: 0.7961
Training random nDCG: 0.3600

Batch (val): 41/41
Validation nDCG: 0.7626
Validation  random nDCG: 0.3136

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.1692, NDCG: 0.9010

Training nDCG: 0.8020
Training random nDCG: 0.3726

Batch (val): 41/41

[I 2026-06-08 08:25:45,524] Trial 1 finished with value: 0.7968503521924367 and parameters: {'learning_rate': 0.0006508976502061023, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 8}. Best is trial 1 with value: 0.7968503521924367.

Validation nDCG: 0.7700
Validation  random nDCG: 0.3581

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 669.62 seconds

    Config:
    - learning_rate = 0.0021061986603807927
    - embedding_size = 64
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.3862, NDCG: 0.7614

Training nDCG: 0.7206
Training random nDCG: 0.3530

Batch (val): 41/41
Validation nDCG: 0.7810
Validation  random nDCG: 0.3371

--> Improvement! Best nDCG: 0.7810
Epoch: 2, Batch: 288/289, Pred Mean: -1.5571, NDCG: 0.6105

Training nDCG: 0.7738
Training random nDCG: 0.3286

Batch (val): 41/41
Validation nDCG: 0.7473
Validation  random nDCG: 0.2755

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -1.3244, NDCG: 0.4693

Training nDCG: 0.7906
Training random nDCG: 0.3483

Batch (val): 41/41
Validation nDCG: 0.7805
Validation  random nDCG: 0.3617

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.0613, NDCG: 0.7721

Training nDCG: 0.7918
Training random nDCG: 0.3246

Batch (val): 41/41
Validation nDCG: 0.7574
Validation  random nDCG: 0.3358

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -2.5624, NDCG: 0.7777

Training nDCG: 0.7931
Training random nDCG: 0.3580

Batch (val): 40/41

[I 2026-06-08 08:35:00,384] Trial 2 finished with value: 0.7809853847487825 and parameters: {'learning_rate': 0.0021061986603807927, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 4}. Best is trial 1 with value: 0.7968503521924367.

Batch (val): 41/41
Validation nDCG: 0.7805
Validation  random nDCG: 0.3601

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 554.83 seconds
Best hyperparameters: {'learning_rate': 0.0006508976502061023, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850

[I 2026-06-08 08:35:03,525] A new study created in memory with name: no-name-db055d72-1eaf-4c3e-9452-aa60780dd543

Running study for gemma unstructured with inference=False and isco=True

    Config:
    - learning_rate = 0.0086619134937933
    - embedding_size = 32
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.7885, NDCG: 0.4693

Training nDCG: 0.7405
Training random nDCG: 0.3377

Batch (val): 41/41
Validation nDCG: 0.7655
Validation  random nDCG: 0.4137

--> Improvement! Best nDCG: 0.7655
Epoch: 2, Batch: 288/289, Pred Mean: 2.0935, NDCG: 0.6049

Training nDCG: 0.8023
Training random nDCG: 0.3387

Batch (val): 41/41
Validation nDCG: 0.7355
Validation  random nDCG: 0.3768

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -2.3506, NDCG: 0.6364

Training nDCG: 0.7918
Training random nDCG: 0.3596

Batch (val): 41/41
Validation nDCG: 0.7430
Validation  random nDCG: 0.3726

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -2.8746, NDCG: 0.6049

Training nDCG: 0.7988
Training random nDCG: 0.3461

Batch (val): 41/41
Validation nDCG: 0.7803
Validation  random nDCG: 0.3705

--> Improvement! Best nDCG: 0.7803
Epoch: 5, Batch: 288/289, Pred Mean: -2.3296, NDCG: 0.4693

Training nDCG: 0.7861
Training random nDCG: 0.3470

Batch (val): 41/41
Validation nDCG: 0.7777
Validation  random nDCG: 0.4069

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -6.2167, NDCG: 0.4693

Training nDCG: 0.7995
Training random nDCG: 0.3503

Batch (val): 41/41
Validation nDCG: 0.7824
Validation  random nDCG: 0.3550

--> Improvement! Best nDCG: 0.7824
Epoch: 7, Batch: 288/289, Pred Mean: -6.3432, NDCG: 0.4693

Training nDCG: 0.8041
Training random nDCG: 0.3548

Batch (val): 41/41
Validation nDCG: 0.7872
Validation  random nDCG: 0.3792

--> Improvement! Best nDCG: 0.7872
Epoch: 8, Batch: 288/289, Pred Mean: -6.1672, NDCG: 0.4693

Training nDCG: 0.7949
Training random nDCG: 0.3667

Batch (val): 41/41
Validation nDCG: 0.7666
Validation  random nDCG: 0.3358

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: -6.1251, NDCG: 0.4693

Training nDCG: 0.7957
Training random nDCG: 0.3456

Batch (val): 41/41
Validation nDCG: 0.7763
Validation  random nDCG: 0.3251

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: -7.4966, NDCG: 0.4693

Training nDCG: 0.8004
Training random nDCG: 0.3424

Batch (val): 41/41
Validation nDCG: 0.7849
Validation  random nDCG: 0.3538

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: -8.9821, NDCG: 0.4693

Training nDCG: 0.7982
Training random nDCG: 0.3350

Batch (val): 41/41

[I 2026-06-08 09:08:55,568] Trial 0 finished with value: 0.7872182651100327 and parameters: {'learning_rate': 0.0086619134937933, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 2}. Best is trial 0 with value: 0.7872182651100327.

Validation nDCG: 0.7827
Validation  random nDCG: 0.3584

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 2031.96 seconds

    Config:
    - learning_rate = 0.0027554600770451285
    - embedding_size = 128
    - pooling_method = max
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 10.6410, NDCG: 0.7039

Training nDCG: 0.7753
Training random nDCG: 0.3321

Batch (val): 41/41
Validation nDCG: 0.7969
Validation  random nDCG: 0.3514

--> Improvement! Best nDCG: 0.7969
Epoch: 2, Batch: 288/289, Pred Mean: 3.8828, NDCG: 0.4693

Training nDCG: 0.7962
Training random nDCG: 0.3822

Batch (val): 41/41
Validation nDCG: 0.7529
Validation  random nDCG: 0.3279

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -1.8346, NDCG: 0.4693

Training nDCG: 0.7980
Training random nDCG: 0.3431

Batch (val): 41/41
Validation nDCG: 0.7803
Validation  random nDCG: 0.3707

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -8.9789, NDCG: 0.7654

Training nDCG: 0.7950
Training random nDCG: 0.3589

Batch (val): 41/41
Validation nDCG: 0.7687
Validation  random nDCG: 0.3466

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -7.4227, NDCG: 0.4693

Training nDCG: 0.8017
Training random nDCG: 0.3508

Batch (val): 41/41

[I 2026-06-08 09:24:47,005] Trial 1 finished with value: 0.7968788710345228 and parameters: {'learning_rate': 0.0027554600770451285, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 8}. Best is trial 1 with value: 0.7968788710345228.

Validation nDCG: 0.7922
Validation  random nDCG: 0.3535

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 951.39 seconds

    Config:
    - learning_rate = 0.003060282435788249
    - embedding_size = 128
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.9748, NDCG: 0.6257

Training nDCG: 0.7698
Training random nDCG: 0.3476

Batch (val): 41/41
Validation nDCG: 0.7608
Validation  random nDCG: 0.3597

--> Improvement! Best nDCG: 0.7608
Epoch: 2, Batch: 288/289, Pred Mean: -3.4017, NDCG: 0.7777

Training nDCG: 0.7967
Training random nDCG: 0.3386

Batch (val): 41/41
Validation nDCG: 0.7606
Validation  random nDCG: 0.3525

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 2.9773, NDCG: 0.6049

Training nDCG: 0.8038
Training random nDCG: 0.3454

Batch (val): 41/41
Validation nDCG: 0.7804
Validation  random nDCG: 0.3969

--> Improvement! Best nDCG: 0.7804
Epoch: 4, Batch: 288/289, Pred Mean: -4.2005, NDCG: 0.8070

Training nDCG: 0.8015
Training random nDCG: 0.3398

Batch (val): 41/41
Validation nDCG: 0.7699
Validation  random nDCG: 0.3465

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -6.4134, NDCG: 0.4693

Training nDCG: 0.8139
Training random nDCG: 0.3479

Batch (val): 41/41
Validation nDCG: 0.7889
Validation  random nDCG: 0.4151

--> Improvement! Best nDCG: 0.7889
Epoch: 6, Batch: 288/289, Pred Mean: -4.8676, NDCG: 0.6049

Training nDCG: 0.8188
Training random nDCG: 0.3674

Batch (val): 41/41
Validation nDCG: 0.7725
Validation  random nDCG: 0.4117

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -4.8921, NDCG: 0.4693

Training nDCG: 0.8104
Training random nDCG: 0.3491

Batch (val): 41/41
Validation nDCG: 0.7718
Validation  random nDCG: 0.3388

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: -5.4855, NDCG: 0.4693

Training nDCG: 0.8124
Training random nDCG: 0.3482

Batch (val): 41/41
Validation nDCG: 0.7760
Validation  random nDCG: 0.3710

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: -7.9210, NDCG: 0.6173

Training nDCG: 0.8186
Training random nDCG: 0.3443

Batch (val): 41/41

[I 2026-06-08 09:52:46,596] Trial 2 finished with value: 0.7888811562302579 and parameters: {'learning_rate': 0.003060282435788249, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.7968788710345228.

Validation nDCG: 0.7758
Validation  random nDCG: 0.3932

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 1679.55 seconds
Best hyperparameters: {'learning_rate': 0.0027554600770451285, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879

[I 2026-06-08 09:52:48,543] A new study created in memory with name: no-name-023b8253-48e5-4980-b04a-78c2e9996f29

Running study for llama structured with inference=False and isco=True

    Config:
    - learning_rate = 0.002884245402402435
    - embedding_size = 16
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.0212, NDCG: 0.7039

Training nDCG: 0.7647
Training random nDCG: 0.3497

Batch (val): 41/41
Validation nDCG: 0.7813
Validation  random nDCG: 0.3340

--> Improvement! Best nDCG: 0.7813
Epoch: 2, Batch: 288/289, Pred Mean: -0.3498, NDCG: 0.9010

Training nDCG: 0.7921
Training random nDCG: 0.3571

Batch (val): 41/41
Validation nDCG: 0.7944
Validation  random nDCG: 0.3578

--> Improvement! Best nDCG: 0.7944
Epoch: 3, Batch: 288/289, Pred Mean: -0.5364, NDCG: 0.7039

Training nDCG: 0.8009
Training random nDCG: 0.3549

Batch (val): 41/41
Validation nDCG: 0.7776
Validation  random nDCG: 0.3791

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.1685, NDCG: 0.7039

Training nDCG: 0.8003
Training random nDCG: 0.3339

Batch (val): 41/41
Validation nDCG: 0.7863
Validation  random nDCG: 0.3215

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.5727, NDCG: 0.6714

Training nDCG: 0.8031
Training random nDCG: 0.3566

Batch (val): 41/41
Validation nDCG: 0.8036
Validation  random nDCG: 0.3379

--> Improvement! Best nDCG: 0.8036
Epoch: 6, Batch: 288/289, Pred Mean: -0.1808, NDCG: 0.6364

Training nDCG: 0.7992
Training random nDCG: 0.3725

Batch (val): 41/41
Validation nDCG: 0.8038
Validation  random nDCG: 0.3152

--> Improvement! Best nDCG: 0.8038
Epoch: 7, Batch: 288/289, Pred Mean: -0.6051, NDCG: 0.6173

Training nDCG: 0.8002
Training random nDCG: 0.3629

Batch (val): 41/41
Validation nDCG: 0.7819
Validation  random nDCG: 0.3658

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: -0.5624, NDCG: 0.6105

Training nDCG: 0.8065
Training random nDCG: 0.3473

Batch (val): 41/41
Validation nDCG: 0.7872
Validation  random nDCG: 0.4039

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: -0.7952, NDCG: 0.7039

Training nDCG: 0.8133
Training random nDCG: 0.3269

Batch (val): 41/41
Validation nDCG: 0.7923
Validation  random nDCG: 0.3840

--> No improvement. Patience: 3/4
Epoch: 10, Batch: 288/289, Pred Mean: -1.4339, NDCG: 0.6173

Training nDCG: 0.8231
Training random nDCG: 0.3654

Batch (val): 41/41

[I 2026-06-08 10:09:54,828] Trial 0 finished with value: 0.80381426922851 and parameters: {'learning_rate': 0.002884245402402435, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.80381426922851.

Validation nDCG: 0.7905
Validation  random nDCG: 0.3473

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 10
Training for 15 epochs took 1026.21 seconds

    Config:
    - learning_rate = 0.0004692403839063054
    - embedding_size = 128
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.8318, NDCG: 0.6257

Training nDCG: 0.7358
Training random nDCG: 0.3739

Batch (val): 41/41
Validation nDCG: 0.7941
Validation  random nDCG: 0.3702

--> Improvement! Best nDCG: 0.7941
Epoch: 2, Batch: 288/289, Pred Mean: -0.2717, NDCG: 0.6364

Training nDCG: 0.7817
Training random nDCG: 0.3489

Batch (val): 41/41
Validation nDCG: 0.7777
Validation  random nDCG: 0.3789

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.4728, NDCG: 0.7039

Training nDCG: 0.7811
Training random nDCG: 0.3623

Batch (val): 41/41
Validation nDCG: 0.7564
Validation  random nDCG: 0.3223

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.6144, NDCG: 0.8278

Training nDCG: 0.7983
Training random nDCG: 0.3239

Batch (val): 41/41
Validation nDCG: 0.7838
Validation  random nDCG: 0.3388

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.5173, NDCG: 0.7777

Training nDCG: 0.8025
Training random nDCG: 0.3469

Batch (val): 41/41
Validation nDCG: 0.7626
Validation  random nDCG: 0.2848

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 526.41 seconds

[I 2026-06-08 10:18:41,267] Trial 1 finished with value: 0.7940613507380218 and parameters: {'learning_rate': 0.0004692403839063054, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.80381426922851.

    Config:
    - learning_rate = 0.0002590423295267711
    - embedding_size = 16
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.1284, NDCG: 0.9675

Training nDCG: 0.5106
Training random nDCG: 0.3647

Batch (val): 41/41
Validation nDCG: 0.6385
Validation  random nDCG: 0.3341

--> Improvement! Best nDCG: 0.6385
Epoch: 2, Batch: 288/289, Pred Mean: -0.1144, NDCG: 0.7670

Training nDCG: 0.7734
Training random nDCG: 0.3775

Batch (val): 41/41
Validation nDCG: 0.7952
Validation  random nDCG: 0.2708

--> Improvement! Best nDCG: 0.7952
Epoch: 3, Batch: 288/289, Pred Mean: -0.0969, NDCG: 0.4693

Training nDCG: 0.7852
Training random nDCG: 0.3561

Batch (val): 41/41
Validation nDCG: 0.7704
Validation  random nDCG: 0.3480

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.1425, NDCG: 0.6105

Training nDCG: 0.8010
Training random nDCG: 0.3475

Batch (val): 41/41
Validation nDCG: 0.7863
Validation  random nDCG: 0.3840

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.0699, NDCG: 0.6257

Training nDCG: 0.8039
Training random nDCG: 0.3677

Batch (val): 41/41
Validation nDCG: 0.7921
Validation  random nDCG: 0.3380

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.1197, NDCG: 0.6714

Training nDCG: 0.8027
Training random nDCG: 0.3570

Batch (val): 41/41
Validation nDCG: 0.7962
Validation  random nDCG: 0.3500

--> Improvement! Best nDCG: 0.7962
Epoch: 7, Batch: 288/289, Pred Mean: 0.3170, NDCG: 0.7039

Training nDCG: 0.8133
Training random nDCG: 0.3651

Batch (val): 41/41
Validation nDCG: 0.7904
Validation  random nDCG: 0.3580

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: -0.0362, NDCG: 0.6714

Training nDCG: 0.8111
Training random nDCG: 0.3556

Batch (val): 41/41
Validation nDCG: 0.7944
Validation  random nDCG: 0.3390

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.0216, NDCG: 0.8396

Training nDCG: 0.8186
Training random nDCG: 0.3310

Batch (val): 41/41
Validation nDCG: 0.7864
Validation  random nDCG: 0.3738

--> No improvement. Patience: 3/4
Epoch: 10, Batch: 288/289, Pred Mean: 0.1571, NDCG: 0.8529

Training nDCG: 0.8278
Training random nDCG: 0.3528

Batch (val): 41/41
Validation nDCG: 0.7990
Validation  random nDCG: 0.3139

--> Improvement! Best nDCG: 0.7990
Epoch: 11, Batch: 288/289, Pred Mean: 0.5251, NDCG: 0.8452

Training nDCG: 0.8286
Training random nDCG: 0.3393

Batch (val): 41/41
Validation nDCG: 0.7776
Validation  random nDCG: 0.3833

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: 0.7365, NDCG: 0.8529

Training nDCG: 0.8226
Training random nDCG: 0.3409

Batch (val): 41/41
Validation nDCG: 0.7680
Validation  random nDCG: 0.3468

--> No improvement. Patience: 2/4
Epoch: 13, Batch: 288/289, Pred Mean: 0.5588, NDCG: 0.8529

Training nDCG: 0.8157
Training random nDCG: 0.3587

Batch (val): 41/41
Validation nDCG: 0.7589
Validation  random nDCG: 0.2996

--> No improvement. Patience: 3/4
Epoch: 14, Batch: 288/289, Pred Mean: 0.3464, NDCG: 0.9325

Training nDCG: 0.7985
Training random nDCG: 0.3731

Batch (val): 41/41

[I 2026-06-08 10:42:04,244] Trial 2 finished with value: 0.7990201619941326 and parameters: {'learning_rate': 0.0002590423295267711, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.80381426922851.

Validation nDCG: 0.7616
Validation  random nDCG: 0.3738

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 14
Training for 15 epochs took 1402.96 seconds
Best hyperparameters: {'learning_rate': 0.002884245402402435, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814

[I 2026-06-08 10:42:06,740] A new study created in memory with name: no-name-e31c9f16-fb64-4729-b4c9-0cdb3392a5d1

Running study for llama semi-structured with inference=False and isco=True

    Config:
    - learning_rate = 0.0002370945631698375
    - embedding_size = 128
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.0638, NDCG: 0.6105

Training nDCG: 0.7234
Training random nDCG: 0.3371

Batch (val): 41/41
Validation nDCG: 0.7853
Validation  random nDCG: 0.3533

--> Improvement! Best nDCG: 0.7853
Epoch: 2, Batch: 288/289, Pred Mean: 0.1457, NDCG: 0.4693

Training nDCG: 0.7883
Training random nDCG: 0.3488

Batch (val): 41/41
Validation nDCG: 0.7720
Validation  random nDCG: 0.3560

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.1660, NDCG: 0.4693

Training nDCG: 0.8015
Training random nDCG: 0.3655

Batch (val): 41/41
Validation nDCG: 0.7677
Validation  random nDCG: 0.3242

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1607, NDCG: 0.6364

Training nDCG: 0.8102
Training random nDCG: 0.3638

Batch (val): 41/41
Validation nDCG: 0.7870
Validation  random nDCG: 0.4349

--> Improvement! Best nDCG: 0.7870
Epoch: 5, Batch: 288/289, Pred Mean: 0.1438, NDCG: 0.6364

Training nDCG: 0.8222
Training random nDCG: 0.3545

Batch (val): 41/41
Validation nDCG: 0.7831
Validation  random nDCG: 0.3469

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.2545, NDCG: 0.6508

Training nDCG: 0.8289
Training random nDCG: 0.3737

Batch (val): 41/41
Validation nDCG: 0.7971
Validation  random nDCG: 0.3524

--> Improvement! Best nDCG: 0.7971
Epoch: 7, Batch: 288/289, Pred Mean: 0.2248, NDCG: 0.6714

Training nDCG: 0.8278
Training random nDCG: 0.3308

Batch (val): 41/41
Validation nDCG: 0.8145
Validation  random nDCG: 0.3588

--> Improvement! Best nDCG: 0.8145
Epoch: 8, Batch: 288/289, Pred Mean: 0.0651, NDCG: 0.6714

Training nDCG: 0.8365
Training random nDCG: 0.3662

Batch (val): 41/41
Validation nDCG: 0.7882
Validation  random nDCG: 0.4116

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.4228, NDCG: 0.6714

Training nDCG: 0.8240
Training random nDCG: 0.3547

Batch (val): 41/41
Validation nDCG: 0.7433
Validation  random nDCG: 0.4142

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 0.3910, NDCG: 0.7039

Training nDCG: 0.8170
Training random nDCG: 0.3305

Batch (val): 41/41
Validation nDCG: 0.7746
Validation  random nDCG: 0.3259

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.3508, NDCG: 0.8127

Training nDCG: 0.8380
Training random nDCG: 0.3428

Batch (val): 41/41

[I 2026-06-08 11:00:54,810] Trial 0 finished with value: 0.8144644281148674 and parameters: {'learning_rate': 0.0002370945631698375, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 2}. Best is trial 0 with value: 0.8144644281148674.

Validation nDCG: 0.7472
Validation  random nDCG: 0.3326

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 1128.02 seconds

    Config:
    - learning_rate = 0.00020216247895752867
    - embedding_size = 128
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -1.0465, NDCG: 0.2961

Training nDCG: 0.5348
Training random nDCG: 0.3618

Batch (val): 41/41
Validation nDCG: 0.5961
Validation  random nDCG: 0.3849

--> Improvement! Best nDCG: 0.5961
Epoch: 2, Batch: 288/289, Pred Mean: -1.5106, NDCG: 0.6105

Training nDCG: 0.7578
Training random nDCG: 0.3455

Batch (val): 41/41
Validation nDCG: 0.8087
Validation  random nDCG: 0.3091

--> Improvement! Best nDCG: 0.8087
Epoch: 3, Batch: 288/289, Pred Mean: -1.8564, NDCG: 0.6364

Training nDCG: 0.7783
Training random nDCG: 0.3579

Batch (val): 41/41
Validation nDCG: 0.7754
Validation  random nDCG: 0.3949

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.9248, NDCG: 0.6257

Training nDCG: 0.7981
Training random nDCG: 0.3638

Batch (val): 41/41
Validation nDCG: 0.7822
Validation  random nDCG: 0.3333

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -2.4796, NDCG: 0.6508

Training nDCG: 0.7989
Training random nDCG: 0.3502

Batch (val): 41/41
Validation nDCG: 0.8166
Validation  random nDCG: 0.3741

--> Improvement! Best nDCG: 0.8166
Epoch: 6, Batch: 288/289, Pred Mean: -3.2424, NDCG: 0.6173

Training nDCG: 0.8196
Training random nDCG: 0.3601

Batch (val): 41/41
Validation nDCG: 0.7696
Validation  random nDCG: 0.3589

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -3.5887, NDCG: 0.6173

Training nDCG: 0.8217
Training random nDCG: 0.3426

Batch (val): 41/41
Validation nDCG: 0.6249
Validation  random nDCG: 0.3985

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: -3.4639, NDCG: 0.4693

Training nDCG: 0.8324
Training random nDCG: 0.3622

Batch (val): 41/41
Validation nDCG: 0.6238
Validation  random nDCG: 0.3633

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: -4.7000, NDCG: 0.4693

Training nDCG: 0.8413
Training random nDCG: 0.3341

Batch (val): 41/41

[I 2026-06-08 11:17:17,930] Trial 1 finished with value: 0.816645930450729 and parameters: {'learning_rate': 0.00020216247895752867, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 8}. Best is trial 1 with value: 0.816645930450729.

Validation nDCG: 0.7672
Validation  random nDCG: 0.3423

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 983.08 seconds

    Config:
    - learning_rate = 0.0006379287164271955
    - embedding_size = 8
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.0306, NDCG: 0.6173

Training nDCG: 0.6755
Training random nDCG: 0.3486

Batch (val): 41/41
Validation nDCG: 0.7996
Validation  random nDCG: 0.3577

--> Improvement! Best nDCG: 0.7996
Epoch: 2, Batch: 288/289, Pred Mean: 0.0418, NDCG: 0.7039

Training nDCG: 0.7806
Training random nDCG: 0.3396

Batch (val): 41/41
Validation nDCG: 0.7853
Validation  random nDCG: 0.3920

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.0816, NDCG: 0.7039

Training nDCG: 0.7862
Training random nDCG: 0.3399

Batch (val): 41/41
Validation nDCG: 0.7888
Validation  random nDCG: 0.3452

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1017, NDCG: 0.6714

Training nDCG: 0.8000
Training random nDCG: 0.3518

Batch (val): 41/41
Validation nDCG: 0.7792
Validation  random nDCG: 0.3633

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.1289, NDCG: 0.7039

Training nDCG: 0.8100
Training random nDCG: 0.3409

Batch (val): 41/41

[I 2026-06-08 11:25:42,240] Trial 2 finished with value: 0.7995891338697697 and parameters: {'learning_rate': 0.0006379287164271955, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 4}. Best is trial 1 with value: 0.816645930450729.

Validation nDCG: 0.7704
Validation  random nDCG: 0.3163

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 504.28 seconds
Best hyperparameters: {'learning_rate': 0.00020216247895752867, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646

[I 2026-06-08 11:25:44,582] A new study created in memory with name: no-name-ecbb408e-9620-4a50-97e9-0bbe6513597d

Running study for llama unstructured with inference=False and isco=True

    Config:
    - learning_rate = 0.0027139443459626472
    - embedding_size = 64
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.1420, NDCG: 0.4693

Training nDCG: 0.7514
Training random nDCG: 0.3501

Batch (val): 41/41
Validation nDCG: 0.7887
Validation  random nDCG: 0.3211

--> Improvement! Best nDCG: 0.7887
Epoch: 2, Batch: 288/289, Pred Mean: -0.2612, NDCG: 0.6364

Training nDCG: 0.8102
Training random nDCG: 0.3596

Batch (val): 41/41
Validation nDCG: 0.7811
Validation  random nDCG: 0.3827

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.4539, NDCG: 0.6105

Training nDCG: 0.8110
Training random nDCG: 0.3399

Batch (val): 41/41
Validation nDCG: 0.7785
Validation  random nDCG: 0.3516

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.5929, NDCG: 0.6257

Training nDCG: 0.8128
Training random nDCG: 0.3637

Batch (val): 41/41
Validation nDCG: 0.7792
Validation  random nDCG: 0.3566

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.0387, NDCG: 0.6257

Training nDCG: 0.8175
Training random nDCG: 0.3622

Batch (val): 40/41

[I 2026-06-08 11:36:37,630] Trial 0 finished with value: 0.7887067372669806 and parameters: {'learning_rate': 0.0027139443459626472, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.7887067372669806.

Batch (val): 41/41
Validation nDCG: 0.7796
Validation  random nDCG: 0.3683

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 652.99 seconds

    Config:
    - learning_rate = 0.00038500595739994486
    - embedding_size = 8
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.0834, NDCG: 0.4693

Training nDCG: 0.6412
Training random nDCG: 0.3575

Batch (val): 41/41
Validation nDCG: 0.7774
Validation  random nDCG: 0.2810

--> Improvement! Best nDCG: 0.7774
Epoch: 2, Batch: 288/289, Pred Mean: -0.0153, NDCG: 0.4693

Training nDCG: 0.7757
Training random nDCG: 0.3399

Batch (val): 41/41
Validation nDCG: 0.7968
Validation  random nDCG: 0.3275

--> Improvement! Best nDCG: 0.7968
Epoch: 3, Batch: 288/289, Pred Mean: 0.0526, NDCG: 0.4693

Training nDCG: 0.7868
Training random nDCG: 0.3626

Batch (val): 41/41
Validation nDCG: 0.7955
Validation  random nDCG: 0.3863

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1065, NDCG: 0.4693

Training nDCG: 0.8003
Training random nDCG: 0.3763

Batch (val): 41/41
Validation nDCG: 0.7839
Validation  random nDCG: 0.3776

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.1459, NDCG: 0.4693

Training nDCG: 0.8070
Training random nDCG: 0.3674

Batch (val): 41/41
Validation nDCG: 0.7875
Validation  random nDCG: 0.3910

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.1777, NDCG: 0.4693

Training nDCG: 0.8165
Training random nDCG: 0.3333

Batch (val): 41/41

[I 2026-06-08 11:49:23,196] Trial 1 finished with value: 0.7968242219191344 and parameters: {'learning_rate': 0.00038500595739994486, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 2}. Best is trial 1 with value: 0.7968242219191344.

Validation nDCG: 0.7949
Validation  random nDCG: 0.3470

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 765.53 seconds

    Config:
    - learning_rate = 0.006151089216463404
    - embedding_size = 32
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.3019, NDCG: 0.7654

Training nDCG: 0.7780
Training random nDCG: 0.3503

Batch (val): 41/41
Validation nDCG: 0.7696
Validation  random nDCG: 0.4030

--> Improvement! Best nDCG: 0.7696
Epoch: 2, Batch: 288/289, Pred Mean: -0.5851, NDCG: 0.4693

Training nDCG: 0.7931
Training random nDCG: 0.3432

Batch (val): 41/41
Validation nDCG: 0.7869
Validation  random nDCG: 0.3923

--> Improvement! Best nDCG: 0.7869
Epoch: 3, Batch: 288/289, Pred Mean: -2.3515, NDCG: 0.4693

Training nDCG: 0.8081
Training random nDCG: 0.3468

Batch (val): 41/41
Validation nDCG: 0.7749
Validation  random nDCG: 0.3125

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.1496, NDCG: 0.7654

Training nDCG: 0.8142
Training random nDCG: 0.3541

Batch (val): 41/41
Validation nDCG: 0.7724
Validation  random nDCG: 0.3574

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -4.0254, NDCG: 0.7654

Training nDCG: 0.8100
Training random nDCG: 0.3526

Batch (val): 41/41
Validation nDCG: 0.7952
Validation  random nDCG: 0.3257

--> Improvement! Best nDCG: 0.7952
Epoch: 6, Batch: 288/289, Pred Mean: -3.2511, NDCG: 0.6257

Training nDCG: 0.8131
Training random nDCG: 0.3592

Batch (val): 41/41
Validation nDCG: 0.7748
Validation  random nDCG: 0.3320

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -5.0391, NDCG: 0.9134

Training nDCG: 0.8108
Training random nDCG: 0.3500

Batch (val): 41/41
Validation nDCG: 0.7776
Validation  random nDCG: 0.2926

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: -2.5620, NDCG: 0.4693

Training nDCG: 0.8139
Training random nDCG: 0.3786

Batch (val): 41/41
Validation nDCG: 0.7830
Validation  random nDCG: 0.3503

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: -2.8994, NDCG: 0.7586

Training nDCG: 0.8101
Training random nDCG: 0.3449

Batch (val): 40/41

[I 2026-06-08 12:08:23,360] Trial 2 finished with value: 0.795211220498447 and parameters: {'learning_rate': 0.006151089216463404, 'embedding_size': 32, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.7968242219191344.

Batch (val): 41/41
Validation nDCG: 0.7609
Validation  random nDCG: 0.3216

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 1140.11 seconds
Best hyperparameters: {'learning_rate': 0.00038500595739994486, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824

[I 2026-06-08 12:08:24,991] A new study created in memory with name: no-name-de3be8ef-00c9-4867-9627-e44531b87051

Running study for qwen structured with inference=False and isco=False

    Config:
    - learning_rate = 0.00011518891040232245
    - embedding_size = 128
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.4003, NDCG: 0.4693

Training nDCG: 0.6887
Training random nDCG: 0.3422

Batch (val): 41/41
Validation nDCG: 0.7742
Validation  random nDCG: 0.3600

--> Improvement! Best nDCG: 0.7742
Epoch: 2, Batch: 288/289, Pred Mean: -0.7013, NDCG: 0.6364

Training nDCG: 0.7943
Training random nDCG: 0.3619

Batch (val): 41/41
Validation nDCG: 0.7646
Validation  random nDCG: 0.3750

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.3594, NDCG: 0.6508

Training nDCG: 0.8138
Training random nDCG: 0.3461

Batch (val): 41/41
Validation nDCG: 0.7531
Validation  random nDCG: 0.3620

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.4591, NDCG: 0.8127

Training nDCG: 0.8291
Training random nDCG: 0.3664

Batch (val): 41/41
Validation nDCG: 0.7473
Validation  random nDCG: 0.2904

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 2.9524, NDCG: 0.3759

Training nDCG: 0.8340
Training random nDCG: 0.3638

Batch (val): 41/41

[I 2026-06-08 12:17:14,033] Trial 0 finished with value: 0.774183513616682 and parameters: {'learning_rate': 0.00011518891040232245, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}. Best is trial 0 with value: 0.774183513616682.

Validation nDCG: 0.7331
Validation  random nDCG: 0.3592

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 528.99 seconds

    Config:
    - learning_rate = 0.0002446151280499899
    - embedding_size = 64
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -1.1290, NDCG: 0.0000

Training nDCG: 0.5096
Training random nDCG: 0.3422

Batch (val): 41/41
Validation nDCG: 0.7879
Validation  random nDCG: 0.3709

--> Improvement! Best nDCG: 0.7879
Epoch: 2, Batch: 288/289, Pred Mean: -2.1396, NDCG: 0.4693

Training nDCG: 0.7361
Training random nDCG: 0.3391

Batch (val): 41/41
Validation nDCG: 0.5052
Validation  random nDCG: 0.4112

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -2.8041, NDCG: 0.4693

Training nDCG: 0.8048
Training random nDCG: 0.3305

Batch (val): 41/41
Validation nDCG: 0.6194
Validation  random nDCG: 0.3660

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -2.6626, NDCG: 0.7654

Training nDCG: 0.8239
Training random nDCG: 0.3450

Batch (val): 41/41
Validation nDCG: 0.7811
Validation  random nDCG: 0.3863

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -3.2165, NDCG: 0.7039

Training nDCG: 0.8334
Training random nDCG: 0.3593

Batch (val): 40/41

[I 2026-06-08 12:26:12,316] Trial 1 finished with value: 0.7879458316681309 and parameters: {'learning_rate': 0.0002446151280499899, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 8}. Best is trial 1 with value: 0.7879458316681309.

Batch (val): 41/41
Validation nDCG: 0.7261
Validation  random nDCG: 0.3533

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 538.25 seconds

    Config:
    - learning_rate = 0.002401311959097615
    - embedding_size = 32
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -0.3383, NDCG: 0.6508

Training nDCG: 0.7211
Training random nDCG: 0.3374

Batch (val): 41/41
Validation nDCG: 0.7796
Validation  random nDCG: 0.3650

--> Improvement! Best nDCG: 0.7796
Epoch: 2, Batch: 288/289, Pred Mean: -1.0672, NDCG: 0.7654

Training nDCG: 0.7805
Training random nDCG: 0.3497

Batch (val): 41/41
Validation nDCG: 0.7514
Validation  random nDCG: 0.3457

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.5753, NDCG: 0.7654

Training nDCG: 0.7855
Training random nDCG: 0.3348

Batch (val): 41/41
Validation nDCG: 0.6996
Validation  random nDCG: 0.3632

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: -2.0497, NDCG: 0.6049

Training nDCG: 0.7838
Training random nDCG: 0.3561

Batch (val): 41/41
Validation nDCG: 0.7810
Validation  random nDCG: 0.3383

--> Improvement! Best nDCG: 0.7810
Epoch: 5, Batch: 288/289, Pred Mean: -0.8245, NDCG: 0.7039

Training nDCG: 0.7860
Training random nDCG: 0.3438

Batch (val): 41/41
Validation nDCG: 0.7722
Validation  random nDCG: 0.3493

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.2929, NDCG: 0.8070

Training nDCG: 0.7895
Training random nDCG: 0.3534

Batch (val): 41/41
Validation nDCG: 0.7659
Validation  random nDCG: 0.3193

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: -1.7202, NDCG: 0.6364

Training nDCG: 0.7918
Training random nDCG: 0.3535

Batch (val): 41/41
Validation nDCG: 0.7731
Validation  random nDCG: 0.3307

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: -1.3037, NDCG: 0.6257

Training nDCG: 0.7916
Training random nDCG: 0.3552

Batch (val): 41/41

[I 2026-06-08 12:39:53,970] Trial 2 finished with value: 0.7810422882651381 and parameters: {'learning_rate': 0.002401311959097615, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 8}. Best is trial 1 with value: 0.7879458316681309.

Validation nDCG: 0.7609
Validation  random nDCG: 0.3887

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 821.63 seconds
Best hyperparameters: {'learning_rate': 0.0002446151280499899, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 8}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946

[I 2026-06-08 12:39:56,054] A new study created in memory with name: no-name-2938a667-e48a-4916-bfd8-75913b1a8df3

Running study for qwen semi-structured with inference=False and isco=False

    Config:
    - learning_rate = 0.0001358744554147989
    - embedding_size = 128
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.1532, NDCG: 0.6049

Training nDCG: 0.7476
Training random nDCG: 0.3526

Batch (val): 41/41
Validation nDCG: 0.7685
Validation  random nDCG: 0.3125

--> Improvement! Best nDCG: 0.7685
Epoch: 2, Batch: 288/289, Pred Mean: 0.2016, NDCG: 0.4693

Training nDCG: 0.7984
Training random nDCG: 0.3315

Batch (val): 41/41
Validation nDCG: 0.7733
Validation  random nDCG: 0.3029

--> Improvement! Best nDCG: 0.7733
Epoch: 3, Batch: 288/289, Pred Mean: 0.1919, NDCG: 0.4693

Training nDCG: 0.8100
Training random nDCG: 0.3414

Batch (val): 41/41
Validation nDCG: 0.7661
Validation  random nDCG: 0.3138

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.2150, NDCG: 0.4693

Training nDCG: 0.8171
Training random nDCG: 0.3153

Batch (val): 41/41
Validation nDCG: 0.7663
Validation  random nDCG: 0.3615

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.1480, NDCG: 0.4693

Training nDCG: 0.8252
Training random nDCG: 0.3543

Batch (val): 41/41
Validation nDCG: 0.7634
Validation  random nDCG: 0.3552

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.2054, NDCG: 0.4693

Training nDCG: 0.8235
Training random nDCG: 0.3530

Batch (val): 40/41

[I 2026-06-08 12:51:26,905] Trial 0 finished with value: 0.7733390327076469 and parameters: {'learning_rate': 0.0001358744554147989, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 2}. Best is trial 0 with value: 0.7733390327076469.

Batch (val): 41/41
Validation nDCG: 0.7579
Validation  random nDCG: 0.3301

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 690.79 seconds

    Config:
    - learning_rate = 0.00025328038363673614
    - embedding_size = 128
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.1609, NDCG: 0.6105

Training nDCG: 0.7647
Training random nDCG: 0.3692

Batch (val): 41/41
Validation nDCG: 0.7775
Validation  random nDCG: 0.3259

--> Improvement! Best nDCG: 0.7775
Epoch: 2, Batch: 288/289, Pred Mean: 0.1974, NDCG: 0.6257

Training nDCG: 0.7953
Training random nDCG: 0.3626

Batch (val): 41/41
Validation nDCG: 0.7668
Validation  random nDCG: 0.3407

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.1645, NDCG: 0.6173

Training nDCG: 0.8057
Training random nDCG: 0.3439

Batch (val): 41/41
Validation nDCG: 0.7663
Validation  random nDCG: 0.3852

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.2468, NDCG: 0.6173

Training nDCG: 0.8077
Training random nDCG: 0.3367

Batch (val): 41/41
Validation nDCG: 0.7426
Validation  random nDCG: 0.3358

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.1653, NDCG: 0.6364

Training nDCG: 0.8186
Training random nDCG: 0.3674

Batch (val): 41/41

[I 2026-06-08 13:02:18,915] Trial 1 finished with value: 0.7774674722206283 and parameters: {'learning_rate': 0.00025328038363673614, 'embedding_size': 128, 'pooling_method': 'mean', 'heads': 4}. Best is trial 1 with value: 0.7774674722206283.

Validation nDCG: 0.7760
Validation  random nDCG: 0.3967

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 651.98 seconds

    Config:
    - learning_rate = 0.0025701024518244436
    - embedding_size = 128
    - pooling_method = max
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 1.7996, NDCG: 0.4693

Training nDCG: 0.7774
Training random nDCG: 0.3621

Batch (val): 41/41
Validation nDCG: 0.7895
Validation  random nDCG: 0.3569

--> Improvement! Best nDCG: 0.7895
Epoch: 2, Batch: 288/289, Pred Mean: 1.7363, NDCG: 0.7654

Training nDCG: 0.7920
Training random nDCG: 0.3665

Batch (val): 41/41
Validation nDCG: 0.7716
Validation  random nDCG: 0.3535

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -1.8838, NDCG: 0.4693

Training nDCG: 0.7946
Training random nDCG: 0.3514

Batch (val): 41/41
Validation nDCG: 0.7868
Validation  random nDCG: 0.3478

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 1.2328, NDCG: 0.4693

Training nDCG: 0.7945
Training random nDCG: 0.3453

Batch (val): 41/41
Validation nDCG: 0.7775
Validation  random nDCG: 0.3235

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -3.4453, NDCG: 0.6173

Training nDCG: 0.8048
Training random nDCG: 0.3597

Batch (val): 41/41

[I 2026-06-08 13:21:10,430] Trial 2 finished with value: 0.7894549532878214 and parameters: {'learning_rate': 0.0025701024518244436, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}. Best is trial 2 with value: 0.7894549532878214.

Validation nDCG: 0.7704
Validation  random nDCG: 0.3592

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 1131.45 seconds
Best hyperparameters: {'learning_rate': 0.0025701024518244436, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455

[I 2026-06-08 13:21:14,237] A new study created in memory with name: no-name-2ea294c1-195e-47d3-8212-508bc7b3c332

Running study for qwen unstructured with inference=False and isco=False

    Config:
    - learning_rate = 0.0003178273771441516
    - embedding_size = 128
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.1630, NDCG: 0.7039

Training nDCG: 0.7292
Training random nDCG: 0.3570

Batch (val): 41/41
Validation nDCG: 0.7282
Validation  random nDCG: 0.3665

--> Improvement! Best nDCG: 0.7282
Epoch: 2, Batch: 288/289, Pred Mean: 0.1486, NDCG: 0.4693

Training nDCG: 0.7768
Training random nDCG: 0.3552

Batch (val): 41/41
Validation nDCG: 0.7239
Validation  random nDCG: 0.3909

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.2749, NDCG: 0.7039

Training nDCG: 0.7958
Training random nDCG: 0.3424

Batch (val): 41/41
Validation nDCG: 0.7404
Validation  random nDCG: 0.3488

--> Improvement! Best nDCG: 0.7404
Epoch: 4, Batch: 288/289, Pred Mean: -0.7742, NDCG: 0.4693

Training nDCG: 0.8182
Training random nDCG: 0.3579

Batch (val): 41/41
Validation nDCG: 0.7572
Validation  random nDCG: 0.3376

--> Improvement! Best nDCG: 0.7572
Epoch: 5, Batch: 288/289, Pred Mean: -1.2399, NDCG: 0.6105

Training nDCG: 0.8359
Training random nDCG: 0.3307

Batch (val): 41/41
Validation nDCG: 0.7585
Validation  random nDCG: 0.2926

--> Improvement! Best nDCG: 0.7585
Epoch: 6, Batch: 288/289, Pred Mean: -0.9234, NDCG: 0.8070

Training nDCG: 0.8541
Training random nDCG: 0.3388

Batch (val): 41/41
Validation nDCG: 0.7509
Validation  random nDCG: 0.3299

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -1.4761, NDCG: 0.9134

Training nDCG: 0.8740
Training random nDCG: 0.3718

Batch (val): 41/41
Validation nDCG: 0.7643
Validation  random nDCG: 0.3423

--> Improvement! Best nDCG: 0.7643
Epoch: 8, Batch: 288/289, Pred Mean: -3.5642, NDCG: 1.0000

Training nDCG: 0.8916
Training random nDCG: 0.3465

Batch (val): 41/41
Validation nDCG: 0.7521
Validation  random nDCG: 0.3842

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: -0.0714, NDCG: 1.0000

Training nDCG: 0.8826
Training random nDCG: 0.3350

Batch (val): 41/41
Validation nDCG: 0.6866
Validation  random nDCG: 0.2874

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: -0.1073, NDCG: 1.0000

Training nDCG: 0.9042
Training random nDCG: 0.3621

Batch (val): 41/41
Validation nDCG: 0.7084
Validation  random nDCG: 0.3624

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.7760, NDCG: 1.0000

Training nDCG: 0.8955
Training random nDCG: 0.3393

Batch (val): 41/41

[I 2026-06-08 14:33:23,678] Trial 0 finished with value: 0.7642931318295405 and parameters: {'learning_rate': 0.0003178273771441516, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.7642931318295405.

Validation nDCG: 0.6892
Validation  random nDCG: 0.3715

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 4329.29 seconds

    Config:
    - learning_rate = 0.0002546944287741854
    - embedding_size = 64
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 6.9272, NDCG: 0.0000

Training nDCG: 0.4227
Training random nDCG: 0.3552

Batch (val): 41/41
Validation nDCG: 0.3005
Validation  random nDCG: 0.3085

--> Improvement! Best nDCG: 0.3005
Epoch: 2, Batch: 288/289, Pred Mean: 1.9208, NDCG: 0.4693

Training nDCG: 0.6319
Training random nDCG: 0.3716

Batch (val): 41/41
Validation nDCG: 0.5730
Validation  random nDCG: 0.3501

--> Improvement! Best nDCG: 0.5730
Epoch: 3, Batch: 288/289, Pred Mean: -4.3138, NDCG: 0.4693

Training nDCG: 0.7035
Training random nDCG: 0.3203

Batch (val): 41/41
Validation nDCG: 0.5413
Validation  random nDCG: 0.3225

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -3.6473, NDCG: 0.6105

Training nDCG: 0.7659
Training random nDCG: 0.3526

Batch (val): 41/41
Validation nDCG: 0.5345
Validation  random nDCG: 0.3034

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -4.5259, NDCG: 0.6173

Training nDCG: 0.7809
Training random nDCG: 0.3560

Batch (val): 41/41
Validation nDCG: 0.7111
Validation  random nDCG: 0.3241

--> Improvement! Best nDCG: 0.7111
Epoch: 6, Batch: 288/289, Pred Mean: -4.2701, NDCG: 0.4441

Training nDCG: 0.7964
Training random nDCG: 0.3479

Batch (val): 41/41
Validation nDCG: 0.6949
Validation  random nDCG: 0.3615

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -4.6119, NDCG: 0.7530

Training nDCG: 0.7966
Training random nDCG: 0.3279

Batch (val): 41/41
Validation nDCG: 0.7114
Validation  random nDCG: 0.3238

--> Improvement! Best nDCG: 0.7114
Epoch: 8, Batch: 288/289, Pred Mean: -4.9788, NDCG: 0.4525

Training nDCG: 0.8109
Training random nDCG: 0.3562

Batch (val): 41/41
Validation nDCG: 0.6649
Validation  random nDCG: 0.3595

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: -6.6883, NDCG: 0.2021

Training nDCG: 0.8121
Training random nDCG: 0.3439

Batch (val): 41/41
Validation nDCG: 0.6281
Validation  random nDCG: 0.2799

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: -11.1915, NDCG: 0.1815

Training nDCG: 0.8282
Training random nDCG: 0.3573

Batch (val): 41/41
Validation nDCG: 0.6768
Validation  random nDCG: 0.3484

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: -2.2714, NDCG: 0.6364

Training nDCG: 0.8390
Training random nDCG: 0.3300

Batch (val): 41/41

[I 2026-06-08 15:44:58,905] Trial 1 finished with value: 0.7114199251686351 and parameters: {'learning_rate': 0.0002546944287741854, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.7642931318295405.

Validation nDCG: 0.6589
Validation  random nDCG: 0.3051

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 4295.14 seconds

    Config:
    - learning_rate = 0.00012835526296426186
    - embedding_size = 128
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.7993, NDCG: 0.4693

Training nDCG: 0.6569
Training random nDCG: 0.3530

Batch (val): 41/41
Validation nDCG: 0.6925
Validation  random nDCG: 0.3751

--> Improvement! Best nDCG: 0.6925
Epoch: 2, Batch: 288/289, Pred Mean: -0.2922, NDCG: 0.4693

Training nDCG: 0.7676
Training random nDCG: 0.3618

Batch (val): 41/41
Validation nDCG: 0.7284
Validation  random nDCG: 0.3632

--> Improvement! Best nDCG: 0.7284
Epoch: 3, Batch: 288/289, Pred Mean: -0.6233, NDCG: 0.6105

Training nDCG: 0.7852
Training random nDCG: 0.3353

Batch (val): 41/41
Validation nDCG: 0.7402
Validation  random nDCG: 0.3467

--> Improvement! Best nDCG: 0.7402
Epoch: 4, Batch: 288/289, Pred Mean: -0.3643, NDCG: 0.6105

Training nDCG: 0.8083
Training random nDCG: 0.3415

Batch (val): 41/41
Validation nDCG: 0.7472
Validation  random nDCG: 0.3936

--> Improvement! Best nDCG: 0.7472
Epoch: 5, Batch: 288/289, Pred Mean: 0.3149, NDCG: 0.7865

Training nDCG: 0.8277
Training random nDCG: 0.3460

Batch (val): 41/41
Validation nDCG: 0.7374
Validation  random nDCG: 0.3405

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.5580, NDCG: 0.6714

Training nDCG: 0.8400
Training random nDCG: 0.3560

Batch (val): 41/41
Validation nDCG: 0.7566
Validation  random nDCG: 0.3417

--> Improvement! Best nDCG: 0.7566
Epoch: 7, Batch: 288/289, Pred Mean: -0.7183, NDCG: 0.7039

Training nDCG: 0.8532
Training random nDCG: 0.3585

Batch (val): 41/41
Validation nDCG: 0.7700
Validation  random nDCG: 0.3746

--> Improvement! Best nDCG: 0.7700
Epoch: 8, Batch: 288/289, Pred Mean: -0.9470, NDCG: 0.8529

Training nDCG: 0.8387
Training random nDCG: 0.3603

Batch (val): 41/41
Validation nDCG: 0.7765
Validation  random nDCG: 0.3222

--> Improvement! Best nDCG: 0.7765
Epoch: 9, Batch: 288/289, Pred Mean: -0.3519, NDCG: 0.9325

Training nDCG: 0.8376
Training random nDCG: 0.3485

Batch (val): 41/41
Validation nDCG: 0.7602
Validation  random nDCG: 0.3188

--> No improvement. Patience: 1/4
Epoch: 10, Batch: 288/289, Pred Mean: -0.4000, NDCG: 0.9325

Training nDCG: 0.8306
Training random nDCG: 0.3770

Batch (val): 41/41
Validation nDCG: 0.7523
Validation  random nDCG: 0.3341

--> No improvement. Patience: 2/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.2460, NDCG: 0.4525

Training nDCG: 0.8321
Training random nDCG: 0.3751

Batch (val): 41/41
Validation nDCG: 0.7369
Validation  random nDCG: 0.3796

--> No improvement. Patience: 3/4
Epoch: 12, Batch: 288/289, Pred Mean: -0.5515, NDCG: 0.7462

Training nDCG: 0.8317
Training random nDCG: 0.3443

Batch (val): 41/41

[I 2026-06-08 16:56:20,611] Trial 2 finished with value: 0.7765026202751056 and parameters: {'learning_rate': 0.00012835526296426186, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 2}. Best is trial 2 with value: 0.7765026202751056.

Validation nDCG: 0.7709
Validation  random nDCG: 0.3344

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 12
Training for 15 epochs took 4281.63 seconds
Best hyperparameters: {'learning_rate': 0.00012835526296426186, 'embedding_size': 128, 'pooling_method': 'max', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503

[I 2026-06-08 16:56:22,378] A new study created in memory with name: no-name-0c06fcf6-4ae6-4658-ae94-e40a1ba25b8e

Running study for gemma structured with inference=False and isco=False

    Config:
    - learning_rate = 0.00010882324634948818
    - embedding_size = 64
    - pooling_method = sum
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -2.1855, NDCG: 0.2961

Training nDCG: 0.4255
Training random nDCG: 0.3567

Batch (val): 41/41
Validation nDCG: 0.6397
Validation  random nDCG: 0.3172

--> Improvement! Best nDCG: 0.6397
Epoch: 2, Batch: 288/289, Pred Mean: -0.8349, NDCG: 0.6714

Training nDCG: 0.6263
Training random nDCG: 0.3558

Batch (val): 41/41
Validation nDCG: 0.7134
Validation  random nDCG: 0.3414

--> Improvement! Best nDCG: 0.7134
Epoch: 3, Batch: 288/289, Pred Mean: -1.1715, NDCG: 0.7654

Training nDCG: 0.7226
Training random nDCG: 0.3429

Batch (val): 41/41
Validation nDCG: 0.5380
Validation  random nDCG: 0.3444

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.4143, NDCG: 0.7654

Training nDCG: 0.7838
Training random nDCG: 0.3574

Batch (val): 41/41
Validation nDCG: 0.6485
Validation  random nDCG: 0.3503

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.4944, NDCG: 0.7654

Training nDCG: 0.8031
Training random nDCG: 0.3573

Batch (val): 41/41
Validation nDCG: 0.7650
Validation  random nDCG: 0.4154

--> Improvement! Best nDCG: 0.7650
Epoch: 6, Batch: 288/289, Pred Mean: -1.5542, NDCG: 0.6508

Training nDCG: 0.8220
Training random nDCG: 0.3459

Batch (val): 41/41
Validation nDCG: 0.7435
Validation  random nDCG: 0.2906

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: -1.7220, NDCG: 0.6105

Training nDCG: 0.8249
Training random nDCG: 0.3658

Batch (val): 41/41
Validation nDCG: 0.7179
Validation  random nDCG: 0.3284

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: -3.2271, NDCG: 0.4693

Training nDCG: 0.8402
Training random nDCG: 0.3524

Batch (val): 41/41
Validation nDCG: 0.7230
Validation  random nDCG: 0.3239

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: -7.2783, NDCG: 0.4693

Training nDCG: 0.8493
Training random nDCG: 0.3485

Batch (val): 41/41

[I 2026-06-08 17:25:43,850] Trial 0 finished with value: 0.7650281809626173 and parameters: {'learning_rate': 0.00010882324634948818, 'embedding_size': 64, 'pooling_method': 'sum', 'heads': 8}. Best is trial 0 with value: 0.7650281809626173.

Validation nDCG: 0.7160
Validation  random nDCG: 0.3737

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 9
Training for 15 epochs took 1761.32 seconds

    Config:
    - learning_rate = 0.00034079343577705874
    - embedding_size = 8
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.0636, NDCG: 0.2961

Training nDCG: 0.5029
Training random nDCG: 0.3566

Batch (val): 41/41
Validation nDCG: 0.6897
Validation  random nDCG: 0.4017

--> Improvement! Best nDCG: 0.6897
Epoch: 2, Batch: 288/289, Pred Mean: -0.2695, NDCG: 0.4693

Training nDCG: 0.7627
Training random nDCG: 0.3488

Batch (val): 41/41
Validation nDCG: 0.7678
Validation  random nDCG: 0.3595

--> Improvement! Best nDCG: 0.7678
Epoch: 3, Batch: 288/289, Pred Mean: -0.2286, NDCG: 0.4693

Training nDCG: 0.7860
Training random nDCG: 0.3630

Batch (val): 41/41
Validation nDCG: 0.7657
Validation  random nDCG: 0.3336

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.1874, NDCG: 0.4693

Training nDCG: 0.7867
Training random nDCG: 0.3450

Batch (val): 41/41
Validation nDCG: 0.7684
Validation  random nDCG: 0.4271

--> Improvement! Best nDCG: 0.7684
Epoch: 5, Batch: 288/289, Pred Mean: -0.1409, NDCG: 0.4693

Training nDCG: 0.7977
Training random nDCG: 0.3589

Batch (val): 41/41
Validation nDCG: 0.7894
Validation  random nDCG: 0.3302

--> Improvement! Best nDCG: 0.7894
Epoch: 6, Batch: 288/289, Pred Mean: -0.1210, NDCG: 0.4693

Training nDCG: 0.8044
Training random nDCG: 0.3567

Batch (val): 41/41
Validation nDCG: 0.7931
Validation  random nDCG: 0.3673

--> Improvement! Best nDCG: 0.7931
Epoch: 7, Batch: 288/289, Pred Mean: -0.0297, NDCG: 0.6049

Training nDCG: 0.8147
Training random nDCG: 0.3408

Batch (val): 41/41
Validation nDCG: 0.8127
Validation  random nDCG: 0.3430

--> Improvement! Best nDCG: 0.8127
Epoch: 8, Batch: 288/289, Pred Mean: -0.0086, NDCG: 0.4693

Training nDCG: 0.8185
Training random nDCG: 0.3257

Batch (val): 41/41
Validation nDCG: 0.7948
Validation  random nDCG: 0.3442

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.0371, NDCG: 0.7039

Training nDCG: 0.8267
Training random nDCG: 0.3440

Batch (val): 41/41
Validation nDCG: 0.7980
Validation  random nDCG: 0.3435

--> No improvement. Patience: 2/4
Epoch: 10, Batch: 288/289, Pred Mean: 0.0466, NDCG: 0.7654

Training nDCG: 0.8297
Training random nDCG: 0.3355

Batch (val): 41/41
Validation nDCG: 0.7877
Validation  random nDCG: 0.3172

--> No improvement. Patience: 3/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.1414, NDCG: 0.7654

Training nDCG: 0.8410
Training random nDCG: 0.3684

Batch (val): 41/41

[I 2026-06-08 18:22:09,571] Trial 1 finished with value: 0.8126749479061539 and parameters: {'learning_rate': 0.00034079343577705874, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.8126749479061539.

Validation nDCG: 0.7863
Validation  random nDCG: 0.3419

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 11
Training for 15 epochs took 3385.66 seconds

    Config:
    - learning_rate = 0.0002511725459589937
    - embedding_size = 16
    - pooling_method = sum
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 1.6891, NDCG: 0.7654

Training nDCG: 0.4441
Training random nDCG: 0.3363

Batch (val): 41/41
Validation nDCG: 0.6771
Validation  random nDCG: 0.3494

--> Improvement! Best nDCG: 0.6771
Epoch: 2, Batch: 288/289, Pred Mean: -1.9117, NDCG: 0.2346

Training nDCG: 0.6434
Training random nDCG: 0.3421

Batch (val): 41/41
Validation nDCG: 0.6318
Validation  random nDCG: 0.3791

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: -0.8560, NDCG: 0.4693

Training nDCG: 0.7064
Training random nDCG: 0.3456

Batch (val): 41/41
Validation nDCG: 0.7899
Validation  random nDCG: 0.3633

--> Improvement! Best nDCG: 0.7899
Epoch: 4, Batch: 288/289, Pred Mean: -0.9432, NDCG: 0.6714

Training nDCG: 0.7850
Training random nDCG: 0.3449

Batch (val): 41/41
Validation nDCG: 0.7781
Validation  random nDCG: 0.3416

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -1.0649, NDCG: 0.6714

Training nDCG: 0.7997
Training random nDCG: 0.3655

Batch (val): 41/41
Validation nDCG: 0.7549
Validation  random nDCG: 0.3331

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -1.1337, NDCG: 0.7654

Training nDCG: 0.8172
Training random nDCG: 0.3442

Batch (val): 41/41
Validation nDCG: 0.7673
Validation  random nDCG: 0.3443

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: -1.3238, NDCG: 0.9010

Training nDCG: 0.8294
Training random nDCG: 0.3410

Batch (val): 41/41

[I 2026-06-08 18:45:38,625] Trial 2 finished with value: 0.789941134495763 and parameters: {'learning_rate': 0.0002511725459589937, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 2}. Best is trial 1 with value: 0.8126749479061539.

Validation nDCG: 0.7601
Validation  random nDCG: 0.3506

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 1409.00 seconds
Best hyperparameters: {'learning_rate': 0.00034079343577705874, 'embedding_size': 8, 'pooling_method': 'max', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503
30,gemma,structured,False,False,0.000341,8,max,2,7,0.812675

[I 2026-06-08 18:45:41,649] A new study created in memory with name: no-name-7bfd2755-2b28-447c-aa8d-256e32ec7559

Running study for gemma semi-structured with inference=False and isco=False

    Config:
    - learning_rate = 0.007733787707765981
    - embedding_size = 8
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.0839, NDCG: 0.7530

Training nDCG: 0.7760
Training random nDCG: 0.3656

Batch (val): 41/41
Validation nDCG: 0.7771
Validation  random nDCG: 0.3189

--> Improvement! Best nDCG: 0.7771
Epoch: 2, Batch: 288/289, Pred Mean: -0.1064, NDCG: 0.6105

Training nDCG: 0.7952
Training random nDCG: 0.3481

Batch (val): 41/41
Validation nDCG: 0.7796
Validation  random nDCG: 0.3602

--> Improvement! Best nDCG: 0.7796
Epoch: 3, Batch: 288/289, Pred Mean: -0.2483, NDCG: 0.9325

Training nDCG: 0.7958
Training random nDCG: 0.3649

Batch (val): 41/41
Validation nDCG: 0.7850
Validation  random nDCG: 0.3800

--> Improvement! Best nDCG: 0.7850
Epoch: 4, Batch: 288/289, Pred Mean: -0.1686, NDCG: 0.7737

Training nDCG: 0.7950
Training random nDCG: 0.3493

Batch (val): 41/41
Validation nDCG: 0.7790
Validation  random nDCG: 0.3766

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.3500, NDCG: 0.6257

Training nDCG: 0.7990
Training random nDCG: 0.3551

Batch (val): 41/41
Validation nDCG: 0.7713
Validation  random nDCG: 0.3420

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.6495, NDCG: 0.7039

Training nDCG: 0.8056
Training random nDCG: 0.3518

Batch (val): 41/41
Validation nDCG: 0.7815
Validation  random nDCG: 0.3672

--> No improvement. Patience: 3/4
Epoch: 7, Batch: 288/289, Pred Mean: -0.4738, NDCG: 0.7039

Training nDCG: 0.7919
Training random nDCG: 0.3778

Batch (val): 41/41

[I 2026-06-08 19:35:44,992] Trial 0 finished with value: 0.784986800972906 and parameters: {'learning_rate': 0.007733787707765981, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 8}. Best is trial 0 with value: 0.784986800972906.

Validation nDCG: 0.7828
Validation  random nDCG: 0.3783

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 7
Training for 15 epochs took 3003.23 seconds

    Config:
    - learning_rate = 0.009194649924590648
    - embedding_size = 16
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.4230, NDCG: 0.7845

Training nDCG: 0.7544
Training random nDCG: 0.3528

Batch (val): 41/41
Validation nDCG: 0.7898
Validation  random nDCG: 0.3834

--> Improvement! Best nDCG: 0.7898
Epoch: 2, Batch: 288/289, Pred Mean: 0.8243, NDCG: 0.4693

Training nDCG: 0.7954
Training random nDCG: 0.3297

Batch (val): 41/41
Validation nDCG: 0.7677
Validation  random nDCG: 0.3775

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 0.8062, NDCG: 0.4693

Training nDCG: 0.7873
Training random nDCG: 0.3512

Batch (val): 41/41
Validation nDCG: 0.7490
Validation  random nDCG: 0.3545

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.6791, NDCG: 0.6257

Training nDCG: 0.7974
Training random nDCG: 0.3548

Batch (val): 41/41
Validation nDCG: 0.7977
Validation  random nDCG: 0.3500

--> Improvement! Best nDCG: 0.7977
Epoch: 5, Batch: 288/289, Pred Mean: -0.8439, NDCG: 0.7670

Training nDCG: 0.7908
Training random nDCG: 0.3709

Batch (val): 41/41
Validation nDCG: 0.7822
Validation  random nDCG: 0.4314

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.8049, NDCG: 0.7845

Training nDCG: 0.7985
Training random nDCG: 0.3597

Batch (val): 41/41
Validation nDCG: 0.7917
Validation  random nDCG: 0.3307

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 1.1804, NDCG: 0.6257

Training nDCG: 0.7920
Training random nDCG: 0.3312

Batch (val): 41/41
Validation nDCG: 0.7851
Validation  random nDCG: 0.3033

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 1.5673, NDCG: 0.7929

Training nDCG: 0.7882
Training random nDCG: 0.3704

Batch (val): 41/41

[I 2026-06-08 20:12:27,776] Trial 1 finished with value: 0.7977224680828553 and parameters: {'learning_rate': 0.009194649924590648, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 4}. Best is trial 1 with value: 0.7977224680828553.

Validation nDCG: 0.7822
Validation  random nDCG: 0.3654

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 2202.72 seconds

    Config:
    - learning_rate = 0.00039041954784827323
    - embedding_size = 8
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.4581, NDCG: 0.2961

Training nDCG: 0.3916
Training random nDCG: 0.3405

Batch (val): 41/41
Validation nDCG: 0.5498
Validation  random nDCG: 0.2565

--> Improvement! Best nDCG: 0.5498
Epoch: 2, Batch: 288/289, Pred Mean: 0.0704, NDCG: 0.6049

Training nDCG: 0.6038
Training random nDCG: 0.3648

Batch (val): 41/41
Validation nDCG: 0.6211
Validation  random nDCG: 0.2958

--> Improvement! Best nDCG: 0.6211
Epoch: 3, Batch: 288/289, Pred Mean: -0.5602, NDCG: 0.4693

Training nDCG: 0.6633
Training random nDCG: 0.3390

Batch (val): 41/41
Validation nDCG: 0.7602
Validation  random nDCG: 0.3168

--> Improvement! Best nDCG: 0.7602
Epoch: 4, Batch: 288/289, Pred Mean: -0.6881, NDCG: 0.4693

Training nDCG: 0.7639
Training random nDCG: 0.3611

Batch (val): 41/41
Validation nDCG: 0.7623
Validation  random nDCG: 0.3542

--> Improvement! Best nDCG: 0.7623
Epoch: 5, Batch: 288/289, Pred Mean: -0.7848, NDCG: 0.4693

Training nDCG: 0.7867
Training random nDCG: 0.3285

Batch (val): 41/41
Validation nDCG: 0.7872
Validation  random nDCG: 0.3615

--> Improvement! Best nDCG: 0.7872
Epoch: 6, Batch: 288/289, Pred Mean: -0.8580, NDCG: 0.4693

Training nDCG: 0.8019
Training random nDCG: 0.3568

Batch (val): 41/41
Validation nDCG: 0.7881
Validation  random nDCG: 0.2846

--> Improvement! Best nDCG: 0.7881
Epoch: 7, Batch: 288/289, Pred Mean: -0.9782, NDCG: 0.4693

Training nDCG: 0.8125
Training random nDCG: 0.3422

Batch (val): 41/41
Validation nDCG: 0.7812
Validation  random nDCG: 0.2895

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: -1.0040, NDCG: 0.4693

Training nDCG: 0.8178
Training random nDCG: 0.3508

Batch (val): 41/41
Validation nDCG: 0.7847
Validation  random nDCG: 0.3815

--> No improvement. Patience: 2/4
Epoch: 9, Batch: 288/289, Pred Mean: -1.1879, NDCG: 0.4693

Training nDCG: 0.8355
Training random nDCG: 0.3601

Batch (val): 41/41
Validation nDCG: 0.7422
Validation  random nDCG: 0.2852

--> No improvement. Patience: 3/4
Epoch: 10, Batch: 288/289, Pred Mean: -1.2294, NDCG: 0.4693

Training nDCG: 0.8380
Training random nDCG: 0.3454

Batch (val): 41/41

[I 2026-06-08 20:51:25,141] Trial 2 finished with value: 0.7880672766808651 and parameters: {'learning_rate': 0.00039041954784827323, 'embedding_size': 8, 'pooling_method': 'sum', 'heads': 4}. Best is trial 1 with value: 0.7977224680828553.

Validation nDCG: 0.7774
Validation  random nDCG: 0.4371

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 10
Training for 15 epochs took 2337.05 seconds
Best hyperparameters: {'learning_rate': 0.009194649924590648, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503
30,gemma,structured,False,False,0.000341,8,max,2,7,0.812675
31,gemma,semi-structured,False,False,0.009195,16,sum,4,4,0.797722

[I 2026-06-08 20:51:29,812] A new study created in memory with name: no-name-85df94e6-823f-4bee-9e20-e4432a8bba50

Running study for gemma unstructured with inference=False and isco=False

    Config:
    - learning_rate = 0.00046365907442957085
    - embedding_size = 32
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -1.4222, NDCG: 0.6105

Training nDCG: 0.5389
Training random nDCG: 0.3428

Batch (val): 41/41
Validation nDCG: 0.6480
Validation  random nDCG: 0.3491

--> Improvement! Best nDCG: 0.6480
Epoch: 2, Batch: 288/289, Pred Mean: -1.7222, NDCG: 0.4693

Training nDCG: 0.7272
Training random nDCG: 0.3569

Batch (val): 41/41
Validation nDCG: 0.7655
Validation  random nDCG: 0.3766

--> Improvement! Best nDCG: 0.7655
Epoch: 3, Batch: 288/289, Pred Mean: -1.2305, NDCG: 0.6105

Training nDCG: 0.7686
Training random nDCG: 0.3448

Batch (val): 41/41
Validation nDCG: 0.7609
Validation  random nDCG: 0.3607

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.6059, NDCG: 0.6714

Training nDCG: 0.7736
Training random nDCG: 0.3480

Batch (val): 41/41
Validation nDCG: 0.5891
Validation  random nDCG: 0.3511

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.0725, NDCG: 0.8070

Training nDCG: 0.7871
Training random nDCG: 0.3634

Batch (val): 41/41
Validation nDCG: 0.5534
Validation  random nDCG: 0.3261

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.0199, NDCG: 0.9010

Training nDCG: 0.7906
Training random nDCG: 0.3471

Batch (val): 41/41

[I 2026-06-08 21:25:49,136] Trial 0 finished with value: 0.7655073268308974 and parameters: {'learning_rate': 0.00046365907442957085, 'embedding_size': 32, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.7655073268308974.

Validation nDCG: 0.6044
Validation  random nDCG: 0.4131

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 2059.19 seconds

    Config:
    - learning_rate = 0.00018934563466095513
    - embedding_size = 64
    - pooling_method = mean
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.0745, NDCG: 0.4693

Training nDCG: 0.7150
Training random nDCG: 0.3456

Batch (val): 41/41
Validation nDCG: 0.7240
Validation  random nDCG: 0.3526

--> Improvement! Best nDCG: 0.7240
Epoch: 2, Batch: 288/289, Pred Mean: 0.1357, NDCG: 0.4693

Training nDCG: 0.7720
Training random nDCG: 0.3383

Batch (val): 41/41
Validation nDCG: 0.7643
Validation  random nDCG: 0.3734

--> Improvement! Best nDCG: 0.7643
Epoch: 3, Batch: 288/289, Pred Mean: 0.1686, NDCG: 0.4693

Training nDCG: 0.7916
Training random nDCG: 0.3276

Batch (val): 41/41
Validation nDCG: 0.7610
Validation  random nDCG: 0.4913

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.1703, NDCG: 0.4693

Training nDCG: 0.8012
Training random nDCG: 0.3440

Batch (val): 41/41
Validation nDCG: 0.7784
Validation  random nDCG: 0.3084

--> Improvement! Best nDCG: 0.7784
Epoch: 5, Batch: 288/289, Pred Mean: 0.1966, NDCG: 0.4693

Training nDCG: 0.8140
Training random nDCG: 0.3377

Batch (val): 41/41
Validation nDCG: 0.7397
Validation  random nDCG: 0.3033

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.2354, NDCG: 0.6508

Training nDCG: 0.8117
Training random nDCG: 0.3784

Batch (val): 41/41
Validation nDCG: 0.7777
Validation  random nDCG: 0.2915

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.3002, NDCG: 0.6508

Training nDCG: 0.8073
Training random nDCG: 0.3673

Batch (val): 41/41
Validation nDCG: 0.7571
Validation  random nDCG: 0.3030

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.4174, NDCG: 0.6364

Training nDCG: 0.8119
Training random nDCG: 0.3820

Batch (val): 41/41

[I 2026-06-08 22:12:00,155] Trial 1 finished with value: 0.7783929293890244 and parameters: {'learning_rate': 0.00018934563466095513, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 2}. Best is trial 1 with value: 0.7783929293890244.

Validation nDCG: 0.7573
Validation  random nDCG: 0.3840

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 2770.92 seconds

    Config:
    - learning_rate = 0.0049189509664071575
    - embedding_size = 8
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.2480, NDCG: 0.6714

Training nDCG: 0.7776
Training random nDCG: 0.3439

Batch (val): 41/41
Validation nDCG: 0.7531
Validation  random nDCG: 0.3420

--> Improvement! Best nDCG: 0.7531
Epoch: 2, Batch: 288/289, Pred Mean: 0.3968, NDCG: 0.6257

Training nDCG: 0.8113
Training random nDCG: 0.3671

Batch (val): 41/41
Validation nDCG: 0.7614
Validation  random nDCG: 0.3427

--> Improvement! Best nDCG: 0.7614
Epoch: 3, Batch: 288/289, Pred Mean: 0.4965, NDCG: 0.9675

Training nDCG: 0.8192
Training random nDCG: 0.3527

Batch (val): 41/41
Validation nDCG: 0.7600
Validation  random nDCG: 0.3285

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.3722, NDCG: 0.7654

Training nDCG: 0.8234
Training random nDCG: 0.3761

Batch (val): 41/41
Validation nDCG: 0.7569
Validation  random nDCG: 0.3616

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.5028, NDCG: 0.6257

Training nDCG: 0.8251
Training random nDCG: 0.3617

Batch (val): 41/41
Validation nDCG: 0.7637
Validation  random nDCG: 0.4282

--> Improvement! Best nDCG: 0.7637
Epoch: 6, Batch: 288/289, Pred Mean: 0.3575, NDCG: 0.4693

Training nDCG: 0.8296
Training random nDCG: 0.3264

Batch (val): 41/41
Validation nDCG: 0.7646
Validation  random nDCG: 0.3348

--> Improvement! Best nDCG: 0.7646
Epoch: 7, Batch: 288/289, Pred Mean: 0.1839, NDCG: 0.4693

Training nDCG: 0.8313
Training random nDCG: 0.3494

Batch (val): 41/41
Validation nDCG: 0.7843
Validation  random nDCG: 0.3508

--> Improvement! Best nDCG: 0.7843
Epoch: 8, Batch: 288/289, Pred Mean: 0.0978, NDCG: 0.4693

Training nDCG: 0.8374
Training random nDCG: 0.3648

Batch (val): 41/41
Validation nDCG: 0.7878
Validation  random nDCG: 0.3308

--> Improvement! Best nDCG: 0.7878
Epoch: 9, Batch: 288/289, Pred Mean: 0.3384, NDCG: 0.4693

Training nDCG: 0.8403
Training random nDCG: 0.3636

Batch (val): 41/41
Validation nDCG: 0.7581
Validation  random nDCG: 0.3075

--> No improvement. Patience: 1/4
Epoch: 10, Batch: 288/289, Pred Mean: 0.5772, NDCG: 0.4693

Training nDCG: 0.8369
Training random nDCG: 0.3364

Batch (val): 41/41
Validation nDCG: 0.7690
Validation  random nDCG: 0.4116

--> No improvement. Patience: 2/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.9435, NDCG: 0.4693

Training nDCG: 0.8423
Training random nDCG: 0.3568

Batch (val): 41/41
Validation nDCG: 0.7819
Validation  random nDCG: 0.3620

--> No improvement. Patience: 3/4
Epoch: 12, Batch: 288/289, Pred Mean: 0.6808, NDCG: 0.4693

Training nDCG: 0.8376
Training random nDCG: 0.3430

Batch (val): 41/41

[I 2026-06-08 23:21:11,158] Trial 2 finished with value: 0.7877834147654169 and parameters: {'learning_rate': 0.0049189509664071575, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 4}. Best is trial 2 with value: 0.7877834147654169.

Validation nDCG: 0.7731
Validation  random nDCG: 0.4013

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 12
Training for 15 epochs took 4150.92 seconds
Best hyperparameters: {'learning_rate': 0.0049189509664071575, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503
30,gemma,structured,False,False,0.000341,8,max,2,7,0.812675
31,gemma,semi-structured,False,False,0.009195,16,sum,4,4,0.797722
32,gemma,unstructured,False,False,0.004919,8,mean,4,8,0.787783

[I 2026-06-08 23:21:12,958] A new study created in memory with name: no-name-15c7b68a-596b-45eb-8e54-40c8b39dbb47

Running study for llama structured with inference=False and isco=False

    Config:
    - learning_rate = 0.005545139402660382
    - embedding_size = 16
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.0314, NDCG: 0.4693

Training nDCG: 0.7728
Training random nDCG: 0.3538

Batch (val): 41/41
Validation nDCG: 0.7684
Validation  random nDCG: 0.3387

--> Improvement! Best nDCG: 0.7684
Epoch: 2, Batch: 288/289, Pred Mean: -0.1052, NDCG: 0.4693

Training nDCG: 0.8014
Training random nDCG: 0.3443

Batch (val): 41/41
Validation nDCG: 0.7751
Validation  random nDCG: 0.3928

--> Improvement! Best nDCG: 0.7751
Epoch: 3, Batch: 288/289, Pred Mean: -0.4219, NDCG: 0.4693

Training nDCG: 0.7970
Training random nDCG: 0.3500

Batch (val): 41/41
Validation nDCG: 0.7592
Validation  random nDCG: 0.4066

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.5198, NDCG: 0.4693

Training nDCG: 0.8021
Training random nDCG: 0.3408

Batch (val): 41/41
Validation nDCG: 0.7824
Validation  random nDCG: 0.3348

--> Improvement! Best nDCG: 0.7824
Epoch: 5, Batch: 288/289, Pred Mean: -1.0433, NDCG: 0.4693

Training nDCG: 0.8032
Training random nDCG: 0.3369

Batch (val): 41/41
Validation nDCG: 0.7727
Validation  random nDCG: 0.3732

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: -1.7068, NDCG: 0.4693

Training nDCG: 0.8109
Training random nDCG: 0.3679

Batch (val): 41/41
Validation nDCG: 0.7719
Validation  random nDCG: 0.3134

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: -1.7471, NDCG: 0.6173

Training nDCG: 0.8088
Training random nDCG: 0.3603

Batch (val): 41/41
Validation nDCG: 0.7937
Validation  random nDCG: 0.2866

--> Improvement! Best nDCG: 0.7937
Epoch: 8, Batch: 288/289, Pred Mean: -2.1313, NDCG: 0.6257

Training nDCG: 0.8141
Training random nDCG: 0.3667

Batch (val): 41/41
Validation nDCG: 0.7817
Validation  random nDCG: 0.3506

--> No improvement. Patience: 1/4
Epoch: 9, Batch: 288/289, Pred Mean: -2.3914, NDCG: 0.7670

Training nDCG: 0.8167
Training random nDCG: 0.3209

Batch (val): 41/41
Validation nDCG: 0.8055
Validation  random nDCG: 0.3670

--> Improvement! Best nDCG: 0.8055
Epoch: 10, Batch: 288/289, Pred Mean: -2.9536, NDCG: 0.6364

Training nDCG: 0.8178
Training random nDCG: 0.3315

Batch (val): 41/41
Validation nDCG: 0.7908
Validation  random nDCG: 0.3864

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: -3.2819, NDCG: 0.6714

Training nDCG: 0.8194
Training random nDCG: 0.3497

Batch (val): 41/41
Validation nDCG: 0.7843
Validation  random nDCG: 0.3473

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: -3.6575, NDCG: 0.6257

Training nDCG: 0.8226
Training random nDCG: 0.3525

Batch (val): 41/41
Validation nDCG: 0.7763
Validation  random nDCG: 0.3392

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: -3.2739, NDCG: 0.6364

Training nDCG: 0.8175
Training random nDCG: 0.3331

Batch (val): 41/41

[I 2026-06-09 00:05:22,774] Trial 0 finished with value: 0.8054916140867368 and parameters: {'learning_rate': 0.005545139402660382, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.8054916140867368.

Validation nDCG: 0.7916
Validation  random nDCG: 0.3310

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 2649.64 seconds

    Config:
    - learning_rate = 0.002735957336540818
    - embedding_size = 16
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.2539, NDCG: 0.7654

Training nDCG: 0.7336
Training random nDCG: 0.3753

Batch (val): 41/41
Validation nDCG: 0.7896
Validation  random nDCG: 0.3873

--> Improvement! Best nDCG: 0.7896
Epoch: 2, Batch: 288/289, Pred Mean: -0.5305, NDCG: 0.6257

Training nDCG: 0.7865
Training random nDCG: 0.3501

Batch (val): 41/41
Validation nDCG: 0.8079
Validation  random nDCG: 0.3963

--> Improvement! Best nDCG: 0.8079
Epoch: 3, Batch: 288/289, Pred Mean: -0.9148, NDCG: 0.6257

Training nDCG: 0.7979
Training random nDCG: 0.3691

Batch (val): 41/41
Validation nDCG: 0.7785
Validation  random nDCG: 0.3590

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -1.1972, NDCG: 0.9066

Training nDCG: 0.7931
Training random nDCG: 0.3401

Batch (val): 41/41
Validation nDCG: 0.8031
Validation  random nDCG: 0.3677

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: -0.3579, NDCG: 0.7654

Training nDCG: 0.7971
Training random nDCG: 0.3348

Batch (val): 41/41
Validation nDCG: 0.7772
Validation  random nDCG: 0.3389

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: -0.5668, NDCG: 0.6173

Training nDCG: 0.8014
Training random nDCG: 0.3439

Batch (val): 41/41

[I 2026-06-09 00:26:48,653] Trial 1 finished with value: 0.8078923246572384 and parameters: {'learning_rate': 0.002735957336540818, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}. Best is trial 1 with value: 0.8078923246572384.

Validation nDCG: 0.7688
Validation  random nDCG: 0.3046

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 1285.82 seconds

    Config:
    - learning_rate = 0.00016817190106102205
    - embedding_size = 8
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.0393, NDCG: 0.6173

Training nDCG: 0.5582
Training random nDCG: 0.3637

Batch (val): 41/41
Validation nDCG: 0.7541
Validation  random nDCG: 0.3642

--> Improvement! Best nDCG: 0.7541
Epoch: 2, Batch: 288/289, Pred Mean: -0.0284, NDCG: 0.6049

Training nDCG: 0.7617
Training random nDCG: 0.3467

Batch (val): 41/41
Validation nDCG: 0.7688
Validation  random nDCG: 0.3570

--> Improvement! Best nDCG: 0.7688
Epoch: 3, Batch: 288/289, Pred Mean: -0.0194, NDCG: 0.6105

Training nDCG: 0.7723
Training random nDCG: 0.3457

Batch (val): 41/41
Validation nDCG: 0.7702
Validation  random nDCG: 0.2928

--> Improvement! Best nDCG: 0.7702
Epoch: 4, Batch: 288/289, Pred Mean: -0.0102, NDCG: 0.7614

Training nDCG: 0.7818
Training random nDCG: 0.3510

Batch (val): 41/41
Validation nDCG: 0.7671
Validation  random nDCG: 0.3626

--> No improvement. Patience: 1/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.0015, NDCG: 0.6173

Training nDCG: 0.7941
Training random nDCG: 0.3489

Batch (val): 41/41
Validation nDCG: 0.7678
Validation  random nDCG: 0.3128

--> No improvement. Patience: 2/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.0118, NDCG: 0.6364

Training nDCG: 0.7952
Training random nDCG: 0.3560

Batch (val): 41/41
Validation nDCG: 0.7775
Validation  random nDCG: 0.3065

--> Improvement! Best nDCG: 0.7775
Epoch: 7, Batch: 288/289, Pred Mean: 0.0215, NDCG: 0.6508

Training nDCG: 0.8009
Training random nDCG: 0.3577

Batch (val): 41/41
Validation nDCG: 0.7749
Validation  random nDCG: 0.3285

--> No improvement. Patience: 1/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.0271, NDCG: 0.6364

Training nDCG: 0.8006
Training random nDCG: 0.3716

Batch (val): 41/41
Validation nDCG: 0.7780
Validation  random nDCG: 0.3153

--> Improvement! Best nDCG: 0.7780
Epoch: 9, Batch: 288/289, Pred Mean: 0.0342, NDCG: 0.6364

Training nDCG: 0.8088
Training random nDCG: 0.3447

Batch (val): 41/41
Validation nDCG: 0.7851
Validation  random nDCG: 0.2951

--> Improvement! Best nDCG: 0.7851
Epoch: 10, Batch: 288/289, Pred Mean: 0.0385, NDCG: 0.6714

Training nDCG: 0.8115
Training random nDCG: 0.3544

Batch (val): 41/41
Validation nDCG: 0.7859
Validation  random nDCG: 0.3745

--> Improvement! Best nDCG: 0.7859
Epoch: 11, Batch: 288/289, Pred Mean: 0.0422, NDCG: 0.6714

Training nDCG: 0.8121
Training random nDCG: 0.3552

Batch (val): 41/41
Validation nDCG: 0.7762
Validation  random nDCG: 0.3860

--> No improvement. Patience: 1/4
Epoch: 12, Batch: 288/289, Pred Mean: 0.0461, NDCG: 0.6714

Training nDCG: 0.8125
Training random nDCG: 0.3594

Batch (val): 41/41
Validation nDCG: 0.7831
Validation  random nDCG: 0.3422

--> No improvement. Patience: 2/4
Epoch: 13, Batch: 288/289, Pred Mean: 0.0535, NDCG: 0.7039

Training nDCG: 0.8214
Training random nDCG: 0.3387

Batch (val): 41/41
Validation nDCG: 0.7914
Validation  random nDCG: 0.3884

--> Improvement! Best nDCG: 0.7914
Epoch: 14, Batch: 288/289, Pred Mean: 0.0661, NDCG: 0.7039

Training nDCG: 0.8205
Training random nDCG: 0.3662

Batch (val): 41/41
Validation nDCG: 0.7740
Validation  random nDCG: 0.2983

--> No improvement. Patience: 1/4
Epoch: 15, Batch: 288/289, Pred Mean: 0.0824, NDCG: 0.7654

Training nDCG: 0.8227
Training random nDCG: 0.3373

Batch (val): 41/41

[I 2026-06-09 01:27:26,927] Trial 2 finished with value: 0.7913527533647365 and parameters: {'learning_rate': 0.00016817190106102205, 'embedding_size': 8, 'pooling_method': 'mean', 'heads': 4}. Best is trial 1 with value: 0.8078923246572384.

Validation nDCG: 0.7616
Validation  random nDCG: 0.3759

--> No improvement. Patience: 2/4
Training for 15 epochs took 3638.22 seconds
Best hyperparameters: {'learning_rate': 0.002735957336540818, 'embedding_size': 16, 'pooling_method': 'max', 'heads': 2}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503
30,gemma,structured,False,False,0.000341,8,max,2,7,0.812675
31,gemma,semi-structured,False,False,0.009195,16,sum,4,4,0.797722
32,gemma,unstructured,False,False,0.004919,8,mean,4,8,0.787783
33,llama,structured,False,False,0.002736,16,max,2,2,0.807892

[I 2026-06-09 01:27:29,312] A new study created in memory with name: no-name-44af18a0-315d-40f1-9c61-63459a0cd27e

Running study for llama semi-structured with inference=False and isco=False

    Config:
    - learning_rate = 0.006970830319967575
    - embedding_size = 128
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -1.2176, NDCG: 0.6173

Training nDCG: 0.7425
Training random nDCG: 0.3459

Batch (val): 41/41
Validation nDCG: 0.8154
Validation  random nDCG: 0.4119

--> Improvement! Best nDCG: 0.8154
Epoch: 2, Batch: 288/289, Pred Mean: -0.8051, NDCG: 0.6257

Training nDCG: 0.7888
Training random nDCG: 0.3386

Batch (val): 41/41
Validation nDCG: 0.7791
Validation  random nDCG: 0.2785

--> No improvement. Patience: 1/4
Epoch: 3, Batch: 288/289, Pred Mean: 4.4677, NDCG: 0.4693

Training nDCG: 0.7963
Training random nDCG: 0.3618

Batch (val): 41/41
Validation nDCG: 0.8112
Validation  random nDCG: 0.3703

--> No improvement. Patience: 2/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.3894, NDCG: 0.4693

Training nDCG: 0.7917
Training random nDCG: 0.3521

Batch (val): 41/41
Validation nDCG: 0.8084
Validation  random nDCG: 0.3712

--> No improvement. Patience: 3/4
Epoch: 5, Batch: 288/289, Pred Mean: -6.3112, NDCG: 0.6508

Training nDCG: 0.7895
Training random nDCG: 0.3673

Batch (val): 41/41

[I 2026-06-09 01:45:06,723] Trial 0 finished with value: 0.8153776031372499 and parameters: {'learning_rate': 0.006970830319967575, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.8153776031372499.

Validation nDCG: 0.7759
Validation  random nDCG: 0.3660

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 5
Training for 15 epochs took 1057.30 seconds

    Config:
    - learning_rate = 0.0001051996160894034
    - embedding_size = 64
    - pooling_method = max
    - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.5998, NDCG: 0.6508

Training nDCG: 0.6670
Training random nDCG: 0.3544

Batch (val): 41/41
Validation nDCG: 0.7756
Validation  random nDCG: 0.4094

--> Improvement! Best nDCG: 0.7756
Epoch: 2, Batch: 288/289, Pred Mean: -0.4864, NDCG: 0.4693

Training nDCG: 0.7762
Training random nDCG: 0.3552

Batch (val): 41/41
Validation nDCG: 0.7999
Validation  random nDCG: 0.3657

--> Improvement! Best nDCG: 0.7999
Epoch: 3, Batch: 288/289, Pred Mean: -0.4670, NDCG: 0.8194

Training nDCG: 0.8013
Training random nDCG: 0.3595

Batch (val): 41/41
Validation nDCG: 0.7610
Validation  random nDCG: 0.3449

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: -0.3172, NDCG: 0.8520

Training nDCG: 0.8157
Training random nDCG: 0.3289

Batch (val): 41/41
Validation nDCG: 0.7814
Validation  random nDCG: 0.3404

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.1238, NDCG: 0.8529

Training nDCG: 0.8324
Training random nDCG: 0.3436

Batch (val): 41/41
Validation nDCG: 0.7777
Validation  random nDCG: 0.2933

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.1059, NDCG: 0.8180

Training nDCG: 0.8272
Training random nDCG: 0.3440

Batch (val): 41/41

[I 2026-06-09 02:04:53,418] Trial 1 finished with value: 0.7998632784427104 and parameters: {'learning_rate': 0.0001051996160894034, 'embedding_size': 64, 'pooling_method': 'max', 'heads': 2}. Best is trial 0 with value: 0.8153776031372499.

Validation nDCG: 0.7657
Validation  random nDCG: 0.3694

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 1186.65 seconds

    Config:
    - learning_rate = 0.0025774229491558657
    - embedding_size = 16
    - pooling_method = sum
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: -0.9310, NDCG: 0.6049

Training nDCG: 0.6565
Training random nDCG: 0.3640

Batch (val): 41/41
Validation nDCG: 0.7850
Validation  random nDCG: 0.3714

--> Improvement! Best nDCG: 0.7850
Epoch: 2, Batch: 288/289, Pred Mean: -1.0805, NDCG: 0.6364

Training nDCG: 0.7819
Training random nDCG: 0.3578

Batch (val): 41/41
Validation nDCG: 0.7872
Validation  random nDCG: 0.3423

--> Improvement! Best nDCG: 0.7872
Epoch: 3, Batch: 288/289, Pred Mean: -0.5948, NDCG: 0.4693

Training nDCG: 0.7884
Training random nDCG: 0.3609

Batch (val): 41/41
Validation nDCG: 0.8048
Validation  random nDCG: 0.3675

--> Improvement! Best nDCG: 0.8048
Epoch: 4, Batch: 288/289, Pred Mean: -0.4740, NDCG: 0.6049

Training nDCG: 0.7926
Training random nDCG: 0.3485

Batch (val): 41/41
Validation nDCG: 0.8050
Validation  random nDCG: 0.3091

--> Improvement! Best nDCG: 0.8050
Epoch: 5, Batch: 288/289, Pred Mean: -0.3477, NDCG: 0.6364

Training nDCG: 0.7955
Training random nDCG: 0.3466

Batch (val): 41/41
Validation nDCG: 0.7833
Validation  random nDCG: 0.3437

--> No improvement. Patience: 1/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.4955, NDCG: 0.4693

Training nDCG: 0.7893
Training random nDCG: 0.3469

Batch (val): 41/41
Validation nDCG: 0.7983
Validation  random nDCG: 0.3312

--> No improvement. Patience: 2/4
Epoch: 7, Batch: 288/289, Pred Mean: -0.3293, NDCG: 0.6049

Training nDCG: 0.7935
Training random nDCG: 0.3549

Batch (val): 41/41
Validation nDCG: 0.7907
Validation  random nDCG: 0.3114

--> No improvement. Patience: 3/4
Epoch: 8, Batch: 288/289, Pred Mean: -0.7607, NDCG: 0.7039

Training nDCG: 0.7979
Training random nDCG: 0.3621

Batch (val): 41/41

[I 2026-06-09 02:31:11,614] Trial 2 finished with value: 0.8049601832096713 and parameters: {'learning_rate': 0.0025774229491558657, 'embedding_size': 16, 'pooling_method': 'sum', 'heads': 4}. Best is trial 0 with value: 0.8153776031372499.

Validation nDCG: 0.7817
Validation  random nDCG: 0.3305

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 8
Training for 15 epochs took 1578.14 seconds
Best hyperparameters: {'learning_rate': 0.006970830319967575, 'embedding_size': 128, 'pooling_method': 'sum', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503
30,gemma,structured,False,False,0.000341,8,max,2,7,0.812675
31,gemma,semi-structured,False,False,0.009195,16,sum,4,4,0.797722
32,gemma,unstructured,False,False,0.004919,8,mean,4,8,0.787783
33,llama,structured,False,False,0.002736,16,max,2,2,0.807892
34,llama,semi-structured,False,False,0.006971,128,sum,4,1,0.815378

[I 2026-06-09 02:31:15,250] A new study created in memory with name: no-name-1c283fbb-faa9-481f-99c6-cdec180ba830

Running study for llama unstructured with inference=False and isco=False

    Config:
    - learning_rate = 0.00018759531311140836
    - embedding_size = 64
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.0799, NDCG: 0.6173

Training nDCG: 0.6640
Training random nDCG: 0.3730

Batch (val): 41/41
Validation nDCG: 0.7582
Validation  random nDCG: 0.2998

--> Improvement! Best nDCG: 0.7582
Epoch: 2, Batch: 288/289, Pred Mean: 0.1363, NDCG: 0.6714

Training nDCG: 0.7709
Training random nDCG: 0.3563

Batch (val): 41/41
Validation nDCG: 0.7709
Validation  random nDCG: 0.3515

--> Improvement! Best nDCG: 0.7709
Epoch: 3, Batch: 288/289, Pred Mean: 0.1813, NDCG: 0.6508

Training nDCG: 0.7885
Training random nDCG: 0.3700

Batch (val): 41/41
Validation nDCG: 0.7668
Validation  random nDCG: 0.3583

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.2120, NDCG: 0.7777

Training nDCG: 0.7983
Training random nDCG: 0.3837

Batch (val): 41/41
Validation nDCG: 0.7695
Validation  random nDCG: 0.3783

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.2190, NDCG: 0.8278

Training nDCG: 0.8033
Training random nDCG: 0.3601

Batch (val): 41/41
Validation nDCG: 0.7592
Validation  random nDCG: 0.3686

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.2165, NDCG: 0.9675

Training nDCG: 0.8054
Training random nDCG: 0.3596

Batch (val): 41/41

[I 2026-06-09 02:55:09,845] Trial 0 finished with value: 0.7708570151567361 and parameters: {'learning_rate': 0.00018759531311140836, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 4}. Best is trial 0 with value: 0.7708570151567361.

Validation nDCG: 0.7458
Validation  random nDCG: 0.3356

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 1434.47 seconds

    Config:
    - learning_rate = 0.0006217308603403987
    - embedding_size = 64
    - pooling_method = mean
    - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.1758, NDCG: 0.4693

Training nDCG: 0.7419
Training random nDCG: 0.3498

Batch (val): 41/41
Validation nDCG: 0.7715
Validation  random nDCG: 0.3314

--> Improvement! Best nDCG: 0.7715
Epoch: 2, Batch: 288/289, Pred Mean: 0.2857, NDCG: 0.4693

Training nDCG: 0.7859
Training random nDCG: 0.3691

Batch (val): 41/41
Validation nDCG: 0.7767
Validation  random nDCG: 0.3005

--> Improvement! Best nDCG: 0.7767
Epoch: 3, Batch: 288/289, Pred Mean: 0.2929, NDCG: 0.4693

Training nDCG: 0.7896
Training random nDCG: 0.3659

Batch (val): 41/41
Validation nDCG: 0.7727
Validation  random nDCG: 0.3882

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.2896, NDCG: 0.4693

Training nDCG: 0.7995
Training random nDCG: 0.3500

Batch (val): 41/41
Validation nDCG: 0.7847
Validation  random nDCG: 0.3364

--> Improvement! Best nDCG: 0.7847
Epoch: 5, Batch: 288/289, Pred Mean: 0.1680, NDCG: 0.6049

Training nDCG: 0.7999
Training random nDCG: 0.3338

Batch (val): 41/41
Validation nDCG: 0.7851
Validation  random nDCG: 0.3277

--> Improvement! Best nDCG: 0.7851
Epoch: 6, Batch: 288/289, Pred Mean: 0.0766, NDCG: 0.4693

Training nDCG: 0.7986
Training random nDCG: 0.3415

Batch (val): 41/41
Validation nDCG: 0.7789
Validation  random nDCG: 0.3215

--> No improvement. Patience: 1/4
Epoch: 7, Batch: 288/289, Pred Mean: 0.0988, NDCG: 0.6257

Training nDCG: 0.8136
Training random nDCG: 0.3439

Batch (val): 41/41
Validation nDCG: 0.7768
Validation  random nDCG: 0.3979

--> No improvement. Patience: 2/4
Epoch: 8, Batch: 288/289, Pred Mean: 0.0797, NDCG: 0.6714

Training nDCG: 0.8180
Training random nDCG: 0.3703

Batch (val): 41/41
Validation nDCG: 0.7819
Validation  random nDCG: 0.3534

--> No improvement. Patience: 3/4
Epoch: 9, Batch: 288/289, Pred Mean: 0.0418, NDCG: 0.7039

Training nDCG: 0.8316
Training random nDCG: 0.3620

Batch (val): 41/41
Validation nDCG: 0.7880
Validation  random nDCG: 0.3168

--> Improvement! Best nDCG: 0.7880
Epoch: 10, Batch: 288/289, Pred Mean: 0.1491, NDCG: 0.7039

Training nDCG: 0.8266
Training random nDCG: 0.3731

Batch (val): 41/41
Validation nDCG: 0.7526
Validation  random nDCG: 0.3833

--> No improvement. Patience: 1/4
Epoch: 11, Batch: 288/289, Pred Mean: 0.0492, NDCG: 0.7654

Training nDCG: 0.8325
Training random nDCG: 0.3383

Batch (val): 41/41
Validation nDCG: 0.7221
Validation  random nDCG: 0.3037

--> No improvement. Patience: 2/4
Epoch: 12, Batch: 288/289, Pred Mean: 0.0591, NDCG: 0.8396

Training nDCG: 0.8367
Training random nDCG: 0.3492

Batch (val): 41/41
Validation nDCG: 0.7243
Validation  random nDCG: 0.3991

--> No improvement. Patience: 3/4
Epoch: 13, Batch: 288/289, Pred Mean: -0.0643, NDCG: 0.8520

Training nDCG: 0.8454
Training random nDCG: 0.3511

Batch (val): 41/41

[I 2026-06-09 03:47:13,358] Trial 1 finished with value: 0.7879744444025734 and parameters: {'learning_rate': 0.0006217308603403987, 'embedding_size': 64, 'pooling_method': 'mean', 'heads': 8}. Best is trial 1 with value: 0.7879744444025734.

Validation nDCG: 0.7621
Validation  random nDCG: 0.3392

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 13
Training for 15 epochs took 3123.42 seconds

    Config:
    - learning_rate = 0.0007506733115176721
    - embedding_size = 16
    - pooling_method = mean
    - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.0349, NDCG: 0.6714

Training nDCG: 0.6800
Training random nDCG: 0.3597

Batch (val): 41/41
Validation nDCG: 0.7738
Validation  random nDCG: 0.4045

--> Improvement! Best nDCG: 0.7738
Epoch: 2, Batch: 288/289, Pred Mean: 0.1572, NDCG: 0.6257

Training nDCG: 0.7816
Training random nDCG: 0.3673

Batch (val): 41/41
Validation nDCG: 0.8003
Validation  random nDCG: 0.3264

--> Improvement! Best nDCG: 0.8003
Epoch: 3, Batch: 288/289, Pred Mean: 0.2178, NDCG: 0.7654

Training nDCG: 0.7876
Training random nDCG: 0.3601

Batch (val): 41/41
Validation nDCG: 0.7785
Validation  random nDCG: 0.3692

--> No improvement. Patience: 1/4
Epoch: 4, Batch: 288/289, Pred Mean: 0.2294, NDCG: 0.7654

Training nDCG: 0.7972
Training random nDCG: 0.3635

Batch (val): 41/41
Validation nDCG: 0.7717
Validation  random nDCG: 0.3188

--> No improvement. Patience: 2/4
Epoch: 5, Batch: 288/289, Pred Mean: 0.2631, NDCG: 0.7654

Training nDCG: 0.8117
Training random nDCG: 0.3595

Batch (val): 41/41
Validation nDCG: 0.7816
Validation  random nDCG: 0.3941

--> No improvement. Patience: 3/4
Epoch: 6, Batch: 288/289, Pred Mean: 0.2496, NDCG: 0.7654

Training nDCG: 0.8169
Training random nDCG: 0.3499

Batch (val): 41/41

[I 2026-06-09 04:11:22,911] Trial 2 finished with value: 0.8002549589273851 and parameters: {'learning_rate': 0.0007506733115176721, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 4}. Best is trial 2 with value: 0.8002549589273851.

Validation nDCG: 0.7705
Validation  random nDCG: 0.3158

--> No improvement. Patience: 4/4

Early stopping triggered at epoch 6
Training for 15 epochs took 1449.47 seconds
Best hyperparameters: {'learning_rate': 0.0007506733115176721, 'embedding_size': 16, 'pooling_method': 'mean', 'heads': 4}

,model,prompt,inference,isco,learning_rate,embedding_size,pooling_method,heads,epochs,nDCG@10 (val)
0,qwen,structured,True,True,0.000438,128,max,4,13,0.808763
1,qwen,semi-structured,True,True,0.000238,128,mean,2,9,0.792956
2,qwen,unstructured,True,True,0.001033,16,max,2,9,0.812563
3,gemma,structured,True,True,0.000282,64,mean,2,5,0.814214
4,gemma,semi-structured,True,True,0.004548,128,sum,2,3,0.885389
5,gemma,unstructured,True,True,0.007879,8,max,4,4,0.841647
6,llama,structured,True,True,0.009736,16,mean,8,6,0.858868
7,llama,semi-structured,True,True,0.005019,64,sum,2,2,0.840683
8,llama,unstructured,True,True,0.000114,128,max,2,3,0.698263
9,qwen,structured,True,False,0.003904,128,sum,8,12,0.853009
10,qwen,semi-structured,True,False,0.000568,16,sum,8,12,0.857052
11,qwen,unstructured,True,False,0.000672,16,mean,8,3,0.787422
12,gemma,structured,True,False,0.000779,64,mean,4,4,0.848280
13,gemma,semi-structured,True,False,0.001978,16,max,8,7,0.891541
14,gemma,unstructured,True,False,0.002521,32,sum,8,4,0.871018
15,llama,structured,True,False,0.002599,64,sum,4,3,0.859637
16,llama,semi-structured,True,False,0.000540,128,max,4,2,0.805218
17,llama,unstructured,True,False,0.002038,16,mean,8,1,0.697860
18,qwen,structured,False,True,0.009396,16,mean,4,2,0.793214
19,qwen,semi-structured,False,True,0.008965,64,max,2,3,0.790987
20,qwen,unstructured,False,True,0.002199,128,mean,4,2,0.776169
21,gemma,structured,False,True,0.005491,64,mean,2,3,0.805098
22,gemma,semi-structured,False,True,0.000651,64,mean,8,2,0.796850
23,gemma,unstructured,False,True,0.002755,128,max,8,1,0.796879
24,llama,structured,False,True,0.002884,16,max,4,6,0.803814
25,llama,semi-structured,False,True,0.000202,128,sum,8,5,0.816646
26,llama,unstructured,False,True,0.000385,8,mean,2,2,0.796824
27,qwen,structured,False,False,0.000245,64,sum,8,1,0.787946
28,qwen,semi-structured,False,False,0.002570,128,max,4,1,0.789455
29,qwen,unstructured,False,False,0.000128,128,max,2,8,0.776503
30,gemma,structured,False,False,0.000341,8,max,2,7,0.812675
31,gemma,semi-structured,False,False,0.009195,16,sum,4,4,0.797722
32,gemma,unstructured,False,False,0.004919,8,mean,4,8,0.787783
33,llama,structured,False,False,0.002736,16,max,2,2,0.807892
34,llama,semi-structured,False,False,0.006971,128,sum,4,1,0.815378
35,llama,unstructured,False,False,0.000751,16,mean,4,2,0.800255

In [13]:
df_results = pd.read_csv("OKRA_validation.csv")

runs_to_do = set(
        zip(df_results['inference'].astype(bool), 
            df_results['isco'].astype(bool), 
            df_results['model'].astype(str), 
            df_results['prompt'].astype(str))
    )
print(f"Resuming... Found {len(completed_runs)} completed configurations.")

Resuming... Found 0 completed configurations.

# Evaluation

In [14]:
test_results = defaultdict(list)

for inference in [True, False]:
    for isco in [True, False]:
        for model in ["qwen", "gemma", "llama"]:
            for prompt in ["structured", "semi-structured", "unstructured"]:

                # Check if this combination was already evaluated
                if (inference, isco, model, prompt) not in runs_to_do:
                    print(f"Skipping {model} {prompt} with inference={inference} and isco={isco} (Already done)")
                    continue
                
                
                if inference:
                    if isco:
                        trainloader = torch.load(f'../dataloaders/graph_trainloader_{model}_{prompt}_isco.pth',
                                                 weights_only=False)
                        testloader = torch.load(f'../dataloaders/graph_testloader_{model}_{prompt}_isco.pth',
                                               weights_only=False)
                    else:
                        trainloader = torch.load(f'../dataloaders/graph_trainloader_{model}_{prompt}.pth',
                                                 weights_only=False)
                        testloader = torch.load(f'../dataloaders/graph_testloader_{model}_{prompt}.pth',
                                               weights_only=False)
                else:
                    if isco:
                        trainloader = torch.load(f'../dataloaders/{model}_{prompt}_isco_trainloader_no_inference.pth',
                                                 weights_only=False)
                        testloader = torch.load(f'../dataloaders/{model}_{prompt}_isco_testloader_no_inference.pth',
                                               weights_only=False)
                    else:
                        trainloader = torch.load(f'../dataloaders/{model}_{prompt}_trainloader_no_inference.pth',
                                                 weights_only=False)
                        testloader = torch.load(f'../dataloaders/{model}_{prompt}_testloader_no_inference.pth',
                                               weights_only=False)

                optimal_parameters = df_results[(df_results["model"] == model) & 
                    (df_results["prompt"] == prompt) &
                    (df_results["inference"] == inference) & 
                    (df_results["isco"] == isco)].iloc[0].values

                learning_rate = float(optimal_parameters[5])
                embedding_size = int(optimal_parameters[6])
                pooling_method = optimal_parameters[7]
                heads = int(optimal_parameters[8])
                epochs = int(optimal_parameters[9])
                
                print(f"""
                Config:
                - learning_rate = {learning_rate}
                - embedding_size = {embedding_size}
                - pooling_method = {pooling_method}
                - heads = {heads}
                """)

                example_batch = next(iter(trainloader))

                okra = OKRA(
                    metadata=example_batch.metadata(),
                    embedding_size=embedding_size,
                    pooling_method=pooling_method,
                    heads=heads
                ).to(device)
            
                # Configure Optimizer
                optimizer = torch.optim.Adam(okra.parameters(), lr=learning_rate)
                
                start_time = time.time() 
                
                # Train and test model
                ndcg_scores_test = train_loop(okra, optimizer, trainloader, testloader,
                                              epochs=epochs, patience=99, kind="test")

                test_results["model"].append(model)
                test_results["prompt"].append(prompt)
                test_results["inference"].append(inference)
                test_results["isco"].append(isco)
                test_results["nDCG@10 (test)"].append(ndcg_scores_test[0])

df_test_results = pd.DataFrame(test_results)
df_test_results.to_csv("OKRA_test.csv")
display(df_test_results)

                Config:
                - learning_rate = 0.000438233385699
                - embedding_size = 128
                - pooling_method = max
                - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.0027, NDCG: 1.0000

Training nDCG: 0.6656
Training random nDCG: 0.3613

Batch (test): 37/37
Test nDCG: 0.7461
Test  random nDCG: 0.3548

--> Improvement! Best nDCG: 0.7461
Epoch: 2, Batch: 288/289, Pred Mean: 0.2765, NDCG: 0.8855

Training nDCG: 0.7972
Training random nDCG: 0.3698

Batch (test): 37/37
Test nDCG: 0.7568
Test  random nDCG: 0.3861

--> Improvement! Best nDCG: 0.7568
Epoch: 3, Batch: 288/289, Pred Mean: 0.1891, NDCG: 0.8855

Training nDCG: 0.8081
Training random nDCG: 0.3516

Batch (test): 37/37
Test nDCG: 0.7481
Test  random nDCG: 0.3250

--> No improvement. Patience: 1/99
Epoch: 4, Batch: 288/289, Pred Mean: 0.7354, NDCG: 0.9675

Training nDCG: 0.8280
Training random nDCG: 0.3751

Batch (test): 37/37
Test nDCG: 0.7576
Test  random nDCG: 0.3888

--> Improvement! Best nDCG: 0.7576
Epoch: 5, Batch: 288/289, Pred Mean: 0.3431, NDCG: 0.9675

Training nDCG: 0.8425
Training random nDCG: 0.3561

Batch (test): 37/37
Test nDCG: 0.7580
Test  random nDCG: 0.4052

--> Improvement! Best nDCG: 0.7580
Epoch: 6, Batch: 288/289, Pred Mean: 0.4821, NDCG: 0.9675

Training nDCG: 0.8585
Training random nDCG: 0.3585

Batch (test): 37/37
Test nDCG: 0.7525
Test  random nDCG: 0.3405

--> No improvement. Patience: 1/99
Epoch: 7, Batch: 288/289, Pred Mean: 0.7292, NDCG: 0.8529

Training nDCG: 0.8791
Training random nDCG: 0.3693

Batch (test): 37/37
Test nDCG: 0.7512
Test  random nDCG: 0.3852

--> No improvement. Patience: 2/99
Epoch: 8, Batch: 288/289, Pred Mean: 0.4844, NDCG: 0.9060

Training nDCG: 0.8975
Training random nDCG: 0.3897

Batch (test): 37/37
Test nDCG: 0.7355
Test  random nDCG: 0.4127

--> No improvement. Patience: 3/99
Epoch: 9, Batch: 288/289, Pred Mean: 0.6647, NDCG: 0.8711

Training nDCG: 0.9077
Training random nDCG: 0.3604

Batch (test): 37/37
Test nDCG: 0.7651
Test  random nDCG: 0.4037

--> Improvement! Best nDCG: 0.7651
Epoch: 10, Batch: 288/289, Pred Mean: 0.1281, NDCG: 0.9469

Training nDCG: 0.9197
Training random nDCG: 0.3913

Batch (test): 37/37
Test nDCG: 0.7459
Test  random nDCG: 0.3880

--> No improvement. Patience: 1/99
Epoch: 11, Batch: 288/289, Pred Mean: 0.2770, NDCG: 0.9469

Training nDCG: 0.9276
Training random nDCG: 0.3669

Batch (test): 37/37
Test nDCG: 0.7552
Test  random nDCG: 0.3990

--> No improvement. Patience: 2/99
Epoch: 12, Batch: 288/289, Pred Mean: 0.0490, NDCG: 0.9218

Training nDCG: 0.9289
Training random nDCG: 0.3810

Batch (test): 37/37
Test nDCG: 0.7621
Test  random nDCG: 0.3823

--> No improvement. Patience: 3/99
Epoch: 13, Batch: 288/289, Pred Mean: 0.3752, NDCG: 0.9675

Training nDCG: 0.9299
Training random nDCG: 0.3749

Batch (test): 37/37
Test nDCG: 0.7537
Test  random nDCG: 0.3906

--> No improvement. Patience: 4/99

                Config:
                - learning_rate = 0.0002378601555888
                - embedding_size = 128
                - pooling_method = mean
                - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.2926, NDCG: 0.7123

Training nDCG: 0.6868
Training random nDCG: 0.3616

Batch (test): 37/37
Test nDCG: 0.8191
Test  random nDCG: 0.4369

--> Improvement! Best nDCG: 0.8191
Epoch: 2, Batch: 288/289, Pred Mean: 0.8060, NDCG: 0.6797

Training nDCG: 0.7798
Training random nDCG: 0.3673

Batch (test): 37/37
Test nDCG: 0.7983
Test  random nDCG: 0.4261

--> No improvement. Patience: 1/99
Epoch: 3, Batch: 288/289, Pred Mean: 1.0825, NDCG: 0.8529

Training nDCG: 0.8044
Training random nDCG: 0.3743

Batch (test): 37/37
Test nDCG: 0.8121
Test  random nDCG: 0.3757

--> No improvement. Patience: 2/99
Epoch: 4, Batch: 288/289, Pred Mean: 1.1384, NDCG: 0.8529

Training nDCG: 0.8421
Training random nDCG: 0.3446

Batch (test): 37/37
Test nDCG: 0.8255
Test  random nDCG: 0.3587

--> Improvement! Best nDCG: 0.8255
Epoch: 5, Batch: 288/289, Pred Mean: 1.1898, NDCG: 0.8855

Training nDCG: 0.8613
Training random nDCG: 0.3881

Batch (test): 37/37
Test nDCG: 0.8250
Test  random nDCG: 0.4105

--> No improvement. Patience: 1/99
Epoch: 6, Batch: 288/289, Pred Mean: 1.2278, NDCG: 0.9060

Training nDCG: 0.8775
Training random nDCG: 0.3778

Batch (test): 37/37
Test nDCG: 0.8045
Test  random nDCG: 0.3795

--> No improvement. Patience: 2/99
Epoch: 7, Batch: 288/289, Pred Mean: 9.3802, NDCG: 0.6979

Training nDCG: 0.8897
Training random nDCG: 0.3684

Batch (test): 37/37
Test nDCG: 0.7811
Test  random nDCG: 0.3694

--> No improvement. Patience: 3/99
Epoch: 8, Batch: 288/289, Pred Mean: 1.7249, NDCG: 0.6039

Training nDCG: 0.9035
Training random nDCG: 0.3637

Batch (test): 37/37
Test nDCG: 0.7987
Test  random nDCG: 0.3943

--> No improvement. Patience: 4/99
Epoch: 9, Batch: 288/289, Pred Mean: 1.6953, NDCG: 0.7328

Training nDCG: 0.9034
Training random nDCG: 0.3595

Batch (test): 37/37
Test nDCG: 0.7785
Test  random nDCG: 0.4199

--> No improvement. Patience: 5/99

                Config:
                - learning_rate = 0.0010330327505085
                - embedding_size = 16
                - pooling_method = max
                - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.4533, NDCG: 0.6509

Training nDCG: 0.6351
Training random nDCG: 0.3798

Batch (test): 37/37
Test nDCG: 0.7296
Test  random nDCG: 0.3837

--> Improvement! Best nDCG: 0.7296
Epoch: 2, Batch: 288/289, Pred Mean: 0.7432, NDCG: 0.5706

Training nDCG: 0.7569
Training random nDCG: 0.3951

Batch (test): 37/37
Test nDCG: 0.7325
Test  random nDCG: 0.3831

--> Improvement! Best nDCG: 0.7325
Epoch: 3, Batch: 288/289, Pred Mean: 0.8316, NDCG: 0.8772

Training nDCG: 0.7726
Training random nDCG: 0.3785

Batch (test): 37/37
Test nDCG: 0.7770
Test  random nDCG: 0.4117

--> Improvement! Best nDCG: 0.7770
Epoch: 4, Batch: 288/289, Pred Mean: 0.7525, NDCG: 1.0000

Training nDCG: 0.7952
Training random nDCG: 0.3780

Batch (test): 37/37
Test nDCG: 0.7391
Test  random nDCG: 0.4158

--> No improvement. Patience: 1/99
Epoch: 5, Batch: 288/289, Pred Mean: 0.6688, NDCG: 1.0000

Training nDCG: 0.8101
Training random nDCG: 0.3975

Batch (test): 37/37
Test nDCG: 0.7482
Test  random nDCG: 0.4635

--> No improvement. Patience: 2/99
Epoch: 6, Batch: 288/289, Pred Mean: 0.5971, NDCG: 1.0000

Training nDCG: 0.8269
Training random nDCG: 0.3879

Batch (test): 37/37
Test nDCG: 0.7448
Test  random nDCG: 0.3607

--> No improvement. Patience: 3/99
Epoch: 7, Batch: 288/289, Pred Mean: 0.8056, NDCG: 0.9197

Training nDCG: 0.8468
Training random nDCG: 0.3730

Batch (test): 37/37
Test nDCG: 0.7481
Test  random nDCG: 0.4183

--> No improvement. Patience: 4/99
Epoch: 8, Batch: 288/289, Pred Mean: 0.7048, NDCG: 1.0000

Training nDCG: 0.8545
Training random nDCG: 0.3866

Batch (test): 37/37
Test nDCG: 0.7237
Test  random nDCG: 0.4559

--> No improvement. Patience: 5/99
Epoch: 9, Batch: 288/289, Pred Mean: 0.8707, NDCG: 1.0000

Training nDCG: 0.8643
Training random nDCG: 0.3617

Batch (test): 37/37
Test nDCG: 0.7202
Test  random nDCG: 0.4380

--> No improvement. Patience: 6/99

                Config:
                - learning_rate = 0.0002823753072782
                - embedding_size = 64
                - pooling_method = mean
                - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: 0.2224, NDCG: 0.6797

Training nDCG: 0.6661
Training random nDCG: 0.3624

Batch (test): 37/37
Test nDCG: 0.7592
Test  random nDCG: 0.3928

--> Improvement! Best nDCG: 0.7592
Epoch: 2, Batch: 288/289, Pred Mean: 0.6754, NDCG: 0.6797

Training nDCG: 0.7808
Training random nDCG: 0.3460

Batch (test): 37/37
Test nDCG: 0.7676
Test  random nDCG: 0.4201

--> Improvement! Best nDCG: 0.7676
Epoch: 3, Batch: 288/289, Pred Mean: 0.9047, NDCG: 0.7123

Training nDCG: 0.7959
Training random nDCG: 0.3620

Batch (test): 37/37
Test nDCG: 0.7433
Test  random nDCG: 0.4486

--> No improvement. Patience: 1/99
Epoch: 4, Batch: 288/289, Pred Mean: 1.0174, NDCG: 0.6797

Training nDCG: 0.8311
Training random nDCG: 0.3338

Batch (test): 37/37
Test nDCG: 0.7761
Test  random nDCG: 0.3835

--> Improvement! Best nDCG: 0.7761
Epoch: 5, Batch: 288/289, Pred Mean: 1.1117, NDCG: 0.6797

Training nDCG: 0.8597
Training random nDCG: 0.3605

Batch (test): 37/37
Test nDCG: 0.7588
Test  random nDCG: 0.4214

--> No improvement. Patience: 1/99

                Config:
                - learning_rate = 0.0045479581890167
                - embedding_size = 128
                - pooling_method = sum
                - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -5.3500, NDCG: 0.9060

Training nDCG: 0.7484
Training random nDCG: 0.3547

Batch (test): 37/37
Test nDCG: 0.7581
Test  random nDCG: 0.4503

--> Improvement! Best nDCG: 0.7581
Epoch: 2, Batch: 288/289, Pred Mean: -0.0338, NDCG: 0.7328

Training nDCG: 0.8062
Training random nDCG: 0.3518

Batch (test): 37/37
Test nDCG: 0.8211
Test  random nDCG: 0.3737

--> Improvement! Best nDCG: 0.8211
Epoch: 3, Batch: 288/289, Pred Mean: 0.2804, NDCG: 0.7328

Training nDCG: 0.8255
Training random nDCG: 0.3532

Batch (test): 37/37
Test nDCG: 0.8351
Test  random nDCG: 0.3842

--> Improvement! Best nDCG: 0.8351

                Config:
                - learning_rate = 0.0078786733580466
                - embedding_size = 8
                - pooling_method = max
                - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.8968, NDCG: 1.0000

Training nDCG: 0.7645
Training random nDCG: 0.3800

Batch (test): 37/37
Test nDCG: 0.8187
Test  random nDCG: 0.4317

--> Improvement! Best nDCG: 0.8187
Epoch: 2, Batch: 288/289, Pred Mean: 0.4685, NDCG: 0.8855

Training nDCG: 0.8024
Training random nDCG: 0.3491

Batch (test): 37/37
Test nDCG: 0.8042
Test  random nDCG: 0.3768

--> No improvement. Patience: 1/99
Epoch: 3, Batch: 288/289, Pred Mean: 0.7425, NDCG: 0.9060

Training nDCG: 0.8086
Training random nDCG: 0.3514

Batch (test): 37/37
Test nDCG: 0.8033
Test  random nDCG: 0.3931

--> No improvement. Patience: 2/99
Epoch: 4, Batch: 288/289, Pred Mean: 0.3169, NDCG: 0.9060

Training nDCG: 0.8393
Training random nDCG: 0.3405

Batch (test): 37/37
Test nDCG: 0.8033
Test  random nDCG: 0.3971

--> No improvement. Patience: 3/99

                Config:
                - learning_rate = 0.0097362197893002
                - embedding_size = 16
                - pooling_method = mean
                - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 1.2309, NDCG: 0.8529

Training nDCG: 0.7705
Training random nDCG: 0.3283

Batch (test): 37/37
Test nDCG: 0.7580
Test  random nDCG: 0.4156

--> Improvement! Best nDCG: 0.7580
Epoch: 2, Batch: 288/289, Pred Mean: 1.2953, NDCG: 0.9469

Training nDCG: 0.8237
Training random nDCG: 0.3598

Batch (test): 37/37
Test nDCG: 0.7344
Test  random nDCG: 0.3900

--> No improvement. Patience: 1/99
Epoch: 3, Batch: 288/289, Pred Mean: 1.4988, NDCG: 0.9469

Training nDCG: 0.8310
Training random nDCG: 0.3732

Batch (test): 37/37
Test nDCG: 0.7648
Test  random nDCG: 0.3949

--> Improvement! Best nDCG: 0.7648
Epoch: 4, Batch: 288/289, Pred Mean: 1.7843, NDCG: 0.9469

Training nDCG: 0.8379
Training random nDCG: 0.3767

Batch (test): 37/37
Test nDCG: 0.7620
Test  random nDCG: 0.3809

--> No improvement. Patience: 1/99
Epoch: 5, Batch: 288/289, Pred Mean: 1.8572, NDCG: 0.9060

Training nDCG: 0.8466
Training random nDCG: 0.3873

Batch (test): 37/37
Test nDCG: 0.7607
Test  random nDCG: 0.3478

--> No improvement. Patience: 2/99
Epoch: 6, Batch: 288/289, Pred Mean: 1.6673, NDCG: 0.8855

Training nDCG: 0.8262
Training random nDCG: 0.3656

Batch (test): 37/37
Test nDCG: 0.7730
Test  random nDCG: 0.3896

--> Improvement! Best nDCG: 0.7730

                Config:
                - learning_rate = 0.0050188820424944
                - embedding_size = 64
                - pooling_method = sum
                - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -3.6583, NDCG: 0.8772

Training nDCG: 0.7634
Training random nDCG: 0.3920

Batch (test): 37/37
Test nDCG: 0.8269
Test  random nDCG: 0.4035

--> Improvement! Best nDCG: 0.8269
Epoch: 2, Batch: 288/289, Pred Mean: -3.8793, NDCG: 0.8772

Training nDCG: 0.7988
Training random nDCG: 0.3585

Batch (test): 37/37
Test nDCG: 0.8276
Test  random nDCG: 0.3777

--> Improvement! Best nDCG: 0.8276

                Config:
                - learning_rate = 0.0001137471190563
                - embedding_size = 128
                - pooling_method = max
                - heads = 2

Epoch: 1, Batch: 288/289, Pred Mean: -0.1255, NDCG: 1.0000

Training nDCG: 0.5816
Training random nDCG: 0.4182

Batch (test): 37/37
Test nDCG: 0.7157
Test  random nDCG: 0.4149

--> Improvement! Best nDCG: 0.7157
Epoch: 2, Batch: 288/289, Pred Mean: -0.0877, NDCG: 1.0000

Training nDCG: 0.7343
Training random nDCG: 0.4063

Batch (test): 37/37
Test nDCG: 0.7813
Test  random nDCG: 0.4965

--> Improvement! Best nDCG: 0.7813
Epoch: 3, Batch: 288/289, Pred Mean: 0.1024, NDCG: 1.0000

Training nDCG: 0.7661
Training random nDCG: 0.3954

Batch (test): 37/37
Test nDCG: 0.8006
Test  random nDCG: 0.4368

--> Improvement! Best nDCG: 0.8006

                Config:
                - learning_rate = 0.0039035309714451
                - embedding_size = 128
                - pooling_method = sum
                - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -0.5993, NDCG: 0.7328

Training nDCG: 0.7450
Training random nDCG: 0.3838

Batch (test): 37/37
Test nDCG: 0.7565
Test  random nDCG: 0.3546

--> Improvement! Best nDCG: 0.7565
Epoch: 2, Batch: 288/289, Pred Mean: -1.4810, NDCG: 0.9675

Training nDCG: 0.7695
Training random nDCG: 0.3695

Batch (test): 37/37
Test nDCG: 0.7736
Test  random nDCG: 0.3998

--> Improvement! Best nDCG: 0.7736
Epoch: 3, Batch: 288/289, Pred Mean: 0.1284, NDCG: 0.9675

Training nDCG: 0.7850
Training random nDCG: 0.3695

Batch (test): 37/37
Test nDCG: 0.7524
Test  random nDCG: 0.3645

--> No improvement. Patience: 1/99
Epoch: 4, Batch: 288/289, Pred Mean: 2.6420, NDCG: 0.9060

Training nDCG: 0.8124
Training random nDCG: 0.3439

Batch (test): 37/37
Test nDCG: 0.7428
Test  random nDCG: 0.4114

--> No improvement. Patience: 2/99
Epoch: 5, Batch: 288/289, Pred Mean: 2.3809, NDCG: 0.7328

Training nDCG: 0.8041
Training random nDCG: 0.3795

Batch (test): 37/37
Test nDCG: 0.7173
Test  random nDCG: 0.3555

--> No improvement. Patience: 3/99
Epoch: 6, Batch: 288/289, Pred Mean: 3.5159, NDCG: 0.7328

Training nDCG: 0.8049
Training random nDCG: 0.3809

Batch (test): 37/37
Test nDCG: 0.7384
Test  random nDCG: 0.4145

--> No improvement. Patience: 4/99
Epoch: 7, Batch: 288/289, Pred Mean: 1.9747, NDCG: 0.7328

Training nDCG: 0.8063
Training random nDCG: 0.3661

Batch (test): 37/37
Test nDCG: 0.7301
Test  random nDCG: 0.3869

--> No improvement. Patience: 5/99
Epoch: 8, Batch: 288/289, Pred Mean: 0.8951, NDCG: 0.7328

Training nDCG: 0.8114
Training random nDCG: 0.3910

Batch (test): 37/37
Test nDCG: 0.7353
Test  random nDCG: 0.4349

--> No improvement. Patience: 6/99
Epoch: 9, Batch: 288/289, Pred Mean: 3.0046, NDCG: 0.7328

Training nDCG: 0.8216
Training random nDCG: 0.3794

Batch (test): 37/37
Test nDCG: 0.7418
Test  random nDCG: 0.3853

--> No improvement. Patience: 7/99
Epoch: 10, Batch: 288/289, Pred Mean: 2.1722, NDCG: 0.7328

Training nDCG: 0.8283
Training random nDCG: 0.3593

Batch (test): 37/37
Test nDCG: 0.7383
Test  random nDCG: 0.3117

--> No improvement. Patience: 8/99
Epoch: 11, Batch: 288/289, Pred Mean: 2.8530, NDCG: 0.7328

Training nDCG: 0.8298
Training random nDCG: 0.3852

Batch (test): 37/37
Test nDCG: 0.7243
Test  random nDCG: 0.4520

--> No improvement. Patience: 9/99
Epoch: 12, Batch: 288/289, Pred Mean: 3.9671, NDCG: 0.7328

Training nDCG: 0.8283
Training random nDCG: 0.3635

Batch (test): 37/37
Test nDCG: 0.7287
Test  random nDCG: 0.4312

--> No improvement. Patience: 10/99

                Config:
                - learning_rate = 0.0005681959974084
                - embedding_size = 16
                - pooling_method = sum
                - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: -0.1199, NDCG: 0.4982

Training nDCG: 0.5521
Training random nDCG: 0.3509

Batch (test): 37/37
Test nDCG: 0.6480
Test  random nDCG: 0.4246

--> Improvement! Best nDCG: 0.6480
Epoch: 2, Batch: 288/289, Pred Mean: 0.1890, NDCG: 0.6797

Training nDCG: 0.7305
Training random nDCG: 0.3668

Batch (test): 37/37
Test nDCG: 0.7866
Test  random nDCG: 0.4706

--> Improvement! Best nDCG: 0.7866
Epoch: 3, Batch: 288/289, Pred Mean: 0.5217, NDCG: 0.6979

Training nDCG: 0.7859
Training random nDCG: 0.3631

Batch (test): 37/37
Test nDCG: 0.7830
Test  random nDCG: 0.3704

--> No improvement. Patience: 1/99
Epoch: 4, Batch: 288/289, Pred Mean: 0.5809, NDCG: 0.6797

Training nDCG: 0.8060
Training random nDCG: 0.3393

Batch (test): 37/37
Test nDCG: 0.7743
Test  random nDCG: 0.4501

--> No improvement. Patience: 2/99
Epoch: 5, Batch: 288/289, Pred Mean: 0.6233, NDCG: 0.8711

Training nDCG: 0.8404
Training random nDCG: 0.3776

Batch (test): 37/37
Test nDCG: 0.7752
Test  random nDCG: 0.4395

--> No improvement. Patience: 3/99
Epoch: 6, Batch: 288/289, Pred Mean: 0.4450, NDCG: 0.9325

Training nDCG: 0.8474
Training random nDCG: 0.3673

Batch (test): 37/37
Test nDCG: 0.7828
Test  random nDCG: 0.4239

--> No improvement. Patience: 4/99
Epoch: 7, Batch: 288/289, Pred Mean: 0.4778, NDCG: 0.8711

Training nDCG: 0.8599
Training random nDCG: 0.3598

Batch (test): 37/37
Test nDCG: 0.7772
Test  random nDCG: 0.3995

--> No improvement. Patience: 5/99
Epoch: 8, Batch: 288/289, Pred Mean: 0.4629, NDCG: 0.9325

Training nDCG: 0.8696
Training random nDCG: 0.3554

Batch (test): 37/37
Test nDCG: 0.7614
Test  random nDCG: 0.4615

--> No improvement. Patience: 6/99
Epoch: 9, Batch: 288/289, Pred Mean: 0.5291, NDCG: 0.7123

Training nDCG: 0.8711
Training random nDCG: 0.3852

Batch (test): 37/37
Test nDCG: 0.7644
Test  random nDCG: 0.4180

--> No improvement. Patience: 7/99
Epoch: 10, Batch: 288/289, Pred Mean: 0.1803, NDCG: 0.8855

Training nDCG: 0.8894
Training random nDCG: 0.3554

Batch (test): 37/37
Test nDCG: 0.7627
Test  random nDCG: 0.4421

--> No improvement. Patience: 8/99
Epoch: 11, Batch: 288/289, Pred Mean: 0.4611, NDCG: 0.8711

Training nDCG: 0.8867
Training random nDCG: 0.3565

Batch (test): 37/37
Test nDCG: 0.7655
Test  random nDCG: 0.4063

--> No improvement. Patience: 9/99
Epoch: 12, Batch: 288/289, Pred Mean: 1.3047, NDCG: 0.6340

Training nDCG: 0.8978
Training random nDCG: 0.3610

Batch (test): 37/37
Test nDCG: 0.7598
Test  random nDCG: 0.3556

--> No improvement. Patience: 10/99

                Config:
                - learning_rate = 0.0006724992879192
                - embedding_size = 16
                - pooling_method = mean
                - heads = 8

Epoch: 1, Batch: 288/289, Pred Mean: 0.0497, NDCG: 0.6934

Training nDCG: 0.6004
Training random nDCG: 0.3715

Batch (test): 37/37
Test nDCG: 0.7695
Test  random nDCG: 0.4632

--> Improvement! Best nDCG: 0.7695
Epoch: 2, Batch: 288/289, Pred Mean: 0.3838, NDCG: 0.6934

Training nDCG: 0.7565
Training random nDCG: 0.3740

Batch (test): 37/37
Test nDCG: 0.7765
Test  random nDCG: 0.4320

--> Improvement! Best nDCG: 0.7765
Epoch: 3, Batch: 288/289, Pred Mean: 0.5978, NDCG: 0.6934

Training nDCG: 0.7617
Training random nDCG: 0.3928

Batch (test): 37/37
Test nDCG: 0.7611
Test  random nDCG: 0.4008

--> No improvement. Patience: 1/99

                Config:
                - learning_rate = 0.0007787269065665
                - embedding_size = 64
                - pooling_method = mean
                - heads = 4

Epoch: 1, Batch: 288/289, Pred Mean: 0.6784, NDCG: 0.7328

Training nDCG: 0.7107
Training random nDCG: 0.3628

Batch (test): 37/37
Test nDCG: 0.7945
Test  random nDCG: 0.4242

--> Improvement! Best nDCG: 0.7945
Epoch: 2, Batch: 288/289, Pred Mean: 1.0292, NDCG: 0.7328

Training nDCG: 0.7988
Training random nDCG: 0.3610

Batch (test): 37/37
Test nDCG: 0.7732
Test  random nDCG: 0.4152

--> No improvement. Patience: 1/99
Epoch: 3, Batch: 288/289, Pred Mean: 1.1688, NDCG: 0.9675


    model           prompt  inference   isco  nDCG@10 (test)
0    qwen       structured       True   True        0.765140
1    qwen  semi-structured       True   True        0.825452
2    qwen     unstructured       True   True        0.776981
3   gemma       structured       True   True        0.776130
4   gemma  semi-structured       True   True        0.835118
5   gemma     unstructured       True   True        0.818695
6   llama       structured       True   True        0.772975
7   llama  semi-structured       True   True        0.827648
8   llama     unstructured       True   True        0.800592
9    qwen       structured       True  False        0.773577
10   qwen  semi-structured       True  False        0.786575
11   qwen     unstructured       True  False        0.776501
12  gemma       structured       True  False        0.794525
13  gemma  semi-structured       True  False        0.818975
14  gemma     unstructured       True  False        0.847828
15  llama       structured       True  False        0.783279
16  llama  semi-structured       True  False        0.820562
17  llama     unstructured       True  False        0.857670
18   qwen       structured      False   True        0.784685
19   qwen  semi-structured      False   True        0.764806
20   qwen     unstructured      False   True        0.740483
21  gemma       structured      False   True        0.754946
22  gemma  semi-structured      False   True        0.738779
23  gemma     unstructured      False   True        0.744088
24  llama       structured      False   True        0.771449
25  llama  semi-structured      False   True        0.743554
26  llama     unstructured      False   True        0.620735
27   qwen       structured      False  False        0.744088
28   qwen  semi-structured      False  False        0.760462
29   qwen     unstructured      False  False        0.738333
30  gemma       structured      False  False        0.745566
31  gemma  semi-structured      False  False        0.761756
32  gemma     unstructured      False  False        0.754698
33  llama       structured      False  False        0.756250
34  llama  semi-structured      False  False        0.715474
35  llama     unstructured      False  False        0.743202